.TH "RATA_PDF/src Directory Reference" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhist_maker\&.cpp\fP"
.br
.RI "\fIFunctions to calculate the PDF uncertainties\&. The functions will be called by tha \fBRATA_PDF\fP package\&. \fP"
.in -1c
