.TH "CrabConfigParser" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrabConfigParser \- 
.PP
This module extends the python configparser to create crab3 config files\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This module extends the python configparser to create crab3 config files\&. 

This module extends the python configparser to create crab3 config files\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
