.TH "scripts/television.py" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/television.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtelevision\&.NoDaemonProcess\fP"
.br
.ti -1c
.RI "class \fBtelevision\&.NoDaemonPool\fP"
.br
.ti -1c
.RI "class \fBtelevision\&.Overview\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBtelevision\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtelevision\&.terminate\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.addtime\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.timerepr\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.checkTask\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.nextUpdate\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.resubmitByStatus\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.addToList\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.getRunTimeFromHistory\fP"
.br
.ti -1c
.RI "def \fBtelevision\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtelevision\&.waitingForExit\fP = False"
.br
.ti -1c
.RI "tuple \fBtelevision\&.parser\fP = optparse\&.OptionParser( description='Monitor for ce tasks', usage='usage: %prog directories')"
.br
.ti -1c
.RI "tuple \fBtelevision\&.task\fP = cesubmit\&.Task\&.load(directory)"
.br
.ti -1c
.RI "tuple \fBtelevision\&.pp\fP = pprint\&.PrettyPrinter(indent=2)"
.br
.ti -1c
.RI "\fBtelevision\&.passphrase\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
