.TH "television.NoDaemonPool" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
television.NoDaemonPool \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Pool\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBProcess\fP = \fBNoDaemonProcess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file television\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "television\&.NoDaemonPool\&.Process = \fBNoDaemonProcess\fP\fC [static]\fP"

.PP
Definition at line 33 of file television\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
