.TH "todo" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBhelper\&.farewell_output\fP \fP" 1c
fix the crash at the end of the program  
.IP "\fBMember \fBRATA_PDF\&.calc_pdf_uncer\fP \fP" 1c
outfile parameters 
.PP
include copier '\fBsignal_mover\&.py\fP'  
.IP "\fBMember \fBRATA_PDF\&.pdf_file_loop\fP \fP" 1c
change to multiprocessing 
.PP
calculate expected run time 
.PP

