.TH "scripts/watchfrog.py" 3 "Wed Feb 4 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/watchfrog.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwatchfrog\&.Overview\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBwatchfrog\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwatchfrog\&.runserver\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.main\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.runGui\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.printFrogArt\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.mp_crab_worker\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.crab_worker\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.getAllCrabFolders\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.addInfoHeader\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.timerepr\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.formatedUnixTimestamp\fP"
.br
.ti -1c
.RI "def \fBwatchfrog\&.commandline_parsing\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBwatchfrog\&.serverLock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "tuple \fBwatchfrog\&.optionsLock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "tuple \fBwatchfrog\&.mylogger\fP = logging\&.getLogger('watchfrog')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
