.TH "examples/remoteProduction Directory Reference" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/remoteProduction Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBB2G-Phys14DR-00002_3_cfg\&.py\fP"
.br
.ti -1c
.RI "file \fBbinConfig\&.py\fP"
.br
.ti -1c
.RI "file \fBhadronizer_match_pu_2_cfg\&.py\fP"
.br
.ti -1c
.RI "file \fBremoteProduction\&.py\fP"
.br
.ti -1c
.RI "file \fBremoteProductionMiniAOD\&.py\fP"
.br
.in -1c
