.TH "aix3a2Finder" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3a2Finder \- 
.PP
Get sample info from \fBaix3adb\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Get sample info from \fBaix3adb\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Tobias Pook 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
