aix3adb2music
NAME
aix3adb2music -
SYNOPSIS
Functions
def commandline_parsing
def readSampleFile
def getSkimAndSampleList
def flattenRemoteSkimDict
def getProcessGroup
Workaround until ProcessGroup is implemented.
def getConfigDicts
def writeConfigDicts
def main
Variables
string COMMENT_CHAR = '#'
list log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
string date = '%F %H:%M:%S'
tuple log = logging.getLogger( 'aix3a2music' )
Function Documentation
def aix3adb2music.commandline_parsing ()
Definition at line 34 of file aix3adb2music.py.
References cesubmit.getCernUserName().
Referenced by main().
def aix3adb2music.flattenRemoteSkimDict (remoteDict, datasections)
Definition at line 103 of file aix3adb2music.py.
Referenced by remoteAnalysis.prepareConfigs().
def aix3adb2music.getConfigDicts (skimlist)
Definition at line 129 of file aix3adb2music.py.
References getProcessGroup().
Referenced by main(), and remoteAnalysis.prepareConfigs().
def aix3adb2music.getProcessGroup (processname)
Workaround until ProcessGroup is implemented. match process name by tags to a Group
Definition at line 115 of file aix3adb2music.py.
Referenced by getConfigDicts().
def aix3adb2music.getSkimAndSampleList (args)
Definition at line 78 of file aix3adb2music.py.
References remoteAnalysis.readConfig(), and readSampleFile().
Referenced by main().
def aix3adb2music.main ()
Definition at line 183 of file aix3adb2music.py.
References commandline_parsing(), aix3adb.createDBlink(), getConfigDicts(), getSkimAndSampleList(), and writeConfigDicts().
def aix3adb2music.readSampleFile (filename)
Definition at line 53 of file aix3adb2music.py.
Referenced by getSkimAndSampleList().
def aix3adb2music.writeConfigDicts (scalesdict, playlistdict, configdir = '', lumi = 1)
Definition at line 158 of file aix3adb2music.py.
Referenced by main(), and remoteAnalysis.prepareConfigs().
Variable Documentation
string aix3adb2music.COMMENT_CHAR = '#'
Definition at line 27 of file aix3adb2music.py.
string aix3adb2music.date = '%F %H:%M:%S'
Definition at line 29 of file aix3adb2music.py.
tuple aix3adb2music.log = logging.getLogger( 'aix3a2music' )
Definition at line 32 of file aix3adb2music.py.
list aix3adb2music.log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
Definition at line 28 of file aix3adb2music.py.
Author
Generated automatically by Doxygen for not_found from the source code.