.TH "scripts/aix3adb2music.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/aix3adb2music.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBaix3adb2music\fP"
.br
.ti -1c
.RI "\fBaix3a2music\fP"
.br
.RI "\fICreate MUSiC config files from aix3db\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBaix3adb2music\&.commandline_parsing\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.readSampleFile\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.getSkimAndSampleList\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.flattenRemoteSkimDict\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.getProcessGroup\fP"
.br
.RI "\fIWorkaround until ProcessGroup is implemented\&. \fP"
.ti -1c
.RI "def \fBaix3adb2music\&.getConfigDicts\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.writeConfigDicts\fP"
.br
.ti -1c
.RI "def \fBaix3adb2music\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBaix3adb2music\&.COMMENT_CHAR\fP = '#'"
.br
.ti -1c
.RI "list \fBaix3adb2music\&.log_choices\fP = [ '\fBERROR\fP', '\fBWARNING\fP', '\fBINFO\fP', '\fBDEBUG\fP' ]"
.br
.ti -1c
.RI "string \fBaix3adb2music\&.date\fP = '%F %H:%M:%S'"
.br
.ti -1c
.RI "tuple \fBaix3adb2music\&.log\fP = logging\&.getLogger( 'aix3a2music' )"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
