.TH "aix3adbSampleFinder" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adbSampleFinder \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcommandline_parsing\fP"
.br
.ti -1c
.RI "def \fBSkimAndSampleSummary\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def aix3adbSampleFinder\&.commandline_parsing ()"

.PP
Definition at line 12 of file aix3adbSampleFinder\&.py\&.
.PP
Referenced by main()\&.
.SS "def aix3adbSampleFinder\&.main ()"

.PP
Definition at line 31 of file aix3adbSampleFinder\&.py\&.
.PP
References commandline_parsing(), lumi\&.format, SkimAndSampleSummary(), and HistClass\&.split()\&.
.SS "def aix3adbSampleFinder\&.SkimAndSampleSummary (skim, sample)"

.PP
Definition at line 23 of file aix3adbSampleFinder\&.py\&.
.PP
References lumi\&.format\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
