.TH "aix3adb.Aix3adbException" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.Aix3adbException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Definition at line 23 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
