.TH "aix3adb.MCSkim" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.MCSkim \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaix3adb\&.Aix3adbBaseElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__repr__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file aix3adb\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def aix3adb\&.Aix3adbBaseElement\&.__repr__ (self)\fC [inherited]\fP"

.PP
Definition at line 32 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
