B2G-Phys14DR-00002_3_cfg
NAME
B2G-Phys14DR-00002_3_cfg -
SYNOPSIS
Variables
tuple process = cms.Process('PAT')
tuple input = cms.untracked.int32(82)
tuple secondaryFileNames = cms.untracked.vstring()
tuple fileNames = cms.untracked.vstring('file:test.root')
tuple allowUnscheduled = cms.untracked.bool(True)
tuple version = cms.untracked.string('$Revision: 1.19 $')
tuple annotation = cms.untracked.string('step3 nevts:82')
tuple name = cms.untracked.string('Applications')
tuple compressionLevel = cms.untracked.int32(4)
tuple compressionAlgorithm = cms.untracked.string('LZMA')
tuple eventAutoFlushCompressedSize = cms.untracked.int32(15728640)
outputCommands = process.MINIAODSIMEventContent.outputCommands,
tuple fileName = cms.untracked.string('file:testMiniAOD.root')
tuple dataset
tuple dropMetaData = cms.untracked.string('ALL')
tuple fastCloning = cms.untracked.bool(False)
tuple overrideInputFileSplitLevels = cms.untracked.bool(True)
Variable Documentation
tuple B2G-Phys14DR-00002_3_cfg.allowUnscheduled = cms.untracked.bool(True)
Definition at line 32 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.annotation = cms.untracked.string('step3 nevts:82')
Definition at line 38 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.compressionAlgorithm = cms.untracked.string('LZMA')
Definition at line 46 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.compressionLevel = cms.untracked.int32(4)
Definition at line 45 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.dataset
Initial value:
= cms.untracked.PSet(
        filterName = cms.untracked.string(''),
        dataTier = cms.untracked.string('MINIAODSIM')
    )
Definition at line 50 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.dropMetaData = cms.untracked.string('ALL')
Definition at line 54 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.eventAutoFlushCompressedSize = cms.untracked.int32(15728640)
Definition at line 47 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.fastCloning = cms.untracked.bool(False)
Definition at line 55 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.fileName = cms.untracked.string('file:testMiniAOD.root')
Definition at line 49 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.fileNames = cms.untracked.vstring('file:test.root')
Definition at line 28 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.input = cms.untracked.int32(82)
Definition at line 22 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.name = cms.untracked.string('Applications')
Definition at line 39 of file B2G-Phys14DR-00002_3_cfg.py.
Referenced by HistClass.CreateTree(), HistClass.FillTree(), HistClass.WriteAll(), HistClass.WriteAll2(), HistClass.WriteAllEff(), HistClass.WriteAllProf(), HistClass.WriteAllTrees(), and HistClass.WriteN().
B2G-Phys14DR-00002_3_cfg.outputCommands = process.MINIAODSIMEventContent.outputCommands,
Definition at line 48 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.overrideInputFileSplitLevels = cms.untracked.bool(True)
Definition at line 56 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.process = cms.Process('PAT')
Definition at line 8 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.secondaryFileNames = cms.untracked.vstring()
Definition at line 27 of file B2G-Phys14DR-00002_3_cfg.py.
tuple B2G-Phys14DR-00002_3_cfg.version = cms.untracked.string('$Revision: 1.19 $')
Definition at line 37 of file B2G-Phys14DR-00002_3_cfg.py.
Author
Generated automatically by Doxygen for not_found from the source code.