.TH "examples/remoteProduction/B2G-Phys14DR-00002_3_cfg.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/remoteProduction/B2G-Phys14DR-00002_3_cfg.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBB2G-Phys14DR-00002_3_cfg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.process\fP = cms\&.Process('PAT')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.input\fP = cms\&.untracked\&.int32(82)"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.secondaryFileNames\fP = cms\&.untracked\&.vstring()"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.fileNames\fP = cms\&.untracked\&.vstring('file:test\&.root')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.allowUnscheduled\fP = cms\&.untracked\&.bool(True)"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.version\fP = cms\&.untracked\&.string('$Revision: 1\&.19 $')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.annotation\fP = cms\&.untracked\&.string('step3 nevts:82')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.name\fP = cms\&.untracked\&.string('Applications')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.compressionLevel\fP = cms\&.untracked\&.int32(4)"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.compressionAlgorithm\fP = cms\&.untracked\&.string('LZMA')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.eventAutoFlushCompressedSize\fP = cms\&.untracked\&.int32(15728640)"
.br
.ti -1c
.RI "\fBB2G-Phys14DR-00002_3_cfg\&.outputCommands\fP = process\&.MINIAODSIMEventContent\&.outputCommands,"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.fileName\fP = cms\&.untracked\&.string('file:testMiniAOD\&.root')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.dataset\fP"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.dropMetaData\fP = cms\&.untracked\&.string('ALL')"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.fastCloning\fP = cms\&.untracked\&.bool(False)"
.br
.ti -1c
.RI "tuple \fBB2G-Phys14DR-00002_3_cfg\&.overrideInputFileSplitLevels\fP = cms\&.untracked\&.bool(True)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
