.TH "examples/remoteProduction/binConfig.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/remoteProduction/binConfig.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBbinConfig\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBbinConfig\&.cpFiles\fP = ['bin','ConfigFiles','lib']"
.br
.ti -1c
.RI "tuple \fBbinConfig\&.PathtoExecutable\fP = os\&.getenv( 'MUSIC_BASE' )"
.br
.ti -1c
.RI "string \fBbinConfig\&.outDir\fP = '/user/USER/out'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
