.TH "binConfig" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBcpFiles\fP = ['bin','ConfigFiles','lib']"
.br
.ti -1c
.RI "tuple \fBPathtoExecutable\fP = os\&.getenv( 'MUSIC_BASE' )"
.br
.ti -1c
.RI "string \fBoutDir\fP = '/user/USER/out'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list binConfig\&.cpFiles = ['bin','ConfigFiles','lib']"

.PP
Definition at line 2 of file binConfig\&.py\&.
.SS "string binConfig\&.outDir = '/user/USER/out'"

.PP
Definition at line 4 of file binConfig\&.py\&.
.SS "tuple binConfig\&.PathtoExecutable = os\&.getenv( 'MUSIC_BASE' )"

.PP
Definition at line 3 of file binConfig\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
