cesubmit
NAME
cesubmit -
SYNOPSIS
Classes
class Job
class Task
class ProxyError
Functions
def submitWorker
def runWorker
def resubmitWorker
def killWorker
def getCernUserName
def createAndUploadGridPack
def uploadGridPack
def parseGetOutput
def parseStatus
def parseStatusMultiple
def parseStatusMultipleL1
def chunks
def timeLeftVomsProxy
def checkVomsProxy
def renewVomsProxy
def checkAndRenewVomsProxy
Variables
tuple log = logging.getLogger(__name__)
Function Documentation
def cesubmit.checkAndRenewVomsProxy (time = 604800, voms = 'cms:/cms/dcms', passphrase = None)
Definition at line 763 of file cesubmit.py.
References checkVomsProxy(), and renewVomsProxy().
Referenced by television.main(), and cesubmit.Job.submit().
def cesubmit.checkVomsProxy (time = 86400)
Returns True if the proxy is valid longer than time, False otherwise.
Definition at line 745 of file cesubmit.py.
References timeLeftVomsProxy().
Referenced by checkAndRenewVomsProxy().
def cesubmit.chunks (l, n)
Yield successive n-sized chunks from l.
Definition at line 725 of file cesubmit.py.
Referenced by cesubmit.Task._getStatusMultiple(), and cesubmit.Task.getOutput().
def cesubmit.createAndUploadGridPack (localfiles, uploadurl, tarfile = 'gridpacktemp.tar.gz', uploadsite = 'srm://grid-srm.physik.rwth-aachen.de:8443/srm/managerv2\?SFN=/pnfs/physik.rwth-aachen.de/cms/store/user/{username}/')
Definition at line 48 of file cesubmit.py.
References uploadGridPack().
Referenced by submit.main().
def cesubmit.getCernUserName ()
Definition at line 36 of file cesubmit.py.
Referenced by remoteAnalysis.checkGridpack(), aix3adb2music.commandline_parsing(), cesubmit.Task.makePrologue(), and uploadGridPack().
def cesubmit.killWorker (job)
Definition at line 32 of file cesubmit.py.
def cesubmit.parseGetOutput (stdout)
Definition at line 659 of file cesubmit.py.
Referenced by cesubmit.Task.getOutput().
def cesubmit.parseStatus (stdout)
Definition at line 673 of file cesubmit.py.
def cesubmit.parseStatusMultiple (stdout)
Definition at line 685 of file cesubmit.py.
def cesubmit.parseStatusMultipleL1 (stdout)
Definition at line 701 of file cesubmit.py.
Referenced by cesubmit.Task._getStatusMultiple().
def cesubmit.renewVomsProxy (voms = 'cms:/cms/dcms', passphrase = None)
Make a new proxy with a lifetime of one week.
Definition at line 750 of file cesubmit.py.
Referenced by checkAndRenewVomsProxy().
def cesubmit.resubmitWorker (job)
Definition at line 28 of file cesubmit.py.
def cesubmit.runWorker (job)
Definition at line 24 of file cesubmit.py.
def cesubmit.submitWorker (job)
Definition at line 20 of file cesubmit.py.
def cesubmit.timeLeftVomsProxy ()
Definition at line 734 of file cesubmit.py.
Referenced by checkVomsProxy(), and television.main().
def cesubmit.uploadGridPack (tarfile, uploadurl, uploadsite = 'srm://grid-srm.physik.rwth-aachen.de:8443/srm/managerv2\?SFN=/pnfs/physik.rwth-aachen.de/cms/store/user/{username}/', force = False)
Definition at line 61 of file cesubmit.py.
References lumi.format, getCernUserName(), and raw_input().
Referenced by remoteAnalysis.checkGridpack(), and createAndUploadGridPack().
Variable Documentation
tuple cesubmit.log = logging.getLogger(__name__)
Definition at line 16 of file cesubmit.py.
Author
Generated automatically by Doxygen for not_found from the source code.