.TH "examples/crabConfigParserTester.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/crabConfigParserTester.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcrabConfigParserTester\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBcrabConfigParserTester\&.requestName\fP = 'ParserTestName'"
.br
.ti -1c
.RI "string \fBcrabConfigParserTester\&.workArea\fP = '/user/pook/crab/'"
.br
.ti -1c
.RI "string \fBcrabConfigParserTester\&.mypset\fP = 'testpset\&.py'"
.br
.ti -1c
.RI "string \fBcrabConfigParserTester\&.datasetpath\fP = '/T_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Spring14miniaod-PU20bx25_POSTLS170_V5-v1/MINIAODSIM'"
.br
.ti -1c
.RI "int \fBcrabConfigParserTester\&.unitsPerJob\fP = 10"
.br
.ti -1c
.RI "tuple \fBcrabConfigParserTester\&.config\fP = CrabConfigParser()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
