.TH "crabConfigParserTester" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crabConfigParserTester \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBrequestName\fP = 'ParserTestName'"
.br
.ti -1c
.RI "string \fBworkArea\fP = '/user/pook/crab/'"
.br
.ti -1c
.RI "string \fBmypset\fP = 'testpset\&.py'"
.br
.ti -1c
.RI "string \fBdatasetpath\fP = '/T_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Spring14miniaod-PU20bx25_POSTLS170_V5-v1/MINIAODSIM'"
.br
.ti -1c
.RI "int \fBunitsPerJob\fP = 10"
.br
.ti -1c
.RI "tuple \fBconfig\fP = \fBCrabConfigParser\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple crabConfigParserTester\&.config = \fBCrabConfigParser\fP()"

.PP
Definition at line 13 of file crabConfigParserTester\&.py\&.
.SS "string crabConfigParserTester\&.datasetpath = '/T_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Spring14miniaod-PU20bx25_POSTLS170_V5-v1/MINIAODSIM'"

.PP
Definition at line 10 of file crabConfigParserTester\&.py\&.
.SS "string crabConfigParserTester\&.mypset = 'testpset\&.py'"

.PP
Definition at line 9 of file crabConfigParserTester\&.py\&.
.SS "string crabConfigParserTester\&.requestName = 'ParserTestName'"

.PP
Definition at line 6 of file crabConfigParserTester\&.py\&.
.SS "int crabConfigParserTester\&.unitsPerJob = 10"

.PP
Definition at line 11 of file crabConfigParserTester\&.py\&.
.SS "string crabConfigParserTester\&.workArea = '/user/pook/crab/'"

.PP
Definition at line 7 of file crabConfigParserTester\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
