.TH "crabFunctions.CrabTask" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crabFunctions.CrabTask \- 
.PP
Class for a single CrabRequest\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIThe object constructor\&. \fP"
.ti -1c
.RI "def \fBisData\fP"
.br
.RI "\fIProperty function to find out if task runs on data\&. \fP"
.ti -1c
.RI "def \fBcrabConfig\fP"
.br
.RI "\fIFunction to access crab config object or read it if unititalized\&. \fP"
.ti -1c
.RI "def \fBglobalTag\fP"
.br
.ti -1c
.RI "def \fBskimmer_version\fP"
.br
.ti -1c
.RI "def \fBjson_file\fP"
.br
.ti -1c
.RI "def \fBinDB\fP"
.br
.ti -1c
.RI "def \fBisFinal\fP"
.br
.ti -1c
.RI "def \fBupdateFromDB\fP"
.br
.ti -1c
.RI "def \fBresubmit_failed\fP"
.br
.RI "\fIFunction to resubmit failed jobs in tasks\&. \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIFunction to update Task in associated Jobs\&. \fP"
.ti -1c
.RI "def \fBhandleNoState\fP"
.br
.RI "\fIFunction to handle Task which received NOSTATE status\&. \fP"
.ti -1c
.RI "def \fBtest_print\fP"
.br
.ti -1c
.RI "def \fBupdateJobStats\fP"
.br
.RI "\fIFunction to update JobStatistics\&. \fP"
.ti -1c
.RI "def \fBreadLogArch\fP"
.br
.RI "\fIFunction to read log info from log\&.tar\&.gz\&. \fP"
.ti -1c
.RI "def \fBfinalizeTask\fP"
.br
.RI "\fIFunction to finalize task in TAPAS workflow\&. \fP"
.ti -1c
.RI "def \fBaddData2db\fP"
.br
.ti -1c
.RI "def \fBaddMC2db\fP"
.br
.ti -1c
.RI "def \fBfillCommonSkimFields\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBuuid\fP"
.br
.ti -1c
.RI "\fBjobs\fP"
.br
.ti -1c
.RI "\fBlocalDir\fP"
.br
.ti -1c
.RI "\fBoutlfn\fP"
.br
.ti -1c
.RI "\fBisUpdating\fP"
.br
.ti -1c
.RI "\fBtaskId\fP"
.br
.ti -1c
.RI "\fBnJobs\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBmaxjobnumber\fP"
.br
.ti -1c
.RI "\fBnUnsubmitted\fP"
.br
.ti -1c
.RI "\fBnIdle\fP"
.br
.ti -1c
.RI "\fBnRunning\fP"
.br
.ti -1c
.RI "\fBnTransferring\fP"
.br
.ti -1c
.RI "\fBnCooloff\fP"
.br
.ti -1c
.RI "\fBnFailed\fP"
.br
.ti -1c
.RI "\fBnFinished\fP"
.br
.ti -1c
.RI "\fBnComplete\fP"
.br
.ti -1c
.RI "\fBfailureReason\fP"
.br
.ti -1c
.RI "\fBlastUpdate\fP"
.br
.ti -1c
.RI "\fBdblink\fP"
.br
.ti -1c
.RI "\fBresubmitCount\fP"
.br
.ti -1c
.RI "\fBdebug\fP"
.br
.ti -1c
.RI "\fBfinalFiles\fP"
.br
.ti -1c
.RI "\fBtotalEvents\fP"
.br
.ti -1c
.RI "\fBdbSkim\fP"
.br
.ti -1c
.RI "\fBdbSample\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_isData\fP"
.br
.ti -1c
.RI "\fB_crabConfig\fP"
.br
.ti -1c
.RI "\fB_inDB\fP"
.br
.ti -1c
.RI "\fB_globalTag_default\fP"
.br
.ti -1c
.RI "\fB_skimmer_version_default\fP"
.br
.ti -1c
.RI "\fB_json_file_default\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for a single CrabRequest\&. 

This class represents one crab3 task/request 
.PP
Definition at line 328 of file crabFunctions\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def crabFunctions\&.CrabTask\&.__init__ (self, taskname, crabController = \fCNone\fP, initUpdate = \fCTrue\fP, dblink = \fCNone\fP, localDir = \fC''\fP, outlfn = \fC''\fP, globalTag = \fCNone\fP, skimmer_version = \fCNone\fP, json_file = \fCNone\fP)"

.PP
The object constructor\&. self: \fBCrabTask\fP 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&.  taskname: String 
.br
\fItaskname,:\fP The object pointer\&.  initUpdate: Boolean 
.br
\fIinitUpdate,:\fP Flag if crab status should be called when an instance is created 
.RE
.PP

.PP
Definition at line 346 of file crabFunctions\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def crabFunctions\&.CrabTask\&.addData2db (self, update = \fCFalse\fP)"

.PP
Definition at line 687 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.dbSample, crabFunctions\&.CrabTask\&.dbSkim, crabFunctions\&.CrabTask\&.fillCommonSkimFields(), cesubmit\&.Task\&.name, and crabFunctions\&.CrabTask\&.name\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.finalizeTask(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.addMC2db (self, update = \fCFalse\fP)"

.PP
Definition at line 721 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.dbSample, crabFunctions\&.CrabTask\&.dbSkim, crabFunctions\&.CrabTask\&.fillCommonSkimFields(), cesubmit\&.Task\&.name, and crabFunctions\&.CrabTask\&.name\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.finalizeTask(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.crabConfig (self)"

.PP
Function to access crab config object or read it if unititalized\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP \fBCrabTask\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 412 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._crabConfig, cesubmit\&.Task\&.name, and crabFunctions\&.CrabTask\&.name\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.fillCommonSkimFields (self)"

.PP
Definition at line 773 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.finalFiles, and crabFunctions\&.CrabTask\&.totalEvents\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.addData2db(), and crabFunctions\&.CrabTask\&.addMC2db()\&.
.SS "def crabFunctions\&.CrabTask\&.finalizeTask (self, update = \fCFalse\fP, debug = \fCFalse\fP)"

.PP
Function to finalize task in TAPAS workflow\&. Get config files and submit samples 
.PP
Definition at line 643 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.addData2db(), crabFunctions\&.CrabTask\&.addMC2db(), crabFunctions\&.CrabTask\&.finalFiles, gridFunctions\&.getdcachelist(), crabFunctions\&.CrabTask\&.isData(), cesubmit\&.Task\&.name, crabFunctions\&.CrabTask\&.name, crabFunctions\&.CrabTask\&.readLogArch(), HistClass\&.split(), crabFunctions\&.CrabTask\&.state, and crabFunctions\&.CrabTask\&.totalEvents\&.
.SS "def crabFunctions\&.CrabTask\&.globalTag (self)"

.PP
Definition at line 419 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._globalTag_default\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.handleNoState (self)"

.PP
Function to handle Task which received NOSTATE status\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP \fBCrabTask\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 564 of file crabFunctions\&.py\&.
.PP
References cesubmit\&.Task\&.name, crabFunctions\&.CrabTask\&.name, crabFunctions\&.CrabTask\&.resubmitCount, and crabFunctions\&.CrabTask\&.state\&.
.SS "def crabFunctions\&.CrabTask\&.inDB (self)"

.PP
Definition at line 457 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._inDB, crabFunctions\&.CrabTask\&.state, and crabFunctions\&.CrabTask\&.updateFromDB()\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.isFinal(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.isData (self)"

.PP
Property function to find out if task runs on data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP \fBCrabTask\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 395 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._isData\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.finalizeTask(), crabFunctions\&.CrabTask\&.json_file(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.isFinal (self)"

.PP
Definition at line 471 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.dbSkim, crabFunctions\&.CrabTask\&.inDB(), and crabFunctions\&.CrabTask\&.state\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.json_file (self)"

.PP
Definition at line 444 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._json_file_default, and crabFunctions\&.CrabTask\&.isData()\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.readLogArch (self, logArchName)"

.PP
Function to read log info from log\&.tar\&.gz\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIlogArchName,:\fP path to the compressed log file 
.RE
.PP
\fBReturns:\fP
.RS 4
a dictionary with parsed info 
.RE
.PP

.PP
Definition at line 621 of file crabFunctions\&.py\&.
.PP
References HistClass\&.split()\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.finalizeTask()\&.
.SS "def crabFunctions\&.CrabTask\&.resubmit_failed (self)"

.PP
Function to resubmit failed jobs in tasks\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP \fBCrabTask\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 507 of file crabFunctions\&.py\&.
.PP
References cesubmit\&.Task\&.jobs, crabFunctions\&.CrabTask\&.jobs, crabFunctions\&.CrabTask\&.lastUpdate, cesubmit\&.Task\&.name, and crabFunctions\&.CrabTask\&.name\&.
.SS "def crabFunctions\&.CrabTask\&.skimmer_version (self)"

.PP
Definition at line 431 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&._skimmer_version_default\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "def crabFunctions\&.CrabTask\&.test_print (self)"

.PP
Definition at line 580 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.uuid\&.
.SS "def crabFunctions\&.CrabTask\&.update (self, updateDB = \fCFalse\fP)"

.PP
Function to update Task in associated Jobs\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP \fBCrabTask\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 520 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.addData2db(), crabFunctions\&.CrabTask\&.addMC2db(), crabFunctions\&.CrabTask\&.crabConfig(), crabFunctions\&.CrabTask\&.failureReason, crabFunctions\&.CrabTask\&.globalTag(), crabFunctions\&.CrabTask\&.inDB(), crabFunctions\&.CrabTask\&.isData(), crabFunctions\&.CrabTask\&.isFinal(), crabFunctions\&.CrabTask\&.isUpdating, cesubmit\&.Task\&.jobs, crabFunctions\&.CrabTask\&.jobs, crabFunctions\&.CrabTask\&.json_file(), crabFunctions\&.CrabTask\&.lastUpdate, cesubmit\&.Task\&.name, crabFunctions\&.CrabTask\&.name, crabFunctions\&.CrabTask\&.nFinished, crabFunctions\&.CrabTask\&.nJobs, crabFunctions\&.CrabTask\&.resubmitCount, crabFunctions\&.CrabTask\&.skimmer_version(), crabFunctions\&.CrabTask\&.state, and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "def crabFunctions\&.CrabTask\&.updateFromDB (self)"

.PP
Definition at line 477 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.inDB()\&.
.SS "def crabFunctions\&.CrabTask\&.updateJobStats (self, dCacheFileList = \fCNone\fP)"

.PP
Function to update JobStatistics\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIdCacheFilelist,:\fP A list of files on the dCache 
.RE
.PP

.PP
Definition at line 586 of file crabFunctions\&.py\&.
.PP
References cesubmit\&.Task\&.jobs, crabFunctions\&.CrabTask\&.jobs, cesubmit\&.Task\&.name, crabFunctions\&.CrabTask\&.name, and crabFunctions\&.CrabTask\&.nComplete\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SH "Member Data Documentation"
.PP 
.SS "crabFunctions\&.CrabTask\&._crabConfig\fC [private]\fP"

.PP
Definition at line 379 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.crabConfig()\&.
.SS "crabFunctions\&.CrabTask\&._globalTag_default\fC [private]\fP"

.PP
Definition at line 382 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.globalTag()\&.
.SS "crabFunctions\&.CrabTask\&._inDB\fC [private]\fP"

.PP
Definition at line 380 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.inDB()\&.
.SS "crabFunctions\&.CrabTask\&._isData\fC [private]\fP"

.PP
Definition at line 370 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.isData()\&.
.SS "crabFunctions\&.CrabTask\&._json_file_default\fC [private]\fP"

.PP
Definition at line 384 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.json_file()\&.
.SS "crabFunctions\&.CrabTask\&._skimmer_version_default\fC [private]\fP"

.PP
Definition at line 383 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.skimmer_version()\&.
.SS "crabFunctions\&.CrabTask\&.dblink"

.PP
Definition at line 371 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.dbSample"

.PP
Definition at line 496 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.addData2db(), and crabFunctions\&.CrabTask\&.addMC2db()\&.
.SS "crabFunctions\&.CrabTask\&.dbSkim"

.PP
Definition at line 495 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.addData2db(), crabFunctions\&.CrabTask\&.addMC2db(), and crabFunctions\&.CrabTask\&.isFinal()\&.
.SS "crabFunctions\&.CrabTask\&.debug"

.PP
Definition at line 374 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.failureReason"

.PP
Definition at line 367 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.finalFiles"

.PP
Definition at line 376 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.fillCommonSkimFields(), and crabFunctions\&.CrabTask\&.finalizeTask()\&.
.SS "crabFunctions\&.CrabTask\&.isUpdating"

.PP
Definition at line 353 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.jobs"

.PP
Definition at line 350 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.resubmit_failed(), crabFunctions\&.CrabTask\&.update(), and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "crabFunctions\&.CrabTask\&.lastUpdate"

.PP
Definition at line 368 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.resubmit_failed(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.localDir"

.PP
Definition at line 351 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.maxjobnumber"

.PP
Definition at line 358 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.name"

.PP
Definition at line 347 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.addData2db(), crabFunctions\&.CrabTask\&.addMC2db(), crabFunctions\&.CrabTask\&.crabConfig(), crabFunctions\&.CrabTask\&.finalizeTask(), crabFunctions\&.CrabTask\&.handleNoState(), parseSampleList\&.mc_sample\&.parse_name(), crabFunctions\&.CrabTask\&.resubmit_failed(), crabFunctions\&.CrabTask\&.update(), and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "crabFunctions\&.CrabTask\&.nComplete"

.PP
Definition at line 366 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "crabFunctions\&.CrabTask\&.nCooloff"

.PP
Definition at line 363 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nFailed"

.PP
Definition at line 364 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nFinished"

.PP
Definition at line 365 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.nIdle"

.PP
Definition at line 360 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nJobs"

.PP
Definition at line 356 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.nRunning"

.PP
Definition at line 361 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nTransferring"

.PP
Definition at line 362 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nUnsubmitted"

.PP
Definition at line 359 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.outlfn"

.PP
Definition at line 352 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.resubmitCount"

.PP
Definition at line 372 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.handleNoState(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.state"

.PP
Definition at line 357 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.finalizeTask(), crabFunctions\&.CrabTask\&.handleNoState(), crabFunctions\&.CrabTask\&.inDB(), crabFunctions\&.CrabTask\&.isFinal(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.taskId"

.PP
Definition at line 354 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.totalEvents"

.PP
Definition at line 377 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.fillCommonSkimFields(), and crabFunctions\&.CrabTask\&.finalizeTask()\&.
.SS "crabFunctions\&.CrabTask\&.uuid"

.PP
Definition at line 348 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.test_print()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
