crabFunctions.CrabController
NAME
crabFunctions.CrabController -
The CrabController class.
SYNOPSIS
Public Member Functions
def __init__
The constructor.
def checkwrite
Check if crab can write to specified site.
def submit
Check if crab can write to specified site.
def resubmit
Resubmit all failed tasks in job or specified list of jobs in task.
def checkusername
Returns the hn name for a user with valid proxy.
def status
Check crab status.
def callCrabCommand
Call crab command in a new process and return result dict.
def getlog
Call crab getlog.
def readCrabConfig
Read a crab config and return python object.
def crabFolders
Return list of all crab folders in workin area (default cwd)
def commandlineOptions
Populates an existing optparse parser or returns a new one with options for crab functions.
Public Attributes
debug
workingArea
dry_run
voGroup
username
logger
crab_q
Private Member Functions
def _prepareFoldername
Add crab_ to Foldername if needed.
Detailed Description
The CrabController class.
This class can be used to manage Analyses using crab3
Definition at line 35 of file crabFunctions.py.
Constructor & Destructor Documentation
def crabFunctions.CrabController.__init__ (self, debug = 0, logger = None, workingArea = None, voGroup = None, username = None)
The constructor. self: CrabController
Parameters:
self,: The object pointer. self: A logging logger instance
self,: A previously defined logger. Crab log messages will use this logger as their parent logger.
Definition at line 42 of file crabFunctions.py.
Member Function Documentation
def crabFunctions.CrabController._prepareFoldername (self, name) [private]
Add crab_ to Foldername if needed.
Parameters:
getlog(self,name)
Definition at line 239 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.getlog(), and crabFunctions.CrabController.resubmit().
def crabFunctions.CrabController.callCrabCommand (self, crabArgs)
Call crab command in a new process and return result dict.
Parameters:
self The object pointer
crabArgs A list of arguments for crab beginning with the command
Definition at line 189 of file crabFunctions.py.
References crabFunctions.CrabController.crab_q.
Referenced by crabFunctions.CrabController.getlog(), crabFunctions.CrabController.resubmit(), crabFunctions.CrabController.status(), and crabFunctions.CrabController.submit().
def crabFunctions.CrabController.checkusername (self)
Returns the hn name for a user with valid proxy. self: CrabController
Parameters:
self,: The object pointer.
Returns:
users hypernews name
Definition at line 145 of file crabFunctions.py.
References crabFunctions.CrabController.username.
Referenced by crabFunctions.CrabController.checkwrite().
def crabFunctions.CrabController.checkwrite (self, site = 'T2_DE_RWTH', path = 'noPath')
Check if crab can write to specified site. self: CrabController
Parameters:
self,: The object pointer. site string
site The Site symbol [default:T2_DE_RWTH] path string
path lfn path to check write permission in. see twiki WorkBookCRAB3Tutorial
Returns:
boolean which is True if user can write to site and False otherwise
Definition at line 85 of file crabFunctions.py.
References crabFunctions.CrabController.checkusername(), crabFunctions.CrabController.username, and crabFunctions.CrabController.voGroup.
def crabFunctions.CrabController.commandlineOptions (self, parser = optparse.OptionParser( 'usage: %prog' ))
Populates an existing optparse parser or returns a new one with options for crab functions. This functions populates a previously created (or new) instance of a optparse parser object with options needed by crab functions. It is possible to add three kinds of options:
options where a error should be raised if the option was previously defined
options where previous definitions should be kept
options where previous definitions should be overriden Optparse parser instance
Parameters:
parser A previously created parser oject which should be extenden [default: new instance]
Returns:
A new or extenden optparse parser instance
Definition at line 256 of file crabFunctions.py.
def crabFunctions.CrabController.crabFolders (self)
Return list of all crab folders in workin area (default cwd)
Parameters:
self The object pointer
Definition at line 231 of file crabFunctions.py.
References crabFunctions.CrabController.workingArea.
def crabFunctions.CrabController.getlog (self, name)
Call crab getlog.
Parameters:
self,: The object pointer. name string
Definition at line 201 of file crabFunctions.py.
References crabFunctions.CrabController._prepareFoldername(), and crabFunctions.CrabController.callCrabCommand().
def crabFunctions.CrabController.readCrabConfig (self, name)
Read a crab config and return python object.
Parameters:
self,: The object pointer.
name The sample name (crab request name)
Definition at line 215 of file crabFunctions.py.
def crabFunctions.CrabController.resubmit (self, name, joblist = None)
Resubmit all failed tasks in job or specified list of jobs in task. self: CrabController
Parameters:
self,: The object pointer. name string
name The crab3 request name, a.k.a the sample name joblist list of strings
joblist The crab3 request name, a.k.a the sample name
Definition at line 126 of file crabFunctions.py.
References crabFunctions.CrabController._prepareFoldername(), crabFunctions.CrabController.callCrabCommand(), crabFunctions.CrabController.dry_run, and crabFunctions.CrabController.workingArea.
def crabFunctions.CrabController.status (self, name)
Check crab status. self: CrabController
Parameters:
self,: The object pointer. name string
name The crab3 request name, a.k.a the sample name
Definition at line 165 of file crabFunctions.py.
References crabFunctions.CrabController.callCrabCommand(), and crabFunctions.CrabController.dry_run.
Referenced by lheanalyzer.Particle.__repr__().
def crabFunctions.CrabController.submit (self, name)
Check if crab can write to specified site.
Parameters:
self,: The object pointer. name string
name The crab3 config file name
Definition at line 108 of file crabFunctions.py.
References crabFunctions.CrabController.callCrabCommand(), crabFunctions.CrabController.debug, and crabFunctions.CrabController.dry_run.
Member Data Documentation
crabFunctions.CrabController.crab_q
Definition at line 75 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.callCrabCommand().
crabFunctions.CrabController.debug
Definition at line 43 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.submit().
crabFunctions.CrabController.dry_run
Definition at line 48 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.resubmit(), crabFunctions.CrabController.status(), and crabFunctions.CrabController.submit().
crabFunctions.CrabController.logger
Definition at line 59 of file crabFunctions.py.
crabFunctions.CrabController.username
Definition at line 54 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.checkusername(), and crabFunctions.CrabController.checkwrite().
crabFunctions.CrabController.voGroup
Definition at line 50 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.checkwrite().
crabFunctions.CrabController.workingArea
Definition at line 45 of file crabFunctions.py.
Referenced by crabFunctions.CrabController.crabFolders(), and crabFunctions.CrabController.resubmit().
Author
Generated automatically by Doxygen for not_found from the source code.