.TH "python/crabConfigParser.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/crabConfigParser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcrabConfigParser\&.CrabConfigParser\fP"
.br
.RI "\fIThe \fBCrabConfigParser\fP class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcrabConfigParser\fP"
.br
.ti -1c
.RI "\fBCrabConfigParser\fP"
.br
.RI "\fIThis module extends the python configparser to create crab3 config files\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
