curseshelpers.CursesMultiHandler
NAME
curseshelpers.CursesMultiHandler -
SYNOPSIS
Inherits Handler.
Public Member Functions
def __init__
def setFormatter
def receive
def send
def emit
def close
Public Attributes
queue
Private Member Functions
def _format_record
Private Attributes
_handler
Detailed Description
Definition at line 452 of file curseshelpers.py.
Constructor & Destructor Documentation
def curseshelpers.CursesMultiHandler.__init__ (self, stdscr, bottomText, log_q, level = logging.DEBUG)
Definition at line 453 of file curseshelpers.py.
Member Function Documentation
def curseshelpers.CursesMultiHandler._format_record (self, record) [private]
Definition at line 485 of file curseshelpers.py.
Referenced by curseshelpers.CursesMultiHandler.emit().
def curseshelpers.CursesMultiHandler.close (self)
Definition at line 508 of file curseshelpers.py.
def curseshelpers.CursesMultiHandler.emit (self, record)
Definition at line 499 of file curseshelpers.py.
References curseshelpers.CursesMultiHandler._format_record(), and curseshelpers.CursesMultiHandler.send().
def curseshelpers.CursesMultiHandler.receive (self)
Definition at line 468 of file curseshelpers.py.
def curseshelpers.CursesMultiHandler.send (self, s)
Definition at line 482 of file curseshelpers.py.
Referenced by curseshelpers.CursesMultiHandler.emit().
def curseshelpers.CursesMultiHandler.setFormatter (self, fmt)
Definition at line 464 of file curseshelpers.py.
Member Data Documentation
curseshelpers.CursesMultiHandler._handler [private]
Definition at line 456 of file curseshelpers.py.
curseshelpers.CursesMultiHandler.queue
Definition at line 458 of file curseshelpers.py.
Author
Generated automatically by Doxygen for not_found from the source code.