.TH "examples/eventView/eventView.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/eventView/eventView.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBeventView\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBeventView\&.efile\fP = \fBphyspic\&.EventFile\fP('events_after_cuts\&.txt')"
.br
.ti -1c
.RI "tuple \fBeventView\&.plot\fP = \fBphyspic\&.Plot\fP()"
.br
.ti -1c
.RI "list \fBeventView\&.partinfo\fP = []"
.br
.ti -1c
.RI "int \fBeventView\&.counter\fP = 0"
.br
.ti -1c
.RI "int \fBeventView\&.tester\fP = 0"
.br
.ti -1c
.RI "int \fBeventView\&.statustester\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
