.TH "eventView" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eventView \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBefile\fP = \fBphyspic\&.EventFile\fP('events_after_cuts\&.txt')"
.br
.ti -1c
.RI "tuple \fBplot\fP = \fBphyspic\&.Plot\fP()"
.br
.ti -1c
.RI "list \fBpartinfo\fP = []"
.br
.ti -1c
.RI "int \fBcounter\fP = 0"
.br
.ti -1c
.RI "int \fBtester\fP = 0"
.br
.ti -1c
.RI "int \fBstatustester\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int eventView\&.counter = 0"

.PP
Definition at line 20 of file eventView\&.py\&.
.SS "tuple eventView\&.efile = \fBphyspic\&.EventFile\fP('events_after_cuts\&.txt')"

.PP
Definition at line 6 of file eventView\&.py\&.
.SS "list eventView\&.partinfo = []"

.PP
Definition at line 19 of file eventView\&.py\&.
.SS "tuple eventView\&.plot = \fBphyspic\&.Plot\fP()"

.PP
Definition at line 16 of file eventView\&.py\&.
.SS "int eventView\&.statustester = 0"

.PP
Definition at line 29 of file eventView\&.py\&.
.SS "int eventView\&.tester = 0"

.PP
Definition at line 22 of file eventView\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
