gridFunctions
NAME
gridFunctions -
This module provides common functions for interaction with the local Tier2.
SYNOPSIS
Classes
class FileNotFound
Functions
def uberls
Get list of files and directories in dCap folder directory: string.
def cp
Copy a file / folder to the dCache source: string.
def cpFolder
Copy a folder to the dCache source: string.
def fileinfos
Get a dictionary of detailed file information of a remote file source: string.
def adler32
Get the adler32 hash value of a dCache file source: string.
def getdcachelist
Get list of files with certain file extension in dCap folder recursively dir: string.
def timeLeftVomsProxy
Returns the life time left.
def checkVomsProxy
Checks if the proxy is valid longer than time.
def renewVomsProxy
Creates a new vom proxy.
def checkAndRenewVomsProxy
Checks if the proxy is valid longer than time and renew if needed.
Detailed Description
This module provides common functions for interaction with the local Tier2.
Function Documentation
def gridFunctions.adler32 (source)
Get the adler32 hash value of a dCache file source: string.
Parameters:
source,: The dCap file path without /pnfs/physik.rwth-aachen.de/cms/store/user/
Definition at line 127 of file gridFunctions.py.
References fileinfos().
Referenced by remoteAnalysis.checkGridpack().
def gridFunctions.checkAndRenewVomsProxy (time = 604800, voms = 'cms:/cms/dcms', passphrase = None)
Checks if the proxy is valid longer than time and renew if needed. time: int
Parameters:
time,: reference time in seconds to check against
voms,: the voms group used to set up the server [default:cms:/cms/dcms] passphrase: string
passphrase,: Passphrase for GRID certificate [default:none]. The password request is send to the prompt if no passphrase given
Definition at line 228 of file gridFunctions.py.
References checkVomsProxy(), and renewVomsProxy().
Referenced by watchfrog.commandline_parsing(), music_crab3.commandline_parsing(), and remoteAnalysis.main().
def gridFunctions.checkVomsProxy (time = 86400)
Checks if the proxy is valid longer than time. time: int
Parameters:
time,: reference time in seconds to check against
Returns:
boolean returns True if the proxy is valid longer than time, False otherwise.
Definition at line 197 of file gridFunctions.py.
References timeLeftVomsProxy().
Referenced by checkAndRenewVomsProxy(), and watchfrog.commandline_parsing().
def gridFunctions.cp (source, target)
Copy a file / folder to the dCache source: string.
Parameters:
source,: The local path to the file / folder name. If you want to copy a folder, the path has to end with an '/'. target: string
target,: The dCap folder without /pnfs/physik.rwth-aachen.de/cms/store/user/. The folder has to end with an '/'
Definition at line 37 of file gridFunctions.py.
References fileinfos(), and raw_input().
Referenced by cpFolder().
def gridFunctions.cpFolder (source, target)
Copy a folder to the dCache source: string.
Parameters:
source,: The local path to the folder name target: string
target,: The dCap folder without /pnfs/physik.rwth-aachen.de/cms/store/user/
Definition at line 81 of file gridFunctions.py.
References cp(), and fileinfos().
def gridFunctions.fileinfos (source)
Get a dictionary of detailed file information of a remote file source: string.
Parameters:
source,: The dCap file path without /pnfs/physik.rwth-aachen.de/cms/store/user/
Definition at line 107 of file gridFunctions.py.
Referenced by adler32(), cp(), and cpFolder().
def gridFunctions.getdcachelist (dir, Tag = '', mem_limit = 500000000, fileXtension = '.pxlio')
Get list of files with certain file extension in dCap folder recursively dir: string.
Parameters:
dir,: The dCap folder without /pnfs/physik.rwth-aachen.de/cms/store/user/ mem_limit: int
mem_limit,: Maximum summed filesize before files are splitted in sublists [default:500000000]
Definition at line 140 of file gridFunctions.py.
References HistClass.split().
Referenced by crabFunctions.CrabTask.finalizeTask(), remote_example.getFilesfromFile(), and remoteAnalysis.prepareFileList().
def gridFunctions.renewVomsProxy (voms = 'cms:/cms/dcms', passphrase = None)
Creates a new vom proxy. This function creates a new voms: string
Parameters:
voms,: the voms group used to set up the server [default:cms:/cms/dcms] passphrase: string
passphrase,: Passphrase for GRID certificate [default:none]. The password request is send to the prompt if no passphrase given
Make a new proxy with a lifetime of one week.
Definition at line 208 of file gridFunctions.py.
Referenced by checkAndRenewVomsProxy().
def gridFunctions.timeLeftVomsProxy ()
Returns the life time left. for a proxy.
Returns:
int time left for the proxy
Definition at line 184 of file gridFunctions.py.
Referenced by checkVomsProxy().
def gridFunctions.uberls (directory)
Get list of files and directories in dCap folder directory: string.
Parameters:
directory,: The dCap folder without /pnfs/physik.rwth-aachen.de/cms/store/user/
Definition at line 13 of file gridFunctions.py.
References lumi.format.
Author
Generated automatically by Doxygen for not_found from the source code.