.TH "python/gridFunctions.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/gridFunctions.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgridFunctions\&.FileNotFound\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBgridFunctions\fP"
.br
.RI "\fIThis module provides common functions for interaction with the local Tier2\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgridFunctions\&.uberls\fP"
.br
.RI "\fIGet list of files and directories in dCap folder  directory: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.cp\fP"
.br
.RI "\fICopy a file / folder to the dCache  source: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.cpFolder\fP"
.br
.RI "\fICopy a folder to the dCache  source: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.fileinfos\fP"
.br
.RI "\fIGet a dictionary of detailed file information of a remote file  source: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.adler32\fP"
.br
.RI "\fIGet the adler32 hash value of a dCache file  source: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.getdcachelist\fP"
.br
.RI "\fIGet list of files with certain file extension in dCap folder recursively  dir: string\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.timeLeftVomsProxy\fP"
.br
.RI "\fIReturns the life time left\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.checkVomsProxy\fP"
.br
.RI "\fIChecks if the proxy is valid longer than time\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.renewVomsProxy\fP"
.br
.RI "\fICreates a new vom proxy\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.checkAndRenewVomsProxy\fP"
.br
.RI "\fIChecks if the proxy is valid longer than time and renew if needed\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
