.TH "examples/remoteProduction/hadronizer_match_pu_2_cfg.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/remoteProduction/hadronizer_match_pu_2_cfg.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBhadronizer_match_pu_2_cfg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.process\fP = cms\&.Process('HLT')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.input\fP = cms\&.untracked\&.int32(20)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.fileNames\fP = cms\&.untracked\&.vstring('/store/user/padeken/MC/DMV/PROC_NAME/File_NAME')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.version\fP = cms\&.untracked\&.string('$Revision: 1\&.19 $')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.annotation\fP = cms\&.untracked\&.string('Configuration/GenProduction/python/ThirteenTeV/Hadronizer_MgmMatchTune4C_hacked_13TeV_madgraph_pythia8_Tauola_cff\&.py nevts:1')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.name\fP = cms\&.untracked\&.string('Applications')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.compressionLevel\fP = cms\&.untracked\&.int32(4)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.compressionAlgorithm\fP = cms\&.untracked\&.string('LZMA')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.eventAutoFlushCompressedSize\fP = cms\&.untracked\&.int32(15728640)"
.br
.ti -1c
.RI "\fBhadronizer_match_pu_2_cfg\&.outputCommands\fP = process\&.AODSIMEventContent\&.outputCommands,"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.fileName\fP = cms\&.untracked\&.string('file:test\&.root')"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.dataset\fP"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.SelectEvents\fP"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.ExternalDecays\fP"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.maxEventsToPrint\fP = cms\&.untracked\&.int32(1)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.pythiaPylistVerbosity\fP = cms\&.untracked\&.int32(1)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.filterEfficiency\fP = cms\&.untracked\&.double(1\&.0)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.pythiaHepMCVerbosity\fP = cms\&.untracked\&.bool(False)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.comEnergy\fP = cms\&.double(13000\&.0)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.UseExternalGenerators\fP = cms\&.untracked\&.bool(True)"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.jetMatching\fP"
.br
.ti -1c
.RI "tuple \fBhadronizer_match_pu_2_cfg\&.PythiaParameters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
