HistClass
NAME
HistClass -
Functions to have easy histogram handling.
SYNOPSIS
Functions
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a number of 1D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a number of 1D histograms in the histo map for a specific particle.
static SUPPRESS_NOT_USED_WARN void CreateHistoUnchangedName (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a 1D histogram in the histo map without the standard histogram naming convention (h1_...)
static SUPPRESS_NOT_USED_WARN void CreateHisto (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateHisto (const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histogram in the histo map for a specific particle.
static SUPPRESS_NOT_USED_WARN void CreateHisto (boost::basic_format< char > name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histograms in the histo map with a boost name as input.
static SUPPRESS_NOT_USED_WARN void CreateHisto (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle='', TString ytitle='')
Function to create one 2D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle='', TString ytitle='')
Function to create a number of 2D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateNSparse (const char *name, int dimension, int *bins, double *xmin, double *xmax, std::string axisTitle[])
Function to create one NSparse in the nSparse map.
static SUPPRESS_NOT_USED_WARN void CreateTree (const char *name, const char *varlist, int bufsize)
Function to create one NtupleD in the NtupleD map.
static SUPPRESS_NOT_USED_WARN void CreateTree (std::unordered_map< std::string, float > *m, const char *name)
Function to create one Tree in the TTree map.
static SUPPRESS_NOT_USED_WARN void CreateEff (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, const char *xtitle='')
Function to create one 1D Efficiency container in the eff map.
static SUPPRESS_NOT_USED_WARN void CreateEff (const char *name, TH1D *hist_all, TH1D *hist_pass)
Function to create one 1D Efficiency container in the eff map from two histograms.
static SUPPRESS_NOT_USED_WARN void CreateEff (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, const char *xtitle='', const char *ytitle='')
Function to create one 2D Efficiency container in the eff map.
static SUPPRESS_NOT_USED_WARN void CreateProf (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, const char *xtitle='', const char *ytitle='')
Function to create one 1D Profile container in the eff map.
static void DeleteHisto (Int_t n_histos, const char *name)
Function to delete a histogram from the histo map.
static void RebinHisto (Int_t n_histos, const char *name, Int_t n_rebin, Double_t *bins)
Function to rebin histograms in the histo map.
static void Fill (Int_t n_histo, const char *name, double value, double weight)
Function to fill an event in a 1D histogram of the map.
static SUPPRESS_NOT_USED_WARN void Fill (Int_t n_histo, std::string name, double value, double weight)
Function to fill an event in a 1D histogram of the map with a string as histo name.
static SUPPRESS_NOT_USED_WARN void Fill (const char *name, double value, double weight)
Function to fill an event in a 1D histogram of the map without histo number.
static SUPPRESS_NOT_USED_WARN void FillStr (const char *name, const char *value, double weight)
Function to fill an event in a 1D histogram of the map without histo number.
static SUPPRESS_NOT_USED_WARN void FillStr (Int_t n_histo, const char *name, const char *value, double weight)
Function to fill an event in a 1D histogram of the map without histo number.
static SUPPRESS_NOT_USED_WARN void Fill (const char *name, double valuex, double valuey, double weight)
Function to fill an event in a 2D histogram of the map.
static SUPPRESS_NOT_USED_WARN void Fill (Int_t n_histo, const char *name, double valuex, double valuey, double weight)
Function to fill an event in a 2D histogram of the map.
static SUPPRESS_NOT_USED_WARN void FillSparse (const char *name, int n,...)
Function to fill an event in a nSparse of the nSparse map.
static SUPPRESS_NOT_USED_WARN void FillTree (const char *name, double *values)
Function to fill an event in a NTupleD of the map.
static SUPPRESS_NOT_USED_WARN void FillTree (const char *name)
Function to fill an event in a TTree of the map.
static SUPPRESS_NOT_USED_WARN void FillEff (const char *name, double valuex, bool passed)
Function to fill an event in a efficiency container of the map.
static SUPPRESS_NOT_USED_WARN void FillEff (const char *name, double valuex, double valuey, bool passed)
Function to fill an event in a 2D efficiency container of the map.
static SUPPRESS_NOT_USED_WARN void Profile (const char *name, double valuex, double valuey)
Function to fill an event in a 1D profile container of the map.
static SUPPRESS_NOT_USED_WARN void Write (Int_t n_histo, const char *name)
Function to write one 1D histogram of the map.
static SUPPRESS_NOT_USED_WARN void Write (const char *name)
Function to write one 1D histogram of the map without number.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name='')
Function to write many 1D histograms of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name='')
Function to write many 2D histograms of the map.
SUPPRESS_NOT_USED_WARN void split (const std::string &s, char delim, std::vector< std::string > *elems)
Function split a string at a delimiter.
SUPPRESS_NOT_USED_WARN
std::vector< std::string > split (const std::string &s, char delim)"
Function split a string at a delimiter and return the results.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name, const char *contains_i)
Function to write many 1D histograms which contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name, const char *contains_i)
Function to write many 2D histograms which contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name, const char *contains_i, const char *vetos_i)
Function to write many 1D histograms which (not) contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name, const char *contains_i, const char *vetos_i)
Function to write many 2D histograms which (not) contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAllTrees (const char *name='')
Function to write many TTrees and TNtupleDs of the maps.
static SUPPRESS_NOT_USED_WARN void WriteN (const char *name='')
Function to write many TNsparses of the map.
static SUPPRESS_NOT_USED_WARN void Write2 (const char *name)
Function to write one 2D histogram of the map.
static SUPPRESS_NOT_USED_WARN void WriteAllEff (const char *name='')
Function to write many efficiency containers of the map.
static SUPPRESS_NOT_USED_WARN void WriteAllEff (const char *name, const char *contains_i)
Function to write many efficiency containers which contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAllProf (const char *name='')
Function to write many profile containers of the map.
static SUPPRESS_NOT_USED_WARN void SetToZero (Int_t n_histo, const char *name)
Function to set all negative bin contents to zero for a 1D histogram.
static SUPPRESS_NOT_USED_WARN
TH1D * ReturnHist (const char *name)"
Function to get one 1D histogram from the map without number.
static SUPPRESS_NOT_USED_WARN void NameBins (const char *name, const uint n_bins, TString *d_mydisc)
Function to give one 1D histogram from the map alphanumeric bin labels without number.
static SUPPRESS_NOT_USED_WARN void NameBins (const char *name, const uint n_bins_x, TString *x_bin_names, const uint n_bins_y, TString *y_bin_names)
Function to give one 2D histogram from the map alphanumeric bin labels without number.
static SUPPRESS_NOT_USED_WARN void NameBins (Int_t n_histo, const char *name, const uint n_bins, TString *d_mydisc)
Function to give one 1D histogram from the map alphanumeric bin labels.
static SUPPRESS_NOT_USED_WARN void CleanUp ()
Function to clean up the memory usage of the HistClass.
static void CreateHisto (Int_t n_histos, const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create histograms in the histo map.
static void ClearHisto (Int_t n_histos, const char *name)
Function to clear histograms in the histo map.
static void RebinHisto (Int_t n_histos, const char *name, Int_t n_rebin, Double_t *bins)
Function to rebin histograms in the histo map.
static void Fill (Int_t n_histo, const char *name, double value, double weight)
Function to fille events in a histogram in the histo map.
static void Write (Int_t n_histo, const char *name)
Function to write a histogram from the histo map.
static void SetToZero (Int_t n_histo, const char *name)
Function to set every negative bin content to zero.
static TH1D * ReturnHist (Int_t n_histo, const char *name)
Function to get a histogram from the histo map.
static void DeleteHisto (Int_t n_histos, const char *name)
Function to delete a histogram from the histo map.
Variables
static std::unordered_map
< std::string, TH1D * > histo"
static std::unordered_map
< std::string, TH2D * > histo2"
static std::unordered_map
< std::string, THnSparseD * > histon"
static std::unordered_map
< std::string, TNtupleD * > ttupple"
static std::unordered_map
< std::string, TTree * > trees"
static std::unordered_map
< std::string, TEfficiency * > effs"
static std::unordered_map
< std::string, TProfile * > prof"
Detailed Description
Functions to have easy histogram handling.
In this namespace different functions to interact with the histogram map are included, to create, fill and write histograms in a convinient way.
Function Documentation
static SUPPRESS_NOT_USED_WARN void HistClass::CleanUp () [static]
Function to clean up the memory usage of the HistClass.
Definition at line 988 of file HistClass.hh.
References effs, histo, histo2, histon, trees, and ttupple.
static void HistClass::ClearHisto (Int_tn_histos, const char *name) [static]
Function to clear histograms in the histo map.
Parameters:
n_histos Number of histograms with the same name
name Name of the histograms that should be cleared
Definition at line 249 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateEff (const char *name, Int_tnbinsx, Double_txlow, Double_txup, const char *xtitle = '') [static]
Function to create one 1D Efficiency container in the eff map.
Parameters:
name Name of the Efficiency container that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 233 of file HistClass.hh.
References effs.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateEff (const char *name, TH1D *hist_all, TH1D *hist_pass) [static]
Function to create one 1D Efficiency container in the eff map from two histograms.
Parameters:
name Name of the Efficiency container that should be created
hist_all Histogram of all events
hist_pass Histogram of all passed events
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 245 of file HistClass.hh.
References effs.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateEff (const char *name, Int_tnbinsx, Double_txlow, Double_txup, Int_tnbinsy, Double_tylow, Double_tyup, const char *xtitle = '', const char *ytitle = '') [static]
Function to create one 2D Efficiency container in the eff map.
Parameters:
name Name of the Efficiency container that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
nbinsy Number of bins on the y-axis
ylow Lower edge of the y-axis
yup Upper edge of the y-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 263 of file HistClass.hh.
References effs.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_tn_histos, const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create a number of 1D histograms in the histo map.
Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histograms that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 55 of file HistClass.hh.
References histo.
Referenced by CreateHisto(), and make_hists().
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_tn_histos, const char *name, const char *particle, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create a number of 1D histograms in the histo map for a specific particle.
Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histograms that should be created
particle Name of the particle for which the histograms are created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 74 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create one 1D histograms in the histo map.
Parameters:
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 106 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (const char *name, const char *particle, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create one 1D histogram in the histo map for a specific particle.
Parameters:
name Name of the histograms that should be created
particle Name of the particle for which the histograms are created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 122 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (boost::basic_format< char >name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create one 1D histograms in the histo map with a boost name as input.
Parameters:
name Name of the histogram that should be created (boost::basic_format)
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 137 of file HistClass.hh.
References CreateHisto().
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (const char *name, Int_tnbinsx, Double_txlow, Double_txup, Int_tnbinsy, Double_tylow, Double_tyup, TStringxtitle = '', TStringytitle = '') [static]
Function to create one 2D histograms in the histo map.
Parameters:
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
nbinsy Number of bins on the y-axis
ylow Lower edge of the y-axis
yup Upper edge of the y-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 153 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo2, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_tn_histos, const char *name, Int_tnbinsx, Double_txlow, Double_txup, Int_tnbinsy, Double_tylow, Double_tyup, TStringxtitle = '', TStringytitle = '') [static]
Function to create a number of 2D histograms in the histo map.
Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
nbinsy Number of bins on the y-axis
ylow Lower edge of the y-axis
yup Upper edge of the y-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 174 of file HistClass.hh.
References histo2.
static void HistClass::CreateHisto (Int_tn_histos, const char *name, const char *title, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create histograms in the histo map.
Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histograms that should be created
title Title of the histograms that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 234 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHistoUnchangedName (const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = '') [static]
Function to create a 1D histogram in the histo map without the standard histogram naming convention (h1_...)
Parameters:
name Name of the histograms that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 91 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateNSparse (const char *name, intdimension, int *bins, double *xmin, double *xmax, std::stringaxisTitle[]) [static]
Function to create one NSparse in the nSparse map.
Parameters:
name Name of the NSparse that should be created
dimension Number of dimensions that the NSparse should have
bins Array with the number of bins for each dimension
xmin Array of the lower edge of the axis for each dimension
xmax Array of the upper edge of the axis for each dimension
axisTitle[] Array of the axis title for each dimension
Definition at line 193 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histon, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateProf (const char *name, Int_tnbinsx, Double_txlow, Double_txup, const char *xtitle = '', const char *ytitle = '') [static]
Function to create one 1D Profile container in the eff map.
Parameters:
name Name of the Profile container that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 278 of file HistClass.hh.
References prof.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateTree (const char *name, const char *varlist, intbufsize) [static]
Function to create one NtupleD in the NtupleD map.
Parameters:
name Name of the NSparse that should be created
varlist Colon sepereated list with the name of the branches that should be created
bufsize Buffer size that the NtupleD should have
Definition at line 208 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, datasets::string, and ttupple.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateTree (std::unordered_map< std::string, float > *m, const char *name) [static]
Function to create one Tree in the TTree map.
Parameters:
m Map of the name and variable that should be matched to each branch
name Name of the TTree that should be created
Definition at line 218 of file HistClass.hh.
References B2G-Phys14DR-00002_3_cfg::name, and trees.
static void HistClass::DeleteHisto (Int_tn_histos, const char *name) [static]
Function to delete a histogram from the histo map.
Parameters:
n_histos Number of histogram to be deleted
name Name of the histogram to be deleted
Definition at line 288 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
Referenced by make_hists().
static void HistClass::DeleteHisto (Int_tn_histos, const char *name) [static]
Function to delete a histogram from the histo map.
Parameters:
n_histos Number of histogram to be deleted
name Name of the histogram to be deleted
Definition at line 331 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static void HistClass::Fill (Int_tn_histo, const char *name, doublevalue, doubleweight) [static]
Function to fille events in a histogram in the histo map.
Parameters:
n_histos Number of the histograms to be filled
name Name of the histogram to be filled
value Value that should be filled in the histogram
weight Weight the the event should get
Definition at line 280 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static void HistClass::Fill (Int_tn_histo, const char *name, doublevalue, doubleweight) [static]
Function to fill an event in a 1D histogram of the map. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 334 of file HistClass.hh.
References histo.
Referenced by analyser(), and Fill().
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (Int_tn_histo, std::stringname, doublevalue, doubleweight) [static]
Function to fill an event in a 1D histogram of the map with a string as histo name.
Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled (std string)
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 350 of file HistClass.hh.
References Fill().
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (const char *name, doublevalue, doubleweight) [static]
Function to fill an event in a 1D histogram of the map without histo number. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 363 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (const char *name, doublevaluex, doublevaluey, doubleweight) [static]
Function to fill an event in a 2D histogram of the map.
Parameters:
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
weight Weight of the event that should be filled
Definition at line 422 of file HistClass.hh.
References histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (Int_tn_histo, const char *name, doublevaluex, doublevaluey, doubleweight) [static]
Function to fill an event in a 2D histogram of the map. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
weight Weight of the event that should be filled
Definition at line 442 of file HistClass.hh.
References histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::FillEff (const char *name, doublevaluex, boolpassed) [static]
Function to fill an event in a efficiency container of the map.
Parameters:
name Name of the histogram which should be filled
valuex x-value that should be filled
passed Boolean if the event passed or not
Definition at line 501 of file HistClass.hh.
References effs.
static SUPPRESS_NOT_USED_WARN void HistClass::FillEff (const char *name, doublevaluex, doublevaluey, boolpassed) [static]
Function to fill an event in a 2D efficiency container of the map.
Parameters:
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
passed Boolean if the event passed or not
Definition at line 517 of file HistClass.hh.
References effs.
static SUPPRESS_NOT_USED_WARN void HistClass::FillSparse (const char *name, intn, ...) [static]
Function to fill an event in a nSparse of the nSparse map. This function fills one value with one event in one specific nSparse. The function also checks if the nSparse exists in the map, otherwise it will print an error message.
Parameters:
name Name of the n which should be filled
n
...
Todo
complete the function
Definition at line 461 of file HistClass.hh.
References histon.
static SUPPRESS_NOT_USED_WARN void HistClass::FillStr (const char *name, const char *value, doubleweight) [static]
Function to fill an event in a 1D histogram of the map without histo number. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 387 of file HistClass.hh.
References histo.
Referenced by FillStr().
static SUPPRESS_NOT_USED_WARN void HistClass::FillStr (Int_tn_histo, const char *name, const char *value, doubleweight) [static]
Function to fill an event in a 1D histogram of the map without histo number. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 411 of file HistClass.hh.
References FillStr().
static SUPPRESS_NOT_USED_WARN void HistClass::FillTree (const char *name, double *values) [static]
Function to fill an event in a NTupleD of the map.
Parameters:
name Name of the NTupleD which should be filled
values Array of values that should be filled
Definition at line 482 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, datasets::string, and ttupple.
static SUPPRESS_NOT_USED_WARN void HistClass::FillTree (const char *name) [static]
Function to fill an event in a TTree of the map.
Parameters:
name Name of the TTree which should be filled
Definition at line 491 of file HistClass.hh.
References B2G-Phys14DR-00002_3_cfg::name, and trees.
static SUPPRESS_NOT_USED_WARN void HistClass::NameBins (const char *name, const uintn_bins, TString *d_mydisc) [static]
Function to give one 1D histogram from the map alphanumeric bin labels without number.
Parameters:
name Name of the histogram that should get bin names
n_bins of bins that should be renamed
d_mydisc Array with the names that th bins should get
Definition at line 944 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::NameBins (const char *name, const uintn_bins_x, TString *x_bin_names, const uintn_bins_y, TString *y_bin_names) [static]
Function to give one 2D histogram from the map alphanumeric bin labels without number.
Parameters:
name Name of the histogram that should get bin names
n_bins_x Number of x-bins that should be renamed
x_bin_names Array with the names that the x-bins should get
n_bins_y Number of y-bins that should be renamed
y_bin_names Array with the names that the y-bins should get
Definition at line 959 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo2, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::NameBins (Int_tn_histo, const char *name, const uintn_bins, TString *d_mydisc) [static]
Function to give one 1D histogram from the map alphanumeric bin labels.
Parameters:
n_histo Number of the histogram that should get bin names
name Name of the histogram that should get bin names
n_bins of bins that should be renamed
d_mydisc Array with the names that th bins should get
Definition at line 976 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::Profile (const char *name, doublevaluex, doublevaluey) [static]
Function to fill an event in a 1D profile container of the map.
Parameters:
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
passed Boolean if the event passed or not
Definition at line 533 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, prof, and datasets::string.
static void HistClass::RebinHisto (Int_tn_histos, const char *name, Int_tn_rebin, Double_t *bins) [static]
Function to rebin histograms in the histo map.
Parameters:
n_histos Number of histograms with the same name
name Name of the histograms that should be rebinned
n_rebin Number of bins that the rebinned histogram should have
bins Array of bin edges that the rebinned histogram should have
Definition at line 264 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static void HistClass::RebinHisto (Int_tn_histos, const char *name, Int_tn_rebin, Double_t *bins) [static]
Function to rebin histograms in the histo map.
Parameters:
n_histos Number of histograms with the same name
name Name of the histograms that should be rebinned
n_rebin Number of bins that the rebinned histogram should have
bins Array of bin edges that the rebinned histogram should have
Definition at line 303 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
Referenced by make_hists().
static TH1D* HistClass::ReturnHist (Int_tn_histo, const char *name) [static]
Function to get a histogram from the histo map.
Parameters:
n_histos Number of histogram to be read
name Name of the histogram to be read
Definition at line 320 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN TH1D* HistClass::ReturnHist (const char *name) [static]
Function to get one 1D histogram from the map without number.
Parameters:
name Name of the histogram that should be returned
histo Returned histogram
Definition at line 928 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
static void HistClass::SetToZero (Int_tn_histo, const char *name) [static]
Function to set every negative bin content to zero.
Parameters:
n_histos Number of histogram to be adapted
name Name of the histogram to be adapted
Definition at line 302 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::SetToZero (Int_tn_histo, const char *name) [static]
Function to set all negative bin contents to zero for a 1D histogram.
Parameters:
n_histo Number of the histogram that should be modified
name Name of the histogram that should be modified
Definition at line 912 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
Referenced by writer().
SUPPRESS_NOT_USED_WARN void HistClass::split (const std::string &s, chardelim, std::vector< std::string > *elems)
Function split a string at a delimiter. Example to create a nice folder structure in your output folder //void specialAna::channel_writer(TFile* file, const char* channel) { //file1->cd(); //file1->mkdir(channel); //for ( int i = 0; i < channel_stages[channel]; i++) { //char n_satge = (char)(((int)'0')+i); //file1->mkdir(TString::Format('%s/Stage_%c', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/', channel, n_satge)); //HistClassWriteAll(TString::Format('_%s_', channel),TString::Format('%s:_%c_', channel, n_satge),TString::Format('sys')); //file1->cd(); //file1->mkdir(TString::Format('%s/Stage_%c/sys', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/sys/', channel, n_satge)); //HistClassWriteAll(TString::Format('_%s_', channel),TString::Format('_%c_:sys', n_satge)); //} //file1->cd(); //}
This function splits a given string at a given delimineter, and pushes the results in a given vector.
Parameters:
&s String that should be split
delim Delimiter where the string should be split
&elems Vector in which the substrings should be pushed
Definition at line 624 of file HistClass.hh.
References datasets::string.
Referenced by music_crab::createTag(), music_crab3::createTag(), githookcontroller.GitHookController::doc_remote_root_name(), crabFunctions.CrabTask::finalizeTask(), gridFunctions::getdcachelist(), cesubmit.Job::jid(), cleanProcessNames::main(), prepareCMSDIST::main(), aix3adbSampleFinder::main(), githookcontroller.GitHookController::parse_pre_commit(), githookcontroller.GitHookController::parse_pre_push(), fakeCondor::parseSplit(), remote_example::prepare_teli(), crabFunctions.CrabTask::readLogArch(), githookcontroller.GitHookController::remote_branches(), githookcontroller.GitHookController::remote_root_name(), githookcontroller.GitHookController::remote_url(), split(), WriteAll(), WriteAll2(), and WriteAllEff().
SUPPRESS_NOT_USED_WARN std::vector<std::string> HistClass::split (const std::string &s, chardelim)
Function split a string at a delimiter and return the results. This function splits a given string at a given delimineter, and returns the resulting substrings as a vector.
Parameters:
&s String that should be split
delim Delimiter where the string should be split
elems Vector in which the substrings were pushed
Definition at line 640 of file HistClass.hh.
References split().
static void HistClass::Write (Int_tn_histo, const char *name) [static]
Function to write a histogram from the histo map.
Parameters:
n_histos Number of histogram to be written
name Name of the histogram to be written
Definition at line 291 of file hist_maker.h.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::Write (Int_tn_histo, const char *name) [static]
Function to write one 1D histogram of the map.
Parameters:
n_histo Number of the histogram that should be written
name Name of the histogram that should be written
Definition at line 548 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
Referenced by pdf_calcer_hessian(), pdf_calcer_MC(), WriteAll(), WriteAll2(), WriteAllEff(), WriteAllProf(), WriteAllTrees(), WriteN(), and writer().
static SUPPRESS_NOT_USED_WARN void HistClass::Write (const char *name) [static]
Function to write one 1D histogram of the map without number.
Parameters:
name Name of the histogram that should be written
Definition at line 557 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::Write2 (const char *name) [static]
Function to write one 2D histogram of the map.
Parameters:
name Name of the histogram that should be written
Definition at line 836 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, histo2, and datasets::string.
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char *name = '') [static]
Function to write many 1D histograms of the map. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all histogram names that should be written contain (DEFAULT = '')
Definition at line 569 of file HistClass.hh.
References histo, B2G-Phys14DR-00002_3_cfg::name, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char *name, const char *contains_i) [static]
Function to write many 1D histograms which contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
Definition at line 655 of file HistClass.hh.
References histo, split(), datasets::string, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char *name, const char *contains_i, const char *vetos_i) [static]
Function to write many 1D histograms which (not) contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'. In this version also a list of strings that should not be contained in the histogram name can be given.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
vetos_i String that of names (seperated by ':') that the histogram name should not contain
Definition at line 719 of file HistClass.hh.
References histo, split(), datasets::string, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char *name = '') [static]
Function to write many 2D histograms of the map. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all histogram names that should be written contain (DEFAULT = '')
Definition at line 587 of file HistClass.hh.
References histo2, B2G-Phys14DR-00002_3_cfg::name, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char *name, const char *contains_i) [static]
Function to write many 2D histograms which contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
Definition at line 686 of file HistClass.hh.
References histo2, split(), datasets::string, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char *name, const char *contains_i, const char *vetos_i) [static]
Function to write many 2D histograms which (not) contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'. In this version also a list of strings that should not be contained in the histogram name can be given.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
vetos_i String that of names (seperated by ':') that the histogram name should not contain
Definition at line 760 of file HistClass.hh.
References histo2, split(), datasets::string, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAllEff (const char *name = '') [static]
Function to write many efficiency containers of the map. This function writes all efficiency containers of the map with the default options, otherwise it writes all efficiency containers that contain the given string in there name.
Parameters:
name Optional string that all efficiency containers names that should be written contain (DEFAULT = '')
Definition at line 848 of file HistClass.hh.
References effs, B2G-Phys14DR-00002_3_cfg::name, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAllEff (const char *name, const char *contains_i) [static]
Function to write many efficiency containers which contain specific strings of the map. This function writes all efficiency containers of the map with that contain the given string in there name. The written efficiencies also have to contain a list of strings that are sepe- rated by a ':'.
Parameters:
name String that all efficiency names that should be written contain
contains_i String that of names (seperated by ':') that the efficiency name should contain
Definition at line 867 of file HistClass.hh.
References effs, split(), datasets::string, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAllProf (const char *name = '') [static]
Function to write many profile containers of the map. This function writes all profile containers of the map with the default options, otherwise it writes all profile containers that contain the given string in there name.
Parameters:
name Optional string that all profile containers names that should be written contain (DEFAULT = '')
Definition at line 896 of file HistClass.hh.
References B2G-Phys14DR-00002_3_cfg::name, prof, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAllTrees (const char *name = '') [static]
Function to write many TTrees and TNtupleDs of the maps. This function writes all TTrees and TNtupleDs of the maps with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all TTrees or TNtupleDs names that should be written contain (DEFAULT = '')
Definition at line 797 of file HistClass.hh.
References B2G-Phys14DR-00002_3_cfg::name, trees, ttupple, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteN (const char *name = '') [static]
Function to write many TNsparses of the map. This function writes all nSparses of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all nSparses names that should be written contain (DEFAULT = '')
Definition at line 821 of file HistClass.hh.
References histon, B2G-Phys14DR-00002_3_cfg::name, and Write().
Variable Documentation
std::unordered_map<std::string, TEfficiency * > HistClass::effs [static]
Map of a string and a TEfficiency container.
Definition at line 43 of file HistClass.hh.
Referenced by CleanUp(), CreateEff(), FillEff(), and WriteAllEff().
std::unordered_map<std::string, TH1D * > HistClass::histo [static]
Map of a string and a TH1D histogram, for easy 1D histogram handling.
Definition at line 38 of file HistClass.hh.
Referenced by CleanUp(), CreateHisto(), CreateHistoUnchangedName(), DeleteHisto(), Fill(), FillStr(), NameBins(), RebinHisto(), ReturnHist(), SetToZero(), Write(), and WriteAll().
std::unordered_map<std::string, TH2D * > HistClass::histo2 [static]
Map of a string and a TH2D histogram, for easy 2D histogram handling.
Definition at line 39 of file HistClass.hh.
Referenced by CleanUp(), CreateHisto(), Fill(), NameBins(), Write2(), and WriteAll2().
std::unordered_map<std::string, THnSparseD * > HistClass::histon [static]
Map of a string and a THnSparseD histogram, for easy nSparse handling.
Definition at line 40 of file HistClass.hh.
Referenced by CleanUp(), CreateNSparse(), FillSparse(), and WriteN().
std::unordered_map<std::string, TProfile * > HistClass::prof [static]
Map of a string and a TEfficiency container.
Definition at line 44 of file HistClass.hh.
Referenced by CreateProf(), Profile(), and WriteAllProf().
std::unordered_map<std::string, TTree * > HistClass::trees [static]
Map of a string and a TTree histogram, for easy tree handling.
Definition at line 42 of file HistClass.hh.
Referenced by CleanUp(), CreateTree(), FillTree(), and WriteAllTrees().
std::unordered_map<std::string, TNtupleD * > HistClass::ttupple [static]
Map of a string and a TNtupleD histogram, for easy Ntuple handling.
Definition at line 41 of file HistClass.hh.
Referenced by CleanUp(), CreateTree(), FillTree(), and WriteAllTrees().
Author
Generated automatically by Doxygen for not_found from the source code.