.TH "lheanalyzer.Event" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer.Event \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBaddParticle\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCDCoupling\fP"
.br
.ti -1c
.RI "\fBparticles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file lheanalyzer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lheanalyzer\&.Event\&.__init__ (self, initstr)"

.PP
.nf
Constuctor call with line from lhe file
.fi
.PP
 
.PP
Definition at line 51 of file lheanalyzer\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lheanalyzer\&.Event\&.addParticle (self, particle)"

.PP
.nf
adds a particle to the event
.fi
.PP
 
.PP
Definition at line 59 of file lheanalyzer\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lheanalyzer\&.Event\&.particles"

.PP
Definition at line 58 of file lheanalyzer\&.py\&.
.PP
Referenced by physpic\&.Plot\&.clear(), physpic\&.Plot\&.draw(), and physpic\&.Plot\&.draw3d()\&.
.SS "lheanalyzer\&.Event\&.QCDCoupling"

.PP
Definition at line 55 of file lheanalyzer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
