lheanalyzer
NAME
lheanalyzer -
SYNOPSIS
Classes
class LHEFileFormatError
class Particle
class Event
class Process
class LHEFile
class LHEAnalysis
class LorentzVector
Functions
def invariantMass
def transverseMass
def deltaR
Function Documentation
def lheanalyzer.deltaR (p0, p1)
Definition at line 179 of file lheanalyzer.py.
References raw_input().
def lheanalyzer.invariantMass (p0, particles)
Definition at line 157 of file lheanalyzer.py.
References raw_input().
def lheanalyzer.transverseMass (p0, p1)
Definition at line 169 of file lheanalyzer.py.
References raw_input().
Author
Generated automatically by Doxygen for not_found from the source code.