.TH "md_README" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- tools3a 
This repository contains tools and libraries for the TAPAS framework\&.
.PP
Some rules for people who like to contribute:
.IP "\(bu" 2
Please make sure to push only sufficiently documented code to this repo ! This means at least meaningful dicstring and full doxygen markup as best practice\&. 
.PP

