.TH "parseSampleList.mc_sample" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parseSampleList.mc_sample \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBparse_name\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdataset\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBgenerator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file parseSampleList\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def parseSampleList\&.mc_sample\&.__init__ (self, dataset)"

.PP
Definition at line 14 of file parseSampleList\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def parseSampleList\&.mc_sample\&.parse_name (self, options, generators, showers = \fC[]\fP, blacklist = \fC[]\fP)"

.PP
Definition at line 18 of file parseSampleList\&.py\&.
.PP
References parseSampleList\&.mc_sample\&.generator, parseSampleList\&.mc_sample\&.name, cesubmit\&.Task\&.name, and crabFunctions\&.CrabTask\&.name\&.
.SH "Member Data Documentation"
.PP 
.SS "parseSampleList\&.mc_sample\&.dataset"

.PP
Definition at line 15 of file parseSampleList\&.py\&.
.SS "parseSampleList\&.mc_sample\&.generator"

.PP
Definition at line 17 of file parseSampleList\&.py\&.
.PP
Referenced by parseSampleList\&.mc_sample\&.parse_name()\&.
.SS "parseSampleList\&.mc_sample\&.name"

.PP
Definition at line 16 of file parseSampleList\&.py\&.
.PP
Referenced by parseSampleList\&.mc_sample\&.parse_name()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
