.TH "python/physpic.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/physpic.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBphyspic\&.Arrow3D\fP"
.br
.RI "\fIhelper classes \fP"
.ti -1c
.RI "class \fBphyspic\&.EventFileFormatError\fP"
.br
.ti -1c
.RI "class \fBphyspic\&.Particle\fP"
.br
.ti -1c
.RI "class \fBphyspic\&.EventFile\fP"
.br
.ti -1c
.RI "class \fBphyspic\&.Plot\fP"
.br
.RI "\fIplotter class \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBphyspic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
