.TH "physpic.Arrow3D" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
physpic.Arrow3D \- 
.PP
helper classes  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FancyArrowPatch\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBdraw\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_verts3d\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
helper classes 
.PP
Definition at line 18 of file physpic\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def physpic\&.Arrow3D\&.__init__ (self, xs, ys, zs, args, kwargs)"

.PP
Definition at line 19 of file physpic\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def physpic\&.Arrow3D\&.draw (self, renderer)"

.PP
Definition at line 23 of file physpic\&.py\&.
.PP
References physpic\&.Arrow3D\&._verts3d\&.
.PP
Referenced by rootplotlib\&.Legend\&.Draw()\&.
.SH "Member Data Documentation"
.PP 
.SS "physpic\&.Arrow3D\&._verts3d\fC [private]\fP"

.PP
Definition at line 21 of file physpic\&.py\&.
.PP
Referenced by physpic\&.Arrow3D\&.draw()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
