.TH "prepareCMSDIST" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prepareCMSDIST \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def prepareCMSDIST\&.main ()"

.PP
Definition at line 11 of file prepareCMSDIST\&.py\&.
.PP
References raw_input(), and HistClass\&.split()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
