.TH "remoteAnalysis.MyConfigParser" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remoteAnalysis.MyConfigParser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SafeConfigParser\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBoptionsNoDefault\fP"
.br
.ti -1c
.RI "def \fBoptionxform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Can get options() without defaults

.fi
.PP
 
.PP
Definition at line 398 of file remoteAnalysis\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def remoteAnalysis\&.MyConfigParser\&.optionsNoDefault (self, section)"

.PP
.nf
Return a list of option names for the given section name.
.fi
.PP
 
.PP
Definition at line 401 of file remoteAnalysis\&.py\&.
.SS "def remoteAnalysis\&.MyConfigParser\&.optionxform (self, optionstr)"

.PP
Definition at line 410 of file remoteAnalysis\&.py\&.
.PP
References remoteAnalysis\&.main()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
