remoteProductionMiniAOD
NAME
remoteProductionMiniAOD -
SYNOPSIS
Functions
def makeExe
def main
Variables
tuple log = logging.getLogger( 'remote' )
Function Documentation
def remoteProductionMiniAOD.main ()
Definition at line 50 of file remoteProductionMiniAOD.py.
References checkEnvironment.checkEnvironment(), and makeExe().
def remoteProductionMiniAOD.makeExe (user)
Definition at line 15 of file remoteProductionMiniAOD.py.
Referenced by main().
Variable Documentation
tuple remoteProductionMiniAOD.log = logging.getLogger( 'remote' )
Definition at line 10 of file remoteProductionMiniAOD.py.
Author
Generated automatically by Doxygen for not_found from the source code.