.TH "remoteProductionMiniAOD" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remoteProductionMiniAOD \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmakeExe\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger( 'remote' )"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def remoteProductionMiniAOD\&.main ()"

.PP
Definition at line 50 of file remoteProductionMiniAOD\&.py\&.
.PP
References checkEnvironment\&.checkEnvironment(), and makeExe()\&.
.SS "def remoteProductionMiniAOD\&.makeExe (user)"

.PP
Definition at line 15 of file remoteProductionMiniAOD\&.py\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "tuple remoteProductionMiniAOD\&.log = logging\&.getLogger( 'remote' )"

.PP
Definition at line 10 of file remoteProductionMiniAOD\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
