television
NAME
television -
SYNOPSIS
Classes
class NoDaemonProcess
class NoDaemonPool
class Overview
Functions
def terminate
def addtime
def timerepr
def runParralellTask
def checkTask
def nextUpdate
def resubmitByStatus
def addToList
def clearFinishedJobs
def getRunTimeFromHistory
def statistics
def main
Variables
waitingForExit = False
tuple parser = optparse.OptionParser( description='Monitor for ce tasks', usage='usage: %prog directories')
tuple task = cesubmit.Task.load(directory)
tuple pp = pprint.PrettyPrinter(indent=2)
passphrase = None
Function Documentation
def television.addtime (tfor, tsince, tto)
Add two time intervals
tfor to tto-tsince
Definition at line 43 of file television.py.
def television.addToList (taskList, myList, overview)
add jobs to the kill / resubmit list
Definition at line 109 of file television.py.
Referenced by main().
def television.checkTask (task, resubmitJobs, killJobs)
perform actions on a task
resubmit jobs, get status, get output and get status again
Definition at line 70 of file television.py.
References cesubmit.Task.load().
def television.clearFinishedJobs (taskList)
remove done jobs from the list
Definition at line 125 of file television.py.
Referenced by main().
def television.getRunTimeFromHistory (history)
Definition at line 136 of file television.py.
References timerepr().
Referenced by television.Overview.update().
def television.main (stdscr, options, args, passphrase)
Definition at line 360 of file television.py.
References addToList(), cesubmit.checkAndRenewVomsProxy(), clearFinishedJobs(), lumi.format, cesubmit.Task.load(), nextUpdate(), resubmitByStatus(), statistics(), cesubmit.timeLeftVomsProxy(), and timerepr().
def television.nextUpdate (lastUpdate, updateInterval, nextTaskId)
Definition at line 88 of file television.py.
Referenced by main().
def television.resubmitByStatus (taskList, resubmitList, status, overview)
add jobs with a certain status to the resubmit list
Definition at line 94 of file television.py.
Referenced by main().
def television.runParralellTask (direcory)
Definition at line 67 of file television.py.
def television.statistics (taskList)
Draw statistics
Draws a histogram of the time consumed by the finished jobs
Definition at line 147 of file television.py.
Referenced by main().
def television.terminate (signum, frame)
Definition at line 39 of file television.py.
def television.timerepr (deltat)
Return formatted time interval
Definition at line 55 of file television.py.
References lumi.format.
Referenced by getRunTimeFromHistory(), and main().
Variable Documentation
tuple television.parser = optparse.OptionParser( description='Monitor for ce tasks', usage='usage: %prog directories')
Definition at line 532 of file television.py.
tuple television.passphrase = None
Definition at line 550 of file television.py.
tuple television.pp = pprint.PrettyPrinter(indent=2)
Definition at line 544 of file television.py.
tuple television.task = cesubmit.Task.load(directory)
Definition at line 541 of file television.py.
television.waitingForExit = False
Definition at line 26 of file television.py.
Author
Generated automatically by Doxygen for not_found from the source code.