.TH "television.NoDaemonProcess" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
television.NoDaemonProcess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Process\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_get_daemon\fP"
.br
.ti -1c
.RI "def \fB_set_daemon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file television\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def television\&.NoDaemonProcess\&._get_daemon (self)\fC [private]\fP"

.PP
Definition at line 31 of file television\&.py\&.
.SS "def television\&.NoDaemonProcess\&._set_daemon (self, value)\fC [private]\fP"

.PP
Definition at line 33 of file television\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
