.TH "terminalFunctions.py" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminalFunctions.py \- 
.PP
Functions to be used for terminal output\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions to be used for terminal output\&. 

Functions and classes for terminal output\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
