.TH "testPlot" 3 "Thu Nov 5 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testPlot \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBefile\fP = \fBphyspic\&.EventFile\fP('events_after_cuts\&.txt')"
.br
.ti -1c
.RI "tuple \fBplot\fP = \fBphyspic\&.Plot\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple testPlot\&.efile = \fBphyspic\&.EventFile\fP('events_after_cuts\&.txt')"

.PP
Definition at line 5 of file testPlot\&.py\&.
.SS "tuple testPlot\&.plot = \fBphyspic\&.Plot\fP()"

.PP
Definition at line 14 of file testPlot\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
