watchfrog
NAME
watchfrog -
SYNOPSIS
Classes
class Overview
Functions
def runserver
def main
def runGui
def printFrogArt
def mp_crab_worker
def crab_worker
def getAllCrabFolders
def addInfoHeader
def createDBlink
def timerepr
def formatedUnixTimestamp
def commandline_parsing
Variables
tuple serverLock = threading.Lock()
tuple optionsLock = threading.Lock()
tuple mylogger = logging.getLogger('watchfrog')
Function Documentation
def watchfrog.addInfoHeader (stdscr, options)
Definition at line 484 of file watchfrog.py.
References lumi.format.
def watchfrog.commandline_parsing ()
Definition at line 516 of file watchfrog.py.
References gridFunctions.checkAndRenewVomsProxy(), gridFunctions.checkVomsProxy(), createDBlink(), and main().
Referenced by main().
def watchfrog.crab_worker (job_q, result_q, log_q)
A worker function to be launched in a separate process. Takes jobs from
    job_q -. When the job is done,
    the result is placed into result_q. Runs until job_q is empty.
Definition at line 280 of file watchfrog.py.
def watchfrog.createDBlink ()
Definition at line 490 of file watchfrog.py.
Referenced by commandline_parsing().
def watchfrog.formatedUnixTimestamp (unixTimeStamp)
Definition at line 512 of file watchfrog.py.
Referenced by watchfrog.Overview.update().
def watchfrog.getAllCrabFolders (options)
Definition at line 320 of file watchfrog.py.
def watchfrog.main ()
Definition at line 48 of file watchfrog.py.
References commandline_parsing(), and printFrogArt().
Referenced by commandline_parsing().
def watchfrog.mp_crab_worker (shared_job_q, shared_result_q, shared_log_q, nprocs)
Split the work with jobs in shared_job_q and results in
    shared_result_q into several processes. Launch each process with
    factorizer_worker as the worker function, and wait until all are
    finished.
Definition at line 261 of file watchfrog.py.
Referenced by runserver().
def watchfrog.printFrogArt ()
Definition at line 249 of file watchfrog.py.
Referenced by main().
def watchfrog.runGui (stdscr, options)
Definition at line 54 of file watchfrog.py.
def watchfrog.runserver (options, args)
Definition at line 31 of file watchfrog.py.
References mp_crab_worker().
def watchfrog.timerepr (deltat)
Return formatted time interval
Definition at line 500 of file watchfrog.py.
References lumi.format.
Variable Documentation
tuple watchfrog.mylogger = logging.getLogger('watchfrog')
Definition at line 29 of file watchfrog.py.
tuple watchfrog.optionsLock = threading.Lock()
Definition at line 28 of file watchfrog.py.
tuple watchfrog.serverLock = threading.Lock()
Definition at line 27 of file watchfrog.py.
Author
Generated automatically by Doxygen for not_found from the source code.