wurlitzer
NAME
wurlitzer -
SYNOPSIS
Functions
def getRunTimeFromHistory
def checkTask
def linearStatusgetter
def resubmitByStatus
def resubmitBytime
def main
Variables
tuple parser = optparse.OptionParser( description='Monitor for ce tasks', usage='usage: %prog directories')
Function Documentation
def wurlitzer.checkTask (item)
perform actions on a task
resubmit jobs, get status, get output and get status again
Definition at line 30 of file wurlitzer.py.
def wurlitzer.getRunTimeFromHistory (history)
Definition at line 18 of file wurlitzer.py.
Referenced by resubmitBytime().
def wurlitzer.linearStatusgetter (taskList, resubmitList, killList)
Definition at line 49 of file wurlitzer.py.
Referenced by main().
def wurlitzer.main (options, args)
Definition at line 88 of file wurlitzer.py.
References linearStatusgetter(), cesubmit.Task.load(), resubmitByStatus(), and resubmitBytime().
def wurlitzer.resubmitByStatus (taskList, resubmitList, status, force = False)
add jobs with a certain status to the resubmit list
Definition at line 67 of file wurlitzer.py.
Referenced by main().
def wurlitzer.resubmitBytime (taskList, resubmitList, time)
add jobs with a certain status to the resubmit list
Definition at line 77 of file wurlitzer.py.
References getRunTimeFromHistory().
Referenced by main().
Variable Documentation
tuple wurlitzer.parser = optparse.OptionParser( description='Monitor for ce tasks', usage='usage: %prog directories')
Definition at line 233 of file wurlitzer.py.
Author
Generated automatically by Doxygen for not_found from the source code.