.TH "RATA_PDF Directory Reference" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinput\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhelper\&.py\fP"
.br
.ti -1c
.RI "file \fBhist_maker\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhist_maker\&.h\fP"
.br
.ti -1c
.RI "file \fBpdf_plotter\&.py\fP"
.br
.ti -1c
.RI "file \fBRATA_PDF\&.py\fP"
.br
.ti -1c
.RI "file \fBsignal_mover\&.py\fP"
.br
.in -1c
