.TH "aix3a2music" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3a2music \- 
.PP
Create MUSiC config files from aix3db\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Create MUSiC config files from aix3db\&. 


.PP
\fBAuthor:\fP
.RS 4
Tobias Pook 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
