.TH "aix3a2Finder" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3a2Finder \- 
.PP
Get sample info from aix3adb\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Get sample info from aix3adb\&. 


.PP
\fBAuthor:\fP
.RS 4
Tobias Pook 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
