fakeCondor
NAME
fakeCondor -
SYNOPSIS
Functions
def id_generator
def jdlreplace
def parseSplit
def main
def parseJDL
def worker
Function Documentation
def fakeCondor.id_generator (size = 3, chars = string.ascii_letters + string.digits)
Definition at line 12 of file fakeCondor.py.
Referenced by main().
def fakeCondor.jdlreplace (value, cluster, process)
Definition at line 15 of file fakeCondor.py.
Referenced by worker().
def fakeCondor.main ()
Definition at line 31 of file fakeCondor.py.
References id_generator(), parseJDL(), and parseSplit().
Referenced by worker().
def fakeCondor.parseJDL (filename, clustername)
Definition at line 62 of file fakeCondor.py.
Referenced by main().
def fakeCondor.parseSplit (splitstring, nprocesses)
Definition at line 20 of file fakeCondor.py.
Referenced by main().
def fakeCondor.worker (item)
Definition at line 86 of file fakeCondor.py.
References jdlreplace(), and main().
Author
Generated automatically by Doxygen for tools3a from the source code.