.TH "RATA_PDF/helper.py" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF/helper.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhelper\&.bcolors\fP"
.br
.RI "\fIClass for the different bash text colors\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBhelper\fP"
.br
.RI "\fIhelper for \fBRATA_PDF\fP pdf calculator \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhelper\&.getTerminalSize\fP"
.br
.RI "\fIFunction to get the size of the terminal\&. \fP"
.ti -1c
.RI "def \fBhelper\&.update_progress\fP"
.br
.RI "\fIFunction to create and update a progress bar\&. \fP"
.ti -1c
.RI "def \fBhelper\&.welcome_output\fP"
.br
.RI "\fIWelcome output function\&. \fP"
.ti -1c
.RI "def \fBhelper\&.farewell_output\fP"
.br
.RI "\fIFarewell output function\&. \fP"
.ti -1c
.RI "def \fBhelper\&.Usage\fP"
.br
.RI "\fIUsage function, prints the usage information\&. \fP"
.ti -1c
.RI "def \fBhelper\&.option_parsing\fP"
.br
.RI "\fIFunction to do the options input parsing\&. \fP"
.ti -1c
.RI "def \fBhelper\&.config_parsing\fP"
.br
.RI "\fIFunction to do the config file parsing\&. \fP"
.ti -1c
.RI "def \fBhelper\&.control_output\fP"
.br
.RI "\fIFunction that does a control output\&. \fP"
.ti -1c
.RI "def \fBhelper\&.get_event_number_list\fP"
.br
.RI "\fIFunction to get list of event numbers\&. \fP"
.ti -1c
.RI "def \fBhelper\&.get_event_number\fP"
.br
.RI "\fIFunction to get the number of events in one file\&. \fP"
.ti -1c
.RI "def \fBhelper\&.check_file\fP"
.br
.RI "\fIFunction to check if there is anythin in a file\&. \fP"
.ti -1c
.RI "def \fBhelper\&.final_file_check\fP"
.br
.RI "\fIFunction to check all output files\&. \fP"
.ti -1c
.RI "def \fBhelper\&.make_c_parameters\fP"
.br
.RI "\fIFunction to convert the parameters for the C++ library\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBhelper\&.info\fP = r\&.ProcInfo_t()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
