lumi
NAME
lumi -
SYNOPSIS
Variables
tuple log = logging.getLogger( 'lumi' )
tuple lumi_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/lumi' )
tuple lumi_map_file = os.path.join( lumi_dir, 'lumi-map.txt' )
tuple date = datetime.datetime.today()
tuple parser = optparse.OptionParser( description='Calculate the integrated luminosity of CRAB tasks after applying additional luminosity-masks', usage='usage: %prog [options] CRAB_TASKS...' )
string help = 'Use lumiCalc.py instead of pixelLumiCalc.py. [default: %default]'
string format = '%(levelname)s at %(asctime)s: %(message)s'
tuple units = dict( [ ['/\xce\xbcb', 1e-6 ], [ '/ub', 1e-6 ], [ '/nb', 1e-3 ], [ '/pb', 1 ], [ '/fb', 1e3 ] ] )
tuple c2aix3adb = crab2aix3adb.Crab2aix3adb()
list lumi_map = []
tuple line = line.split( '#' )
tuple lumis = LumiList( os.path.join( options.lumi_dir, file ) )
list jsons_to_read = []
tuple infosForDB_by_json = defaultdict( list )
tuple crabCfgPath = os.path.join( task, 'share/crab.cfg' )
tuple output_file_name = os.path.splitext( os.path.basename( parser.get( 'CMSSW', 'output_file' ) ) )
tuple datasetpath = parser.get( 'CMSSW', 'datasetpath' )
tuple ana_lumis = LumiList( os.path.join( task, 'res/lumiSummary.json' ) )
output_lumis = cert_lumis&ana_lumis
tuple tee = subprocess.Popen( [ 'tee', options.output ], stdin = subprocess.PIPE )
list args = [ options.lumi, 'overview', '-i', json ]
tuple proc = subprocess.Popen( args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT )
tuple output = proc.communicate()
tuple lines = output.splitlines()
tuple unit_line = line.next()
list recorded = unit_line[4]
tuple unit = re.compile('\(([^)]*)\)
Variable Documentation
tuple lumi.ana_lumis = LumiList( os.path.join( task, 'res/lumiSummary.json' ) )
Definition at line 105 of file lumi.py.
list lumi.args = [ options.lumi, 'overview', '-i', json ]
Definition at line 145 of file lumi.py.
tuple lumi.c2aix3adb = crab2aix3adb.Crab2aix3adb()
Definition at line 73 of file lumi.py.
tuple lumi.crabCfgPath = os.path.join( task, 'share/crab.cfg' )
Definition at line 94 of file lumi.py.
tuple lumi.datasetpath = parser.get( 'CMSSW', 'datasetpath' )
Definition at line 103 of file lumi.py.
tuple lumi.date = datetime.datetime.today()
Definition at line 20 of file lumi.py.
string lumi.format = '%(levelname)s at %(asctime)s: %(message)s'
Definition at line 45 of file lumi.py.
Referenced by watchfrog.addInfoHeader(), aix3adbSampleFinder.main(), watchdog.main(), television.main(), githookcontroller.GitHookController.parse_pre_push(), remoteAnalysis.prepare(), aix3adbSampleFinder.SkimAndSampleSummary(), television.timerepr(), watchfrog.timerepr(), television.Overview.update(), and helper.update_progress().
string lumi.help = 'Use lumiCalc.py instead of pixelLumiCalc.py. [default: %default]'
Definition at line 27 of file lumi.py.
tuple lumi.infosForDB_by_json = defaultdict( list )
Definition at line 89 of file lumi.py.
list lumi.jsons_to_read = []
Definition at line 87 of file lumi.py.
tuple lumi.line = line.split( '#' )
Definition at line 81 of file lumi.py.
tuple lumi.lines = output.splitlines()
Definition at line 158 of file lumi.py.
tuple lumi.log = logging.getLogger( 'lumi' )
Definition at line 15 of file lumi.py.
tuple lumi.lumi_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/lumi' )
Definition at line 17 of file lumi.py.
list lumi.lumi_map = []
Definition at line 77 of file lumi.py.
tuple lumi.lumi_map_file = os.path.join( lumi_dir, 'lumi-map.txt' )
Definition at line 18 of file lumi.py.
tuple lumi.lumis = LumiList( os.path.join( options.lumi_dir, file ) )
Definition at line 84 of file lumi.py.
tuple lumi.output = proc.communicate()
Definition at line 152 of file lumi.py.
tuple lumi.output_file_name = os.path.splitext( os.path.basename( parser.get( 'CMSSW', 'output_file' ) ) )
Definition at line 102 of file lumi.py.
lumi.output_lumis = cert_lumis&ana_lumis
Definition at line 113 of file lumi.py.
tuple lumi.parser = optparse.OptionParser( description='Calculate the integrated luminosity of CRAB tasks after applying additional luminosity-masks', usage='usage: %prog [options] CRAB_TASKS...' )
Definition at line 22 of file lumi.py.
tuple lumi.proc = subprocess.Popen( args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT )
Definition at line 150 of file lumi.py.
list lumi.recorded = unit_line[4]
Definition at line 171 of file lumi.py.
tuple lumi.tee = subprocess.Popen( [ 'tee', options.output ], stdin = subprocess.PIPE )
Definition at line 135 of file lumi.py.
tuple lumi.unit = re.compile('\(([^)]*)\)
Definition at line 172 of file lumi.py.
tuple lumi.unit_line = line.next()
Definition at line 170 of file lumi.py.
tuple lumi.units = dict( [ ['/\xce\xbcb', 1e-6 ], [ '/ub', 1e-6 ], [ '/nb', 1e-3 ], [ '/pb', 1 ], [ '/fb', 1e3 ] ] )
Definition at line 49 of file lumi.py.
Author
Generated automatically by Doxygen for tools3a from the source code.