mergeFolders
NAME
mergeFolders -
SYNOPSIS
Functions
def main
def multiextractRoot
def extractRootFiles
def megeRootFiles
def hadd
def cleanUp
Variables
tuple log = logging.getLogger( 'merger' )
Function Documentation
def mergeFolders.cleanUp (options)
Definition at line 168 of file mergeFolders.py.
References main().
Referenced by main().
def mergeFolders.extractRootFiles (options)
Definition at line 65 of file mergeFolders.py.
Referenced by main().
def mergeFolders.hadd (item)
Definition at line 147 of file mergeFolders.py.
def mergeFolders.main ()
Definition at line 19 of file mergeFolders.py.
References cleanUp(), extractRootFiles(), and megeRootFiles().
Referenced by cleanUp().
def mergeFolders.megeRootFiles (options)
Definition at line 95 of file mergeFolders.py.
Referenced by main().
def mergeFolders.multiextractRoot (splited)
Definition at line 49 of file mergeFolders.py.
Variable Documentation
tuple mergeFolders.log = logging.getLogger( 'merger' )
Definition at line 5 of file mergeFolders.py.
Author
Generated automatically by Doxygen for tools3a from the source code.