.TH "scripts/music_crab3.py" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/music_crab3.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmusic_crab3\fP"
.br
.RI "\fIMUSiC wrapper for crab3\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmusic_crab3\&.main\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.createCrabConfig\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.preloadProcess\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.writeCrabConfig\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.getRunRange\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.readSampleFile\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.getExistingProcesses\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.getGlobalTag\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.createDBlink\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.sampleInDB\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.submitSample2db_dump_csv\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.submitSample2db\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.submitSample2dbOld\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.createTag\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.setupLogging\fP"
.br
.ti -1c
.RI "def \fBmusic_crab3\&.commandline_parsing\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBmusic_crab3\&.COMMENT_CHAR\fP = '#'"
.br
.ti -1c
.RI "list \fBmusic_crab3\&.log_choices\fP = [ '\fBERROR\fP', '\fBWARNING\fP', '\fBINFO\fP', '\fBDEBUG\fP' ]"
.br
.ti -1c
.RI "string \fBmusic_crab3\&.date\fP = '%F %H:%M:%S'"
.br
.ti -1c
.RI "tuple \fBmusic_crab3\&.log\fP = logging\&.getLogger( 'music_crab' )"
.br
.ti -1c
.RI "\fBmusic_crab3\&.runOnMC\fP = False"
.br
.ti -1c
.RI "\fBmusic_crab3\&.runOnData\fP = False"
.br
.ti -1c
.RI "\fBmusic_crab3\&.runOnGen\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
