.TH "parseSampleList" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parseSampleList \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.ti -1c
.RI "def \fBgetSamplesByTimestamps\fP"
.br
.ti -1c
.RI "def \fBabbrDatasetName\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger( 'parseSampleList' )"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def parseSampleList\&.abbrDatasetName (datasetName)"

.PP
Definition at line 182 of file parseSampleList\&.py\&.
.PP
References main()\&.
.PP
Referenced by main()\&.
.SS "def parseSampleList\&.getSamplesByTimestamps (options, filename)"

.PP
Definition at line 158 of file parseSampleList\&.py\&.
.PP
Referenced by main()\&.
.SS "def parseSampleList\&.main ()"

.PP
Definition at line 13 of file parseSampleList\&.py\&.
.PP
References abbrDatasetName(), and getSamplesByTimestamps()\&.
.PP
Referenced by abbrDatasetName()\&.
.SH "Variable Documentation"
.PP 
.SS "tuple parseSampleList\&.log = logging\&.getLogger( 'parseSampleList' )"

.PP
Definition at line 11 of file parseSampleList\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
