.TH "RATA_PDF/pdf_plotter.py" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF/pdf_plotter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBpdf_plotter\fP"
.br
.RI "\fISmall script to plot the uncertainty bands calculated with \fBRATA_PDF\fP\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpdf_plotter\&.setTDRStyle\fP"
.br
.ti -1c
.RI "def \fBpdf_plotter\&.set_palette\fP"
.br
.ti -1c
.RI "def \fBpdf_plotter\&.reader\fP"
.br
.RI "\fIFunction to read a histogram from a given file in the memory\&. \fP"
.ti -1c
.RI "def \fBpdf_plotter\&.main\fP"
.br
.RI "\fIMain function\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBpdf_plotter\&.path\fP = '/home/home1/institut_3a/erdweg/Desktop/Software/SirPlotAlot/'"
.br
.ti -1c
.RI "tuple \fBpdf_plotter\&.tdrStyle\fP = r\&.TStyle('tdrStyle','Style for P-TDR')"
.br
.ti -1c
.RI "tuple \fBpdf_plotter\&.tdrStyle2\fP = r\&.TStyle('tdrStyle2','Style for P-TDR')"
.br
.ti -1c
.RI "list \fBpdf_plotter\&.colors\fP = [1, 2, 3, 4, 6, 7, 8, 9, 11]"
.br
.ti -1c
.RI "list \fBpdf_plotter\&.markers\fP = [20, 21, 22, 23, 24, 25, 26, 27, 28]"
.br
.ti -1c
.RI "list \fBpdf_plotter\&.styles\fP = [1, 2, 3, 4, 5, 6, 7, 8, 9]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
