remoteAnalysis
NAME
remoteAnalysis -
SYNOPSIS
Classes
class MyConfigParser
Functions
def main
def readConfig
def prepare
def merge
def makeTask
def adler32
Determines the adler32 check sum of a file.
def ask
Asks a yes/no question at the prompt.
def checkGridpack
Check a grid pack and asks if it should be updated.
def createGridpack
Creates a local grid pack tar.gz file.
def expandFiles
Returns a list of paths from a base directory and a shell conform list of subpath.
def getJobChunks
def prepareFileList
This function prepares a list of pxlio files depending on the chosen options.
def determineJobChunksByFiles
def determineJobChunksByEvents
def getFileList
def getSkipEventsLocal
def prepareConfigs
This function may be used to implement dynamic creation of config files during submission.
def chunks
Yield successive n-sized chunks from l.
def cummulative
Variables
tuple logger = logging.getLogger(__name__)
Function Documentation
def remoteAnalysis.adler32 (path)
Determines the adler32 check sum of a file. path: string
Parameters:
path,: The path to the file.
Returns:
string The adler32 check sum value.
Definition at line 203 of file remoteAnalysis.py.
Referenced by checkGridpack().
def remoteAnalysis.ask (question)
Asks a yes/no question at the prompt. question: string
Parameters:
question,: The question to ask
Returns:
boolean returns True if the user answered y, False if the user answered n.
Definition at line 214 of file remoteAnalysis.py.
References raw_input().
Referenced by checkGridpack().
def remoteAnalysis.checkGridpack (local, remote, gpdir, gpfilestring)
Check a grid pack and asks if it should be updated. Two checks are performed. (1) the timestamp of all files that should enter the grid pack is compared to the local grid pack timestamp. If at least one file is newer than the grid pack, it is suggested to upgrade the grid pack. (2) The adler32 check sum of the remote grid pack is compared to the local grid pack. If they differ or no remote grid pack is found, it is suggested to upload the grid pack. local: string
Parameters:
local,: The local path where the grid tar.gz file is stored. remote: string
remote,: The remote path where the grid tar.gz file is stored. gpdir: string
gpdir,: The local directory containing all the files and subdirectories that are part of the gridpack. gpfilestring: string.
gpfilestring,: A string describing all files that should be contained in the grid pack. Usual shell syntax, such as astersiks is allowed. Directories are included recursively.
Definition at line 238 of file remoteAnalysis.py.
References adler32(), ask(), createGridpack(), and expandFiles().
Referenced by prepare().
def remoteAnalysis.chunks (l, n)
Yield successive n-sized chunks from l. The last chunk may be smaller than n.
l: iterable
Parameters:
l,: The iterable from which chunks are determiend. l: iterable
l,: The iterable from which chunks are determiend.
Returns:
A list of chunks from l.
Definition at line 389 of file remoteAnalysis.py.
Referenced by determineJobChunksByFiles().
def remoteAnalysis.createGridpack (localpath, gpdir, gpfilestring)
Creates a local grid pack tar.gz file. localpath: string
Parameters:
localpath,: The local path where the grid tar.gz file is stored. gpdir: string
gpdir,: The local directory containing all the files and subdirectories that are part of the gridpack. gpfilestring: string.
gpfilestring,: A string describing all files that should be contained in the grid pack. Usual shell syntax, such as astersiks is allowed. Directories are included recursively.
Definition at line 278 of file remoteAnalysis.py.
References expandFiles().
Referenced by checkGridpack().
def remoteAnalysis.cummulative (l)
Yield cummulative sums.
Definition at line 393 of file remoteAnalysis.py.
Referenced by determineJobChunksByEvents().
def remoteAnalysis.determineJobChunksByEvents (files, eventsperjob)
Definition at line 343 of file remoteAnalysis.py.
References cummulative(), getFileList(), and getSkipEventsLocal().
Referenced by getJobChunks().
def remoteAnalysis.determineJobChunksByFiles (files, filesperjob)
Definition at line 339 of file remoteAnalysis.py.
References chunks().
Referenced by getJobChunks().
def remoteAnalysis.expandFiles (gpdir, gpfilestring)
Returns a list of paths from a base directory and a shell conform list of subpath. The function prepends the base directory and resolves wildcards gpdir: string
Parameters:
gpdir,: The local directory containing all the files and subdirectories that are part of the gridpack. gpfilestring: string.
gpfilestring,: A string describing all files that should be contained in the grid pack. Usual shell syntax, such as astersiks is allowed. Directories are included recursively.
Returns:
: A list of all paths corresponding to the input
Definition at line 294 of file remoteAnalysis.py.
Referenced by checkGridpack(), createGridpack(), and makeTask().
def remoteAnalysis.getFileList (files, cummulativeHigh, cummulativeLow, skipEventsGlobal, eventsperjob)
Definition at line 357 of file remoteAnalysis.py.
Referenced by determineJobChunksByEvents().
def remoteAnalysis.getJobChunks (files, options)
Definition at line 300 of file remoteAnalysis.py.
References determineJobChunksByEvents(), and determineJobChunksByFiles().
Referenced by makeTask().
def remoteAnalysis.getSkipEventsLocal (cummulativeLow, skipEventsGlobal)
Definition at line 361 of file remoteAnalysis.py.
Referenced by determineJobChunksByEvents().
def remoteAnalysis.main ()
Definition at line 21 of file remoteAnalysis.py.
References merge(), and prepare().
Referenced by remoteAnalysis.MyConfigParser.optionxform().
def remoteAnalysis.makeTask (options, skim, sample, section, arguments)
Definition at line 170 of file remoteAnalysis.py.
References expandFiles(), getJobChunks(), and prepareFileList().
Referenced by prepare().
def remoteAnalysis.merge (options, args)
Definition at line 158 of file remoteAnalysis.py.
Referenced by main().
def remoteAnalysis.prepare (options, args)
Definition at line 136 of file remoteAnalysis.py.
References checkGridpack(), lumi.format, makeTask(), prepareConfigs(), and readConfig().
Referenced by main().
def remoteAnalysis.prepareConfigs (skimlist, options)
This function may be used to implement dynamic creation of config files during submission. Currently only MUSiC configs are implemented
Parameters:
options A ConfigOptions object holding current script wide options
args A list of additional command line arguments
A list of skims and samples as created by readConfig
Definition at line 376 of file remoteAnalysis.py.
References aix3adb2music.flattenRemoteSkimDict(), aix3adb2music.getConfigDicts(), and aix3adb2music.writeConfigDicts().
Referenced by prepare().
def remoteAnalysis.prepareFileList (skim, sample, options)
This function prepares a list of pxlio files depending on the chosen options.
Parameters:
A aix3adb skim object
Program wide options saved in Option class from optparse
Returns:
A list of dicts as used in the skim.files field
Definition at line 322 of file remoteAnalysis.py.
Referenced by makeTask().
def remoteAnalysis.readConfig (options, args)
Definition at line 56 of file remoteAnalysis.py.
Referenced by aix3adb2music.getSkimAndSampleList(), and prepare().
Variable Documentation
tuple remoteAnalysis.logger = logging.getLogger(__name__)
Definition at line 5 of file remoteAnalysis.py.
Author
Generated automatically by Doxygen for tools3a from the source code.