.TH "scripts/remoteAnalysis.py" 3 "Wed Sep 30 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/remoteAnalysis.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBremoteAnalysis\&.MyConfigParser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBremoteAnalysis\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBremoteAnalysis\&.main\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.readConfig\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.prepare\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.merge\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.makeTask\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.adler32\fP"
.br
.RI "\fIDetermines the adler32 check sum of a file\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.ask\fP"
.br
.RI "\fIAsks a yes/no question at the prompt\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.checkGridpack\fP"
.br
.RI "\fICheck a grid pack and asks if it should be updated\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.createGridpack\fP"
.br
.RI "\fICreates a local grid pack tar\&.gz file\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.expandFiles\fP"
.br
.RI "\fIReturns a list of paths from a base directory and a shell conform list of subpath\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.getJobChunks\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.prepareFileList\fP"
.br
.RI "\fIThis function prepares a list of pxlio files depending on the chosen options\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.determineJobChunksByFiles\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.determineJobChunksByEvents\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.getFileList\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.getSkipEventsLocal\fP"
.br
.ti -1c
.RI "def \fBremoteAnalysis\&.prepareConfigs\fP"
.br
.RI "\fIThis function may be used to implement dynamic creation of config files during submission\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.chunks\fP"
.br
.RI "\fIYield successive n-sized chunks from l\&. \fP"
.ti -1c
.RI "def \fBremoteAnalysis\&.cummulative\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBremoteAnalysis\&.logger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
