watchdog
NAME
watchdog -
SYNOPSIS
Functions
def commandline_parsing
def read_crabconfig
def getdCacheFiles
def readLogArch
def finalizeSample
def addData2db
def addMC2db
def fillCommonSkimFields
def createDBlink
def main
Variables
runOnMC = True
runOnData = False
runOnGen = False
Function Documentation
def watchdog.addData2db (sample, dblink, args, config, finalFiles, totalEvents)
Definition at line 130 of file watchdog.py.
References fillCommonSkimFields().
Referenced by finalizeSample().
def watchdog.addMC2db (sample, dblink, args, config, finalFiles, totalEvents)
Definition at line 162 of file watchdog.py.
References fillCommonSkimFields().
Referenced by finalizeSample().
def watchdog.commandline_parsing ()
Definition at line 21 of file watchdog.py.
Referenced by main().
def watchdog.createDBlink ()
Definition at line 236 of file watchdog.py.
Referenced by main().
def watchdog.fillCommonSkimFields (dbSample, dbSkim, config, finalFiles, totalEvents)
Definition at line 214 of file watchdog.py.
Referenced by addData2db(), and addMC2db().
def watchdog.finalizeSample (sample, dblink, args)
Definition at line 69 of file watchdog.py.
References addData2db(), addMC2db(), read_crabconfig(), and readLogArch().
Referenced by main().
def watchdog.getdCacheFiles (sample)
Definition at line 47 of file watchdog.py.
def watchdog.main ()
Definition at line 246 of file watchdog.py.
References commandline_parsing(), createDBlink(), finalizeSample(), and lumi.format.
def watchdog.read_crabconfig (sample)
Definition at line 39 of file watchdog.py.
Referenced by finalizeSample().
def watchdog.readLogArch (logArchName)
Definition at line 50 of file watchdog.py.
Referenced by finalizeSample().
Variable Documentation
watchdog.runOnData = False
Definition at line 18 of file watchdog.py.
watchdog.runOnGen = False
Definition at line 19 of file watchdog.py.
watchdog.runOnMC = True
Definition at line 17 of file watchdog.py.
Author
Generated automatically by Doxygen for tools3a from the source code.