.TH "lib.object_plotting" 3 "Tue Feb 24 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.object_plotting \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBplot_upper_cut\fP"
.br
.ti -1c
.RI "def \fBplot_lower_cut\fP"
.br
.ti -1c
.RI "def \fBplot_both_cuts\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.object_plotting\&.plot_both_cuts (axis1, value1, value2, include = \fCTrue\fP, cut_arrow_position = \fC0\&.5\fP)"

.PP
Definition at line 39 of file object_plotting\&.py\&.
.PP
References lib\&.object_plotting\&.plot_lower_cut(), and lib\&.object_plotting\&.plot_upper_cut()\&.
.SS "def lib\&.object_plotting\&.plot_lower_cut (axis1, value, cut_arrow_position = \fC0\&.5\fP)"

.PP
Definition at line 23 of file object_plotting\&.py\&.
.PP
Referenced by lib\&.object_plotting\&.plot_both_cuts()\&.
.SS "def lib\&.object_plotting\&.plot_upper_cut (axis1, value, cut_arrow_position = \fC0\&.5\fP)"

.PP
Definition at line 8 of file object_plotting\&.py\&.
.PP
Referenced by lib\&.object_plotting\&.plot_both_cuts()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
