.TH "lib/object_plotting.py" 3 "Tue Feb 24 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/object_plotting.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.object_plotting\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlib\&.object_plotting\&.plot_upper_cut\fP"
.br
.ti -1c
.RI "def \fBlib\&.object_plotting\&.plot_lower_cut\fP"
.br
.ti -1c
.RI "def \fBlib\&.object_plotting\&.plot_both_cuts\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
