testplot
NAME
testplot -
SYNOPSIS
Functions
def main
def readFiles
def getHists
Variables
string baseDir = '/home/lo/rwth/user/out/output2014_10_8_19_12/merged/'
Function Documentation
def testplot.getHists (file, hist, histname = '')
Definition at line 75 of file testplot.py.
References main().
Referenced by main().
def testplot.main ()
Definition at line 13 of file testplot.py.
References getHists(), and readFiles().
Referenced by getHists().
def testplot.readFiles (flist)
Definition at line 61 of file testplot.py.
Referenced by main().
Variable Documentation
string testplot.baseDir = '/home/lo/rwth/user/out/output2014_10_8_19_12/merged/'
Definition at line 8 of file testplot.py.
Author
Generated automatically by Doxygen for PlotLib from the source code.