.TH "testplot" 3 "Tue Feb 24 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testplot \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.ti -1c
.RI "def \fBreadFiles\fP"
.br
.ti -1c
.RI "def \fBgetHists\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBbaseDir\fP = '/home/lo/rwth/user/out/output2014_10_8_19_12/merged/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def testplot\&.getHists (file, hist, histname = \fC''\fP)"

.PP
Definition at line 75 of file testplot\&.py\&.
.PP
References main()\&.
.PP
Referenced by main()\&.
.SS "def testplot\&.main ()"

.PP
Definition at line 13 of file testplot\&.py\&.
.PP
References getHists(), and readFiles()\&.
.PP
Referenced by getHists()\&.
.SS "def testplot\&.readFiles (flist)"

.PP
Definition at line 61 of file testplot\&.py\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "string testplot\&.baseDir = '/home/lo/rwth/user/out/output2014_10_8_19_12/merged/'"

.PP
Definition at line 8 of file testplot\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
