.TH "lib.DukePlotALot" 3 "Tue Feb 24 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.DukePlotALot \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplotter\fP"
.br
.RI "\fIClass to collect matplotlib functions\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
