lib.plotlib
NAME
lib.plotlib -
SYNOPSIS
Classes
class NoDictMessagesFilter
class LayoutMessagesFilter
class HistStorageContainer
class HistStorage
Class to handle histograms functions.
Functions
def xfrange
helper methods
def getColorList
def getDictValue
def scale_xaxis
def duke_errorbar
def _duke__errorbar
def getRGBTColor
def makeTeXTable
Variables
list log_plotlib = log['plotlib']
tuple rnd = rounding()
Function Documentation
def lib.plotlib._duke__errorbar (h, xerr, yerr, axes = None, emptybins = True, ignore_binns = None, zorder = None, kwargs) [private]
Definition at line 187 of file plotlib.py.
Referenced by lib.plotlib.duke_errorbar().
def lib.plotlib.duke_errorbar (hists, xerr = True, yerr = True, xpadding = 0, ypadding = .1, xerror_in_padding = True, yerror_in_padding = True, emptybins = True, snap = True, axes = None, ignore_binns = None, kwargs)
Definition at line 89 of file plotlib.py.
References lib.plotlib._duke__errorbar().
Referenced by lib.plotlib.scale_xaxis().
def lib.plotlib.getColorList (ncolors)
Definition at line 41 of file plotlib.py.
References lib.plotlib.xfrange().
def lib.plotlib.getDictValue (hist, parmDict)
Definition at line 52 of file plotlib.py.
Referenced by DukePlotALot_tester.Creat_standard_plot(), DukePlotALot_tester_realPlotRoot.main(), and DukePlotALot_tester_realPlot.main().
def lib.plotlib.getRGBTColor (color)
Definition at line 228 of file plotlib.py.
Referenced by DukePlotALot_tester_realPlotRoot.main().
def lib.plotlib.makeTeXTable (dir_name, hist, histContainer)
Definition at line 242 of file plotlib.py.
def lib.plotlib.scale_xaxis (hist, factor)
Definition at line 64 of file plotlib.py.
References lib.plotlib.duke_errorbar().
def lib.plotlib.xfrange (start, stop, step)
helper methods some times one needs float lists
Definition at line 35 of file plotlib.py.
Referenced by lib.plotlib.getColorList().
Variable Documentation
list lib.plotlib.log_plotlib = log['plotlib']
Definition at line 28 of file plotlib.py.
tuple lib.plotlib.rnd = rounding()
Definition at line 30 of file plotlib.py.
Author
Generated automatically by Doxygen for not_found from the source code.