.TH "lib.configobj.NestingError" 3 "Mon Nov 23 2015" "not_found" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.NestingError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlib\&.configobj\&.ConfigObjError\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBline\fP"
.br
.ti -1c
.RI "\fBline_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This error indicates a level of nesting that doesn't match.

.fi
.PP
 
.PP
Definition at line 232 of file configobj\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.configobj\&.ConfigObjError\&.line\fC [inherited]\fP"

.PP
Definition at line 227 of file configobj\&.py\&.
.SS "lib\&.configobj\&.ConfigObjError\&.line_number\fC [inherited]\fP"

.PP
Definition at line 228 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for not_found from the source code\&.
