.TH "lib/configobj.py" 3 "Wed Mar 18 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/configobj.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlib\&.configobj\&.UnknownType\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.Builder\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ConfigObjError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.NestingError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ParseError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ReloadError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.DuplicateError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ConfigspecError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.InterpolationError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.InterpolationLoopError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.RepeatSectionError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.MissingInterpolationOption\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.UnreprError\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.InterpolationEngine\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ConfigParserInterpolation\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.TemplateInterpolation\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.Section\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.ConfigObj\fP"
.br
.ti -1c
.RI "class \fBlib\&.configobj\&.SimpleVal\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.configobj\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlib\&.configobj\&.match_utf8\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.any\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.getObj\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.unrepr\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.__newobj__\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.flatten_errors\fP"
.br
.ti -1c
.RI "def \fBlib\&.configobj\&.get_extra_values\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlib\&.configobj\&.compiler\fP = None"
.br
.ti -1c
.RI "dictionary \fBlib\&.configobj\&.BOMS\fP"
.br
.ti -1c
.RI "dictionary \fBlib\&.configobj\&.BOM_LIST\fP"
.br
.ti -1c
.RI "dictionary \fBlib\&.configobj\&.BOM_SET\fP"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.squot\fP = ''%s''"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.dquot\fP = ''%s''"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.noquot\fP = '%s'"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.wspace_plus\fP = ' \\r\\n\\v\\t\\'''"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.tsquot\fP = ''''%s''''"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.tdquot\fP = ''''%s''''"
.br
.ti -1c
.RI "tuple \fBlib\&.configobj\&.MISSING\fP = object()"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.__version__\fP = '4\&.7\&.2'"
.br
.ti -1c
.RI "tuple \fBlib\&.configobj\&.__all__\fP"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.DEFAULT_INTERPOLATION\fP = 'configparser'"
.br
.ti -1c
.RI "string \fBlib\&.configobj\&.DEFAULT_INDENT_TYPE\fP = ' '"
.br
.ti -1c
.RI "int \fBlib\&.configobj\&.MAX_INTERPOL_DEPTH\fP = 10"
.br
.ti -1c
.RI "dictionary \fBlib\&.configobj\&.OPTION_DEFAULTS\fP"
.br
.ti -1c
.RI "tuple \fBlib\&.configobj\&._builder\fP = Builder()"
.br
.ti -1c
.RI "dictionary \fBlib\&.configobj\&.interpolation_engines\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
