DukePlotALot_tester
NAME
DukePlotALot_tester -
SYNOPSIS
Functions
def main
def Creat_standard_plot
def create_xs_file
def create_test_histos
Variables
tuple root_directory = os.getcwd()
string xs_file_name = 'xs_test.cfg'
int lumi = 1
Function Documentation
def DukePlotALot_tester.Creat_standard_plot ()
Definition at line 39 of file DukePlotALot_tester.py.
References create_test_histos(), create_xs_file(), and lib.plotlib.getDictValue().
Referenced by main().
def DukePlotALot_tester.create_test_histos ()
Definition at line 179 of file DukePlotALot_tester.py.
References main().
Referenced by Creat_standard_plot().
def DukePlotALot_tester.create_xs_file ()
Definition at line 160 of file DukePlotALot_tester.py.
Referenced by Creat_standard_plot().
def DukePlotALot_tester.main ()
Definition at line 27 of file DukePlotALot_tester.py.
References Creat_standard_plot().
Referenced by create_test_histos().
Variable Documentation
int DukePlotALot_tester.lumi = 1
Definition at line 24 of file DukePlotALot_tester.py.
tuple DukePlotALot_tester.root_directory = os.getcwd()
Definition at line 22 of file DukePlotALot_tester.py.
string DukePlotALot_tester.xs_file_name = 'xs_test.cfg'
Definition at line 23 of file DukePlotALot_tester.py.
Author
Generated automatically by Doxygen for PlotLib from the source code.