.TH "DukePlotALot_tester" 3 "Wed Feb 11 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DukePlotALot_tester \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.ti -1c
.RI "def \fBcreate_test_histos\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def DukePlotALot_tester\&.create_test_histos ()"

.PP
Definition at line 43 of file DukePlotALot_tester\&.py\&.
.PP
References main()\&.
.PP
Referenced by main()\&.
.SS "def DukePlotALot_tester\&.main ()"

.PP
Definition at line 6 of file DukePlotALot_tester\&.py\&.
.PP
References create_test_histos()\&.
.PP
Referenced by create_test_histos()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
