.TH "lib/DukePlotALot.py" 3 "Tue Aug 4 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DukePlotALot.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlib\&.DukePlotALot\&.plotter\fP"
.br
.RI "\fIClass to collect matplotlib functions\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.DukePlotALot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
