.TH "DukePlotALot_tester_realPlotRoot.py" 3 "Wed Feb 11 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DukePlotALot_tester_realPlotRoot.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBDukePlotALot_tester_realPlotRoot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDukePlotALot_tester_realPlotRoot\&.main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
