.TH "DukePlotALot_tester.py" 3 "Thu Jul 23 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DukePlotALot_tester.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBDukePlotALot_tester\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDukePlotALot_tester\&.main\fP"
.br
.ti -1c
.RI "def \fBDukePlotALot_tester\&.Creat_standard_plot\fP"
.br
.ti -1c
.RI "def \fBDukePlotALot_tester\&.create_xs_file\fP"
.br
.ti -1c
.RI "def \fBDukePlotALot_tester\&.create_test_histos\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBDukePlotALot_tester\&.root_directory\fP = os\&.getcwd()"
.br
.ti -1c
.RI "string \fBDukePlotALot_tester\&.xs_file_name\fP = 'xs_test\&.cfg'"
.br
.ti -1c
.RI "int \fBDukePlotALot_tester\&.lumi\fP = 1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
