.TH "DukePlotALot_tester_realPlotRoot" 3 "Mon Aug 3 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DukePlotALot_tester_realPlotRoot \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def DukePlotALot_tester_realPlotRoot\&.main ()"

.PP
Definition at line 14 of file DukePlotALot_tester_realPlotRoot\&.py\&.
.PP
References lib\&.plotlib\&.getDictValue(), and lib\&.plotlib\&.getRGBTColor()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
