.TH "lib" 3 "Mon Nov 23 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBconfigobj\fP"
.br
.ti -1c
.RI "\fBDukePlotALot\fP"
.br
.ti -1c
.RI "\fBDukePlotALot2D\fP"
.br
.ti -1c
.RI "\fBobject_plotting\fP"
.br
.ti -1c
.RI "\fBordered\fP"
.br
.ti -1c
.RI "\fBplotlib\fP"
.br
.ti -1c
.RI "\fBrootplotlib\fP"
.br
.ti -1c
.RI "\fBrounding\fP"
.br
.ti -1c
.RI "\fBstyle_class\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
