.TH "lib.configobj.ConfigspecError" 3 "Thu Jul 23 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.ConfigspecError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlib\&.configobj\&.ConfigObjError\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBline\fP"
.br
.ti -1c
.RI "\fBline_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An error occured whilst parsing a configspec.

.fi
.PP
 
.PP
Definition at line 261 of file configobj\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.configobj\&.ConfigObjError\&.line\fC [inherited]\fP"

.PP
Definition at line 227 of file configobj\&.py\&.
.SS "lib\&.configobj\&.ConfigObjError\&.line_number\fC [inherited]\fP"

.PP
Definition at line 228 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
