.TH "lib.DukePlotALot2D.FixedOrderFormatter" 3 "Mon Sep 14 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.DukePlotALot2D.FixedOrderFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScalarFormatter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBorderOfMagnitude\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_set_orderOfMagnitude\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_order_of_mag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Formats axis ticks using scientific notation with a constant order of 
magnitude
.fi
.PP
 
.PP
Definition at line 290 of file DukePlotALot2D\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lib\&.DukePlotALot2D\&.FixedOrderFormatter\&.__init__ (self, order_of_mag = \fC0\fP, useOffset = \fCTrue\fP, useMathText = \fCFalse\fP)"

.PP
Definition at line 293 of file DukePlotALot2D\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lib\&.DukePlotALot2D\&.FixedOrderFormatter\&._set_orderOfMagnitude (self, range)\fC [private]\fP"

.PP
.nf
Over-riding this to avoid having orderOfMagnitude reset elsewhere
.fi
.PP
 
.PP
Definition at line 297 of file DukePlotALot2D\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.DukePlotALot2D\&.FixedOrderFormatter\&._order_of_mag\fC [private]\fP"

.PP
Definition at line 294 of file DukePlotALot2D\&.py\&.
.SS "lib\&.DukePlotALot2D\&.FixedOrderFormatter\&.orderOfMagnitude"

.PP
Definition at line 299 of file DukePlotALot2D\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
