lib.DukePlotALot2D
NAME
lib.DukePlotALot2D -
SYNOPSIS
Classes
class plotter2D
class FixedOrderFormatter
Functions
def grid
def contourplot
def main
Function Documentation
def lib.DukePlotALot2D.contourplot (xlist, ylist, zlist, levels = [], labels = [], overlay = True, resolution = 100, interactive = True, showPoints = True, logz = False, filename = '', contoursAlpha = 0.5, contourLineWidth = 4, CMSLabel = True, CMSLabelCoords = [5, xlabel = 'x', ylabel = 'y', zlabel = 'z', xyrange = [0, LegendLocation = 'upper right', LegendTitle = 'contourplot', LegendColumns = 1)
Definition at line 292 of file DukePlotALot2D.py.
References lib.DukePlotALot2D.grid().
Referenced by lib.DukePlotALot2D.main().
def lib.DukePlotALot2D.grid (x, y, z, resX = 100, resY = 100)
Definition at line 272 of file DukePlotALot2D.py.
Referenced by lib.DukePlotALot2D.contourplot().
def lib.DukePlotALot2D.main ()
Definition at line 339 of file DukePlotALot2D.py.
References lib.DukePlotALot2D.contourplot().
Author
Generated automatically by Doxygen for PlotLib from the source code.