.TH "lib.rootplotlib.CmsDecoration" 3 "Wed Jun 17 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.rootplotlib.CmsDecoration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBDraw\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrelPosX\fP"
.br
.ti -1c
.RI "\fBrelPosY\fP"
.br
.ti -1c
.RI "\fBrelExtraDY\fP"
.br
.ti -1c
.RI "\fBlumiText\fP"
.br
.ti -1c
.RI "\fBlumiTextOffset\fP"
.br
.ti -1c
.RI "\fBextraTextOffset\fP"
.br
.ti -1c
.RI "\fBextraText\fP"
.br
.ti -1c
.RI "\fBadditionalText\fP"
.br
.ti -1c
.RI "\fBpad\fP"
.br
.ti -1c
.RI "\fBalign_\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_style\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file rootplotlib\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lib\&.rootplotlib\&.CmsDecoration\&.__init__ (self, sc_obj = \fCsc\&.style_container()\fP, extraText = \fCNone\fP, additionalText = \fCNone\fP, lumiText = \fC'19\&.7 fb^{-1} (8 TeV)'\fP, position = \fCNone\fP, vspace = \fC0\fP, hspace = \fC0\fP, referenceHeight = \fCNone\fP, pad = \fCNone\fP)"

.PP
Definition at line 21 of file rootplotlib\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lib\&.rootplotlib\&.CmsDecoration\&.Draw (self)"

.PP
Definition at line 62 of file rootplotlib\&.py\&.
.PP
References lib\&.rootplotlib\&.CmsDecoration\&.additionalText, lib\&.rootplotlib\&.CmsDecoration\&.align_, lib\&.rootplotlib\&.CmsDecoration\&.extraText, lib\&.rootplotlib\&.CmsDecoration\&.lumiText, and lib\&.rootplotlib\&.CmsDecoration\&.lumiTextOffset\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.rootplotlib\&.CmsDecoration\&._style\fC [private]\fP"

.PP
Definition at line 22 of file rootplotlib\&.py\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.additionalText"

.PP
Definition at line 37 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.CmsDecoration\&.Draw()\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.align_"

.PP
Definition at line 53 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.CmsDecoration\&.Draw()\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.extraText"

.PP
Definition at line 33 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.CmsDecoration\&.Draw()\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.extraTextOffset"

.PP
Definition at line 30 of file rootplotlib\&.py\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.lumiText"

.PP
Definition at line 28 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.CmsDecoration\&.Draw()\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.lumiTextOffset"

.PP
Definition at line 29 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.CmsDecoration\&.Draw()\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.pad"

.PP
Definition at line 43 of file rootplotlib\&.py\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.relExtraDY"

.PP
Definition at line 25 of file rootplotlib\&.py\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.relPosX"

.PP
Definition at line 23 of file rootplotlib\&.py\&.
.SS "lib\&.rootplotlib\&.CmsDecoration\&.relPosY"

.PP
Definition at line 24 of file rootplotlib\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
