.TH "lib.configobj.UnknownType" 3 "Wed Mar 18 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.UnknownType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Definition at line 151 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
