.TH "lib.configobj.MissingInterpolationOption" 3 "Thu Apr 30 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.MissingInterpolationOption \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlib\&.configobj\&.InterpolationError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBline\fP"
.br
.ti -1c
.RI "\fBline_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A value specified for interpolation was missing.
.fi
.PP
 
.PP
Definition at line 287 of file configobj\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lib\&.configobj\&.MissingInterpolationOption\&.__init__ (self, option)"

.PP
Definition at line 289 of file configobj\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.configobj\&.ConfigObjError\&.line\fC [inherited]\fP"

.PP
Definition at line 227 of file configobj\&.py\&.
.SS "lib\&.configobj\&.ConfigObjError\&.line_number\fC [inherited]\fP"

.PP
Definition at line 228 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
