.TH "lib.rootplotlib" 3 "Tue Mar 31 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.rootplotlib \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmsDecoration\fP"
.br
.ti -1c
.RI "class \fBLegend\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBLatex\fP"
.br
.ti -1c
.RI "def \fBinit\fP"
.br
.ti -1c
.RI "def \fBtdrStyle\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.rootplotlib\&.init ()"

.PP
Definition at line 236 of file rootplotlib\&.py\&.
.PP
References lib\&.rootplotlib\&.tdrStyle()\&.
.SS "def lib\&.rootplotlib\&.Latex (pad = \fCNone\fP)"

.PP
Definition at line 5 of file rootplotlib\&.py\&.
.SS "def lib\&.rootplotlib\&.tdrStyle ()"

.PP
Definition at line 246 of file rootplotlib\&.py\&.
.PP
Referenced by lib\&.rootplotlib\&.init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
