lib.configobj.InterpolationEngine
NAME
lib.configobj.InterpolationEngine -
SYNOPSIS
Inherits object.
Inherited by lib.configobj.ConfigParserInterpolation, and lib.configobj.TemplateInterpolation.
Public Member Functions
def __init__
def interpolate
Public Attributes
section
Private Member Functions
def _fetch
def _parse_match
Static Private Attributes
tuple _KEYCRE = re.compile(r'%\(([^)]*)\)s')
string _cookie = '%'
Detailed Description
A helper class to help perform string interpolation.
This class is an abstract base class; its descendants perform
the actual work.
Definition at line 299 of file configobj.py.
Constructor & Destructor Documentation
def lib.configobj.InterpolationEngine.__init__ (self, section)
Definition at line 311 of file configobj.py.
Member Function Documentation
def lib.configobj.InterpolationEngine._fetch (self, key) [private]
Helper function to fetch values from owning section.
Returns a 2-tuple: the value, and the section where it was found.
Definition at line 369 of file configobj.py.
References lib.configobj.InterpolationEngine.section.
Referenced by lib.configobj.ConfigParserInterpolation._parse_match(), and lib.configobj.TemplateInterpolation._parse_match().
def lib.configobj.InterpolationEngine._parse_match (self, match) [private]
Implementation-dependent helper function.
Will be passed a match object corresponding to the interpolation
key we just found (e.g., "%(foo)s" or "$foo"). Should look up that
key in the appropriate config file section (using the ``_fetch()``
helper function) and return a 3-tuple: (key, value, section)
``key`` is the name of the key we're looking for
``value`` is the value found for that key
``section`` is a reference to the section where it was found
``key`` and ``section`` should be None if no further
interpolation should be performed on the resulting value
(e.g., if we interpolated "$$" and returned "$").
Definition at line 403 of file configobj.py.
Referenced by lib.configobj.InterpolationEngine.interpolate().
def lib.configobj.InterpolationEngine.interpolate (self, key, value)
Definition at line 316 of file configobj.py.
References lib.configobj.InterpolationEngine._cookie, lib.configobj.InterpolationEngine._parse_match(), and lib.configobj.InterpolationEngine.section.
Member Data Documentation
string lib.configobj.InterpolationEngine._cookie = '%' [static], [private]
Definition at line 309 of file configobj.py.
Referenced by lib.configobj.InterpolationEngine.interpolate().
tuple lib.configobj.InterpolationEngine._KEYCRE = re.compile(r'%\(([^)]*)\)s') [static], [private]
Definition at line 308 of file configobj.py.
lib.configobj.InterpolationEngine.section
Definition at line 313 of file configobj.py.
Referenced by lib.configobj.InterpolationEngine._fetch(), and lib.configobj.InterpolationEngine.interpolate().
Author
Generated automatically by Doxygen for PlotLib from the source code.