lib.configobj
NAME
lib.configobj -
SYNOPSIS
Classes
class UnknownType
class Builder
class ConfigObjError
class NestingError
class ParseError
class ReloadError
class DuplicateError
class ConfigspecError
class InterpolationError
class InterpolationLoopError
class RepeatSectionError
class MissingInterpolationOption
class UnreprError
class InterpolationEngine
class ConfigParserInterpolation
class TemplateInterpolation
class Section
class ConfigObj
class SimpleVal
Functions
def match_utf8
def any
def getObj
def unrepr
def __newobj__
def flatten_errors
def get_extra_values
Variables
compiler = None
dictionary BOMS
dictionary BOM_LIST
dictionary BOM_SET
string squot = ''%s''
string dquot = ''%s''
string noquot = '%s'
string wspace_plus = ' \r\n\v\t\'''
string tsquot = ''''%s''''
string tdquot = ''''%s''''
tuple MISSING = object()
string __version__ = '4.7.2'
tuple __all__
string DEFAULT_INTERPOLATION = 'configparser'
string DEFAULT_INDENT_TYPE = ' '
int MAX_INTERPOL_DEPTH = 10
dictionary OPTION_DEFAULTS
tuple _builder = Builder()
dictionary interpolation_engines
Function Documentation
def lib.configobj.__newobj__ (cls, args)
Definition at line 467 of file configobj.py.
def lib.configobj.any (iterable)
Definition at line 91 of file configobj.py.
Referenced by githookcontroller.GitHookController.update_doxygen().
def lib.configobj.flatten_errors (cfg, res, levels = None, results = None)
An example function that will turn a nested dictionary of results
(as returned by ``ConfigObj.validate``) into a flat list.
``cfg`` is the ConfigObj instance being checked, ``res`` is the results
dictionary returned by ``validate``.
(This is a recursive function, so you shouldn't use the ``levels`` or
``results`` arguments - they are used by the function.)
Returns a list of keys that failed. Each member of the list is a tuple::
    ([list of sections...], key, result)
If ``validate`` was called with ``preserve_errors=False`` (the default)
then ``result`` will always be ``False``.
*list of sections* is a flattened list of sections that the key was found
in.
If the section was missing (or a section was expected and a scalar provided
- or vice-versa) then key will be ``None``.
If the value (or section) was missing then ``result`` will be ``False``.
If ``validate`` was called with ``preserve_errors=True`` and a value
was present, but failed the check, then ``result`` will be the exception
object returned. You can use this as a string that describes the failure.
For example *The value "3" is of the wrong type*.
Definition at line 2382 of file configobj.py.
def lib.configobj.get_extra_values (conf, _prepend = ())
Find all the values and sections not in the configspec from a validated
ConfigObj.
``get_extra_values`` returns a list of tuples where each tuple represents
either an extra section, or an extra value.
The tuples contain two values, a tuple representing the section the value
is in and the name of the extra values. For extra values in the top level
section the first member will be an empty tuple. For values in the 'foo'
section the first member will be ``('foo',)``. For members in the 'bar'
subsection of the 'foo' section the first member will be ``('foo', 'bar')``.
NOTE: If you call ``get_extra_values`` on a ConfigObj instance that hasn't
been validated it will return an empty list.
Definition at line 2442 of file configobj.py.
def lib.configobj.getObj (s)
Definition at line 142 of file configobj.py.
Referenced by lib.configobj.unrepr().
def lib.configobj.match_utf8 (encoding)
Definition at line 71 of file configobj.py.
def lib.configobj.unrepr (s)
Definition at line 214 of file configobj.py.
References lib.configobj.getObj().
Variable Documentation
tuple lib.configobj.__all__
Initial value:
= (
    '__version__',
    'DEFAULT_INDENT_TYPE',
    'DEFAULT_INTERPOLATION',
    'ConfigObjError',
    'NestingError',
    'ParseError',
    'DuplicateError',
    'ConfigspecError',
    'ConfigObj',
    'SimpleVal',
    'InterpolationError',
    'InterpolationLoopError',
    'MissingInterpolationOption',
    'RepeatSectionError',
    'ReloadError',
    'UnreprError',
    'UnknownType',
    'flatten_errors',
    'get_extra_values'
)
Definition at line 98 of file configobj.py.
string lib.configobj.__version__ = '4.7.2'
Definition at line 86 of file configobj.py.
tuple lib.configobj._builder = Builder()
Definition at line 211 of file configobj.py.
dictionary lib.configobj.BOM_LIST
Initial value:
= {
    'utf_16': 'utf_16',
    'u16': 'utf_16',
    'utf16': 'utf_16',
    'utf-16': 'utf_16',
    'utf16_be': 'utf16_be',
    'utf_16_be': 'utf16_be',
    'utf-16be': 'utf16_be',
    'utf16_le': 'utf16_le',
    'utf_16_le': 'utf16_le',
    'utf-16le': 'utf16_le',
    'utf_8': 'utf_8',
    'u8': 'utf_8',
    'utf': 'utf_8',
    'utf8': 'utf_8',
    'utf-8': 'utf_8',
    }
Definition at line 43 of file configobj.py.
dictionary lib.configobj.BOM_SET
Initial value:
= {
    'utf_8': BOM_UTF8,
    'utf_16': BOM_UTF16,
    'utf16_be': BOM_UTF16_BE,
    'utf16_le': BOM_UTF16_LE,
    None: BOM_UTF8
    }
Definition at line 62 of file configobj.py.
dictionary lib.configobj.BOMS
Initial value:
= {
    BOM_UTF8: ('utf_8', None),
    BOM_UTF16_BE: ('utf16_be', 'utf_16'),
    BOM_UTF16_LE: ('utf16_le', 'utf_16'),
    BOM_UTF16: ('utf_16', 'utf_16'),
    }
Definition at line 34 of file configobj.py.
lib.configobj.compiler = None
Definition at line 29 of file configobj.py.
string lib.configobj.DEFAULT_INDENT_TYPE = ' '
Definition at line 121 of file configobj.py.
string lib.configobj.DEFAULT_INTERPOLATION = 'configparser'
Definition at line 120 of file configobj.py.
string lib.configobj.dquot = ''%s''
Definition at line 77 of file configobj.py.
dictionary lib.configobj.interpolation_engines
Initial value:
= {
    'configparser': ConfigParserInterpolation,
    'template': TemplateInterpolation,
}
Definition at line 461 of file configobj.py.
int lib.configobj.MAX_INTERPOL_DEPTH = 10
Definition at line 122 of file configobj.py.
tuple lib.configobj.MISSING = object()
Definition at line 84 of file configobj.py.
string lib.configobj.noquot = '%s'
Definition at line 78 of file configobj.py.
dictionary lib.configobj.OPTION_DEFAULTS
Initial value:
= {
    'interpolation': True,
    'raise_errors': False,
    'list_values': True,
    'create_empty': False,
    'file_error': False,
    'configspec': None,
    'stringify': True,
    # option may be set to one of ('', ' ', '\t')
    'indent_type': None,
    'encoding': None,
    'default_encoding': None,
    'unrepr': False,
    'write_empty_values': False,
}
Definition at line 124 of file configobj.py.
string lib.configobj.squot = ''%s''
Definition at line 76 of file configobj.py.
string lib.configobj.tdquot = ''''%s''''
Definition at line 81 of file configobj.py.
string lib.configobj.tsquot = ''''%s''''
Definition at line 80 of file configobj.py.
string lib.configobj.wspace_plus = ' \r\n\v\t\'''
Definition at line 79 of file configobj.py.
Author
Generated automatically by Doxygen for PlotLib from the source code.