lib.configobj.Section
NAME
lib.configobj.Section -
SYNOPSIS
Inherits dict.
Inherited by lib.configobj.ConfigObj.
Public Member Functions
def __setstate__
def __reduce__
def __init__
def __getitem__
def __setitem__
def __delitem__
def get
def update
def pop
def popitem
def clear
def setdefault
def items
def keys
def values
def iteritems
def iterkeys
def itervalues
def __repr__
def dict
def merge
def rename
def walk
def as_bool
def as_int
def as_float
def as_list
def restore_default
def restore_defaults
Public Attributes
parent
main
depth
name
scalars
sections
comments
inline_comments
configspec
defaults
default_values
extra_values
Private Member Functions
def _initialise
def _interpolate
Private Attributes
_created
_interpolation_engine
Static Private Attributes
__iter__ = iterkeys
__str__ = __repr__
Detailed Description
A dictionary-like object that represents a section in a config file.
It does string interpolation if the 'interpolation' attribute
of the 'main' object is set to True.
Interpolation is tried first from this object, then from the 'DEFAULT'
section of this object, next from the parent and its 'DEFAULT' section,
and so on until the main object is reached.
A Section will behave like an ordered dictionary - following the
order of the ``scalars`` and ``sections`` attributes.
You can use this to change the order of members.
Iteration follows the order: scalars, then sections.
Definition at line 471 of file configobj.py.
Constructor & Destructor Documentation
def lib.configobj.Section.__init__ (self, parent, depth, main, indict = None, name = None)
* parent is the section above
* depth is the depth level of this section
* main is the main ConfigObj
* indict is a dictionary to initialise the section with
Definition at line 499 of file configobj.py.
Member Function Documentation
def lib.configobj.Section.__delitem__ (self, key)
Remove items from the sequence when deleting.
Definition at line 641 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.inline_comments, and lib.configobj.Section.scalars.
def lib.configobj.Section.__getitem__ (self, key)
Fetch the item and do string interpolation.
Definition at line 565 of file configobj.py.
References lib.configobj.Section._interpolate().
def lib.configobj.Section.__reduce__ (self)
Definition at line 494 of file configobj.py.
References lib.configobj.Section.dict().
def lib.configobj.Section.__repr__ (self)
x.__repr__() <==> repr(x)
Definition at line 754 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.__setitem__ (self, key, value, unrepr = False)
Correctly set a value.
Making dictionary values Section instances.
(We have to special case 'Section' instances - which are also dicts)
Keys must be strings.
Values need only be strings (or lists of strings) if
``main.stringify`` is set.
``unrepr`` must be set when setting a value to a dictionary, without
creating a new sub-section.
Definition at line 582 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.defaults, lib.configobj.Section.depth, lib.configobj.Section.inline_comments, and lib.configobj.Section.main.
def lib.configobj.Section.__setstate__ (self, state)
Definition at line 490 of file configobj.py.
def lib.configobj.Section._initialise (self) [private]
Definition at line 525 of file configobj.py.
Referenced by lib.configobj.ConfigObj.reload(), and lib.configobj.ConfigObj.reset().
def lib.configobj.Section._interpolate (self, key, value) [private]
Definition at line 542 of file configobj.py.
References lib.configobj.Section._interpolation_engine.
Referenced by lib.configobj.Section.__getitem__().
def lib.configobj.Section.as_bool (self, key)
Accepts a key as input. The corresponding value must be a string or
the objects (``True`` or 1) or (``False`` or 0). We allow 0 and 1 to
retain compatibility with Python 2.2.
If the string is one of ``True``, ``On``, ``Yes``, or ``1`` it returns
``True``.
If the string is one of ``False``, ``Off``, ``No``, or ``0`` it returns
``False``.
``as_bool`` is not case sensitive.
Any other input will raise a ``ValueError``.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_bool('a')
Traceback (most recent call last):
ValueError: Value "fish" is neither True nor False
>>> a['b'] = 'True'
>>> a.as_bool('b')
>>> a['b'] = 'off'
>>> a.as_bool('b')
Definition at line 940 of file configobj.py.
def lib.configobj.Section.as_float (self, key)
A convenience method which coerces the specified value to a float.
If the value is an invalid literal for ``float``, a ``ValueError`` will
be raised.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_float('a')
Traceback (most recent call last):
ValueError: invalid literal for float(): fish
>>> a['b'] = '1'
>>> a.as_float('b')
1.0
>>> a['b'] = '3.2'
>>> a.as_float('b')
3.2000000000000002
Definition at line 1007 of file configobj.py.
def lib.configobj.Section.as_int (self, key)
A convenience method which coerces the specified value to an integer.
If the value is an invalid literal for ``int``, a ``ValueError`` will
be raised.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_int('a')
Traceback (most recent call last):
ValueError: invalid literal for int() with base 10: 'fish'
>>> a['b'] = '1'
>>> a.as_int('b')
>>> a['b'] = '3.2'
>>> a.as_int('b')
Traceback (most recent call last):
ValueError: invalid literal for int() with base 10: '3.2'
Definition at line 984 of file configobj.py.
def lib.configobj.Section.as_list (self, key)
A convenience method which fetches the specified value, guaranteeing
that it is a list.
>>> a = ConfigObj()
>>> a['a'] = 1
>>> a.as_list('a')
[1]
>>> a['a'] = (1,)
>>> a.as_list('a')
[1]
>>> a['a'] = [1]
>>> a.as_list('a')
[1]
Definition at line 1029 of file configobj.py.
def lib.configobj.Section.clear (self)
A version of clear that also affects scalars/sections
Also clears comments and configspec.
Leaves other attributes alone :
    depth/main/parent are not affected
Definition at line 695 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.configspec, lib.configobj.Section.defaults, lib.configobj.Section.extra_values, lib.configobj.Section.inline_comments, lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.ConfigObj.reload(), and lib.configobj.ConfigObj.reset().
def lib.configobj.Section.dict (self)
Return a deepcopy of self as a dictionary.
All members that are ``Section`` instances are recursively turned to
ordinary dictionaries - by calling their ``dict`` method.
>>> n = a.dict()
>>> n == a
>>> n is a
Definition at line 770 of file configobj.py.
Referenced by lib.configobj.Section.__reduce__().
def lib.configobj.Section.get (self, key, default = None)
A version of ``get`` that doesn't bypass string interpolation.
Definition at line 652 of file configobj.py.
def lib.configobj.Section.items (self)
D.items() -> list of D's (key, value) pairs, as 2-tuples
Definition at line 722 of file configobj.py.
References lib.configobj.Section.scalars, lib.configobj.Section.sections, and lib.configobj.Section.values().
Referenced by lib.ordered.OrderedDict.__eq__(), lib.ordered.OrderedDict.__repr__(), and lib.configobj.Section.iteritems().
def lib.configobj.Section.iteritems (self)
D.iteritems() -> an iterator over the (key, value) items of D
Definition at line 737 of file configobj.py.
References lib.configobj.Section.items().
def lib.configobj.Section.iterkeys (self)
D.iterkeys() -> an iterator over the keys of D
Definition at line 742 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.itervalues (self)
D.itervalues() -> an iterator over the values of D
Definition at line 749 of file configobj.py.
References lib.configobj.Section.values().
def lib.configobj.Section.keys (self)
D.keys() -> list of D's keys
Definition at line 727 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.merge (self, indict)
A recursive update - useful for merging config files.
>>> a = '''[section1]
... option1 = True
... [[subsection]]
... more_options = False
... # end of file'''.splitlines()
>>> b = '''# File is user.ini
... [section1]
... option1 = False
... # end of file'''.splitlines()
>>> c1 = ConfigObj(b)
>>> c2 = ConfigObj(a)
>>> c2.merge(c1)
>>> c2
ConfigObj({'section1': {'option1': 'False', 'subsection': {'more_options': 'False'}}})
Definition at line 798 of file configobj.py.
def lib.configobj.Section.pop (self, key, default = MISSING)
'D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
If key is not found, d is returned if given, otherwise KeyError is raised'
Definition at line 668 of file configobj.py.
def lib.configobj.Section.popitem (self)
Pops the first (key,val)
Definition at line 684 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.rename (self, oldkey, newkey)
Change a keyname to another, without changing position in sequence.
Implemented so that transformations can be made on keys,
as well as on values. (used by encode and decode)
Also renames comments.
Definition at line 825 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.inline_comments, lib.configobj.Section.scalars, lib.configobj.Section.sections, and lib.configobj.Section.walk().
def lib.configobj.Section.restore_default (self, key)
Restore (and return) default value for the specified key.
This method will only work for a ConfigObj that was created
with a configspec and has been validated.
If there is no default value for this key, ``KeyError`` is raised.
Definition at line 1051 of file configobj.py.
References lib.configobj.Section.default_values, and lib.configobj.Section.defaults.
Referenced by lib.configobj.Section.restore_defaults().
def lib.configobj.Section.restore_defaults (self)
Recursively restore default values to all members
that have them.
This method will only work for a ConfigObj that was created
with a configspec and has been validated.
It doesn't delete or modify entries without default values.
Definition at line 1067 of file configobj.py.
References lib.configobj.Section.default_values, lib.configobj.Section.restore_default(), and lib.configobj.Section.sections.
def lib.configobj.Section.setdefault (self, key, default = None)
A version of setdefault that sets sequence if appropriate.
Definition at line 713 of file configobj.py.
def lib.configobj.Section.update (self, indict)
A version of update that uses our ``__setitem__``.
Definition at line 660 of file configobj.py.
def lib.configobj.Section.values (self)
D.values() -> list of D's values
Definition at line 732 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.Section.items(), and lib.configobj.Section.itervalues().
def lib.configobj.Section.walk (self, function, raise_errors = True, call_on_sections = False, keywargs)
Walk every member and call a function on the keyword and value.
Return a dictionary of the return values
If the function raises an exception, raise the errror
unless ``raise_errors=False``, in which case set the return value to
``False``.
Any unrecognised keyword arguments you pass to walk, will be pased on
to the function you pass in.
Note: if ``call_on_sections`` is ``True`` then - on encountering a
subsection, *first* the function is called for the *whole* subsection,
and then recurses into it's members. This means your function must be
able to handle strings, dictionaries and lists. This allows you
to change the key of subsections as well as for ordinary members. The
return value when called on the whole subsection has to be discarded.
See the encode and decode methods for examples, including functions.
.. admonition:: caution
    You can use ``walk`` to transform the names of members of a section
    but you mustn't add or delete members.
>>> config = '''[XXXXsection]
... XXXXkey = XXXXvalue'''.splitlines()
>>> cfg = ConfigObj(config)
>>> cfg
ConfigObj({'XXXXsection': {'XXXXkey': 'XXXXvalue'}})
>>> def transform(section, key):
... val = section[key]
... newkey = key.replace('XXXX', 'CLIENT1')
... section.rename(key, newkey)
... if isinstance(val, (tuple, list, dict)):
... pass
... else:
... val = val.replace('XXXX', 'CLIENT1')
... section[newkey] = val
>>> cfg.walk(transform, call_on_sections=True)
{'CLIENT1section': {'CLIENT1key': None}}
>>> cfg
ConfigObj({'CLIENT1section': {'CLIENT1key': 'CLIENT1value'}})
Definition at line 856 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.Section.rename().
Member Data Documentation
lib.configobj.Section.__iter__ = iterkeys [static], [private]
Definition at line 746 of file configobj.py.
lib.configobj.Section.__str__ = __repr__ [static], [private]
Definition at line 764 of file configobj.py.
lib.configobj.Section._created [private]
Definition at line 539 of file configobj.py.
lib.configobj.Section._interpolation_engine [private]
Definition at line 560 of file configobj.py.
Referenced by lib.configobj.Section._interpolate().
lib.configobj.Section.comments
Definition at line 531 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.rename().
lib.configobj.Section.configspec
Definition at line 534 of file configobj.py.
Referenced by lib.configobj.Section.clear(), lib.configobj.ConfigObj.reset(), and lib.configobj.ConfigObj.validate().
lib.configobj.Section.default_values
Definition at line 537 of file configobj.py.
Referenced by lib.configobj.Section.restore_default(), and lib.configobj.Section.restore_defaults().
lib.configobj.Section.defaults
Definition at line 536 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.restore_default().
lib.configobj.Section.depth
Definition at line 514 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__().
lib.configobj.Section.extra_values
Definition at line 538 of file configobj.py.
Referenced by lib.configobj.Section.clear().
lib.configobj.Section.inline_comments
Definition at line 532 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.rename().
lib.configobj.Section.main
Definition at line 512 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__().
lib.configobj.Section.name
Definition at line 516 of file configobj.py.
lib.configobj.Section.parent
Definition at line 510 of file configobj.py.
lib.configobj.Section.scalars
Definition at line 527 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__repr__(), lib.configobj.Section.clear(), lib.configobj.Section.items(), lib.configobj.Section.iterkeys(), lib.configobj.Section.keys(), lib.configobj.Section.popitem(), lib.configobj.Section.rename(), lib.configobj.Section.values(), and lib.configobj.Section.walk().
lib.configobj.Section.sections
Definition at line 529 of file configobj.py.
Referenced by lib.configobj.Section.__repr__(), lib.configobj.Section.clear(), lib.configobj.Section.items(), lib.configobj.Section.iterkeys(), lib.configobj.Section.keys(), lib.configobj.Section.popitem(), lib.configobj.Section.rename(), lib.configobj.Section.restore_defaults(), lib.configobj.Section.values(), and lib.configobj.Section.walk().
Author
Generated automatically by Doxygen for PlotLib from the source code.