.TH "lib.DukePlotALot2D" 3 "Thu May 28 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.DukePlotALot2D \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplotter2D\fP"
.br
.ti -1c
.RI "class \fBFixedOrderFormatter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgrid\fP"
.br
.ti -1c
.RI "def \fBcontourplot\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lib\&.DukePlotALot2D\&.contourplot (xlist, ylist, zlist, levels = \fC[]\fP, labels = \fC[]\fP, overlay = \fCTrue\fP, resolution = \fC100\fP, interactive = \fCTrue\fP, showPoints = \fCTrue\fP, logz = \fCFalse\fP, filename = \fC''\fP, contoursAlpha = \fC0\&.5\fP, contourLineWidth = \fC4\fP, CMSLabel = \fCTrue\fP, CMSLabelCoords = \fC[5\fP, xlabel = \fC'x'\fP, ylabel = \fC'y'\fP, zlabel = \fC'z'\fP, xyrange = \fC[0\fP, LegendLocation = \fC'upper right'\fP, LegendTitle = \fC'contourplot'\fP, LegendColumns = \fC1\fP)"

.PP
Definition at line 292 of file DukePlotALot2D\&.py\&.
.PP
References lib\&.DukePlotALot2D\&.grid()\&.
.PP
Referenced by lib\&.DukePlotALot2D\&.main()\&.
.SS "def lib\&.DukePlotALot2D\&.grid (x, y, z, resX = \fC100\fP, resY = \fC100\fP)"

.PP
Definition at line 272 of file DukePlotALot2D\&.py\&.
.PP
Referenced by lib\&.DukePlotALot2D\&.contourplot()\&.
.SS "def lib\&.DukePlotALot2D\&.main ()"

.PP
Definition at line 339 of file DukePlotALot2D\&.py\&.
.PP
References lib\&.DukePlotALot2D\&.contourplot()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
