lib.rootplotlib.Legend
NAME
lib.rootplotlib.Legend -
SYNOPSIS
Inherits object.
Public Member Functions
def __init__
def add
def AddEntry
def getTextWidth
def Draw
def draw
Public Attributes
textFont
textSize
tickOffset
relPosX
relPosY
lineHeight
symbolWidth
legendGap
vspace
hspace
ncolumns
pad
referenceHeight
valign
entries
margin
align
leg
Properties
x0 = property(lambda self: self.__position[0])
y0 = property(lambda self: self.__position[1])
x1 = property(lambda self: self.__position[2])
y1 = property(lambda self: self.__position[3])
width = property(lambda self: self.__position[2]-self.__position[0])
height = property(lambda self: self.__position[3]-self.__position[1])
Private Attributes
__position
Detailed Description
Definition at line 147 of file rootplotlib.py.
Constructor & Destructor Documentation
def lib.rootplotlib.Legend.__init__ (self, align = 'right', valign = 'top', pad = None, vspace = 0, hspace = 0, ncolumns = 1)
Definition at line 148 of file rootplotlib.py.
Member Function Documentation
def lib.rootplotlib.Legend.add (self, hist, label, option = '')
Definition at line 173 of file rootplotlib.py.
Referenced by lib.rootplotlib.Legend.AddEntry().
def lib.rootplotlib.Legend.AddEntry (self, hist, label, option = '')
Definition at line 175 of file rootplotlib.py.
References lib.rootplotlib.Legend.add().
def lib.rootplotlib.Legend.Draw (self)
Definition at line 184 of file rootplotlib.py.
References lib.rootplotlib.Legend.draw().
def lib.rootplotlib.Legend.draw (self)
Definition at line 186 of file rootplotlib.py.
References lib.rootplotlib.Legend.entries, and lib.rootplotlib.Legend.getTextWidth().
Referenced by lib.rootplotlib.Legend.Draw().
def lib.rootplotlib.Legend.getTextWidth (self, text)
Definition at line 177 of file rootplotlib.py.
References lib.rootplotlib.Legend.referenceHeight, lib.rootplotlib.Legend.textFont, and lib.rootplotlib.Legend.textSize.
Referenced by lib.rootplotlib.Legend.draw().
Member Data Documentation
lib.rootplotlib.Legend.__position [private]
Definition at line 172 of file rootplotlib.py.
lib.rootplotlib.Legend.align
Definition at line 207 of file rootplotlib.py.
lib.rootplotlib.Legend.entries
Definition at line 171 of file rootplotlib.py.
Referenced by lib.rootplotlib.Legend.draw().
lib.rootplotlib.Legend.hspace
Definition at line 158 of file rootplotlib.py.
lib.rootplotlib.Legend.leg
Definition at line 228 of file rootplotlib.py.
lib.rootplotlib.Legend.legendGap
Definition at line 156 of file rootplotlib.py.
lib.rootplotlib.Legend.lineHeight
Definition at line 154 of file rootplotlib.py.
lib.rootplotlib.Legend.margin
Definition at line 196 of file rootplotlib.py.
lib.rootplotlib.Legend.ncolumns
Definition at line 159 of file rootplotlib.py.
lib.rootplotlib.Legend.pad
Definition at line 161 of file rootplotlib.py.
lib.rootplotlib.Legend.referenceHeight
Definition at line 167 of file rootplotlib.py.
Referenced by lib.rootplotlib.Legend.getTextWidth().
lib.rootplotlib.Legend.relPosX
Definition at line 152 of file rootplotlib.py.
lib.rootplotlib.Legend.relPosY
Definition at line 153 of file rootplotlib.py.
lib.rootplotlib.Legend.symbolWidth
Definition at line 155 of file rootplotlib.py.
lib.rootplotlib.Legend.textFont
Definition at line 149 of file rootplotlib.py.
Referenced by lib.rootplotlib.Legend.getTextWidth().
lib.rootplotlib.Legend.textSize
Definition at line 150 of file rootplotlib.py.
Referenced by lib.rootplotlib.Legend.getTextWidth().
lib.rootplotlib.Legend.tickOffset
Definition at line 151 of file rootplotlib.py.
lib.rootplotlib.Legend.valign
Definition at line 170 of file rootplotlib.py.
lib.rootplotlib.Legend.vspace
Definition at line 157 of file rootplotlib.py.
Property Documentation
lib.rootplotlib.Legend.height = property(lambda self: self.__position[3]-self.__position[1]) [static]
Definition at line 234 of file rootplotlib.py.
lib.rootplotlib.Legend.width = property(lambda self: self.__position[2]-self.__position[0]) [static]
Definition at line 233 of file rootplotlib.py.
lib.rootplotlib.Legend.x0 = property(lambda self: self.__position[0]) [static]
Definition at line 229 of file rootplotlib.py.
lib.rootplotlib.Legend.x1 = property(lambda self: self.__position[2]) [static]
Definition at line 231 of file rootplotlib.py.
lib.rootplotlib.Legend.y0 = property(lambda self: self.__position[1]) [static]
Definition at line 230 of file rootplotlib.py.
lib.rootplotlib.Legend.y1 = property(lambda self: self.__position[3]) [static]
Definition at line 232 of file rootplotlib.py.
Author
Generated automatically by Doxygen for PlotLib from the source code.