.TH "lib.configobj.ConfigObjError" 3 "Tue Aug 4 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.ConfigObjError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SyntaxError\&.
.PP
Inherited by \fBlib\&.configobj\&.ConfigspecError\fP, \fBlib\&.configobj\&.DuplicateError\fP, \fBlib\&.configobj\&.InterpolationError\fP, \fBlib\&.configobj\&.NestingError\fP, \fBlib\&.configobj\&.ParseError\fP, \fBlib\&.configobj\&.RepeatSectionError\fP, and \fBlib\&.configobj\&.UnreprError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBline\fP"
.br
.ti -1c
.RI "\fBline_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This is the base class for all errors that ConfigObj raises.
It is a subclass of SyntaxError.

.fi
.PP
 
.PP
Definition at line 221 of file configobj\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lib\&.configobj\&.ConfigObjError\&.__init__ (self, message = \fC''\fP, line_number = \fCNone\fP, line = \fC''\fP)"

.PP
Definition at line 226 of file configobj\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lib\&.configobj\&.ConfigObjError\&.line"

.PP
Definition at line 227 of file configobj\&.py\&.
.SS "lib\&.configobj\&.ConfigObjError\&.line_number"

.PP
Definition at line 228 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
