lib.object_plotting
NAME
lib.object_plotting -
SYNOPSIS
Functions
def plot_upper_cut
def plot_lower_cut
def plot_both_cuts
def gaussian
def plot_gauss_fit
def eff_function
def plot_efficiency_fit
def res_function
def plot_resolution_fit
def draw_lines
Function Documentation
def lib.object_plotting.draw_lines (axis)
Definition at line 245 of file object_plotting.py.
def lib.object_plotting.eff_function (x, par)
Definition at line 112 of file object_plotting.py.
Referenced by lib.object_plotting.plot_efficiency_fit().
def lib.object_plotting.gaussian (x, norm, mu, sig)
Definition at line 60 of file object_plotting.py.
Referenced by lib.object_plotting.plot_gauss_fit().
def lib.object_plotting.plot_both_cuts (axis1, value1, value2, include = True, cut_arrow_position = 0.5)
Definition at line 44 of file object_plotting.py.
References lib.object_plotting.plot_lower_cut(), and lib.object_plotting.plot_upper_cut().
def lib.object_plotting.plot_efficiency_fit (axis1, histo, xmin = 0, xmax = 0, startvals = [], plottrange = [], color = 'black')
Definition at line 115 of file object_plotting.py.
References lib.object_plotting.eff_function().
def lib.object_plotting.plot_gauss_fit (axis1, histo, xmin = 0, xmax = 0, color = 'black', write_results = False)
Definition at line 63 of file object_plotting.py.
References lib.object_plotting.gaussian().
def lib.object_plotting.plot_lower_cut (axis1, value, cut_arrow_position = 0.5)
Definition at line 29 of file object_plotting.py.
Referenced by lib.object_plotting.plot_both_cuts().
def lib.object_plotting.plot_resolution_fit (axis1, histo, xmin = 0, xmax = 0, startvals = [], plottrange = [], color = 'black')
Definition at line 181 of file object_plotting.py.
References lib.object_plotting.res_function().
def lib.object_plotting.plot_upper_cut (axis1, value, cut_arrow_position = 0.5)
Definition at line 14 of file object_plotting.py.
Referenced by lib.object_plotting.plot_both_cuts().
def lib.object_plotting.res_function (x, par)
Definition at line 178 of file object_plotting.py.
Referenced by lib.object_plotting.plot_resolution_fit().
Author
Generated automatically by Doxygen for PlotLib from the source code.