lib.configobj.ConfigObj
NAME
lib.configobj.ConfigObj -
SYNOPSIS
Inherits lib.configobj.Section.
Public Member Functions
def write
def validate
def reset
def reload
def __setstate__
def __reduce__
def __getitem__
def __setitem__
def __delitem__
def get
def update
def pop
def popitem
def clear
def setdefault
def items
def keys
def values
def iteritems
def iterkeys
def itervalues
def __repr__
def dict
def merge
def rename
def walk
def as_bool
def as_int
def as_float
def as_list
def restore_default
def restore_defaults
Public Attributes
configspec
indent_type
interpolation
parent
main
depth
name
scalars
sections
comments
inline_comments
defaults
default_values
extra_values
Static Public Attributes
quot = tdquot
Private Member Functions
def _handle_value
def _multiline
def _handle_configspec
def _set_configspec
def _write_line
def _write_marker
def _handle_comment
Private Attributes
_vdtMissingValue
_original_configspec
Static Private Attributes
tuple _keyword
tuple _valueexp
Detailed Description
An object to read, create, and write config files.
Definition at line 1084 of file configobj.py.
Member Function Documentation
def lib.configobj.Section.__delitem__ (self, key) [inherited]
Remove items from the sequence when deleting.
Definition at line 641 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.inline_comments, and lib.configobj.Section.scalars.
def lib.configobj.Section.__getitem__ (self, key) [inherited]
Fetch the item and do string interpolation.
Definition at line 565 of file configobj.py.
References lib.configobj.Section._interpolate().
def lib.configobj.Section.__reduce__ (self) [inherited]
Definition at line 494 of file configobj.py.
References lib.configobj.Section.dict().
def lib.configobj.Section.__repr__ (self) [inherited]
x.__repr__() <==> repr(x)
Definition at line 754 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.__setitem__ (self, key, value, unrepr = False) [inherited]
Correctly set a value.
Making dictionary values Section instances.
(We have to special case 'Section' instances - which are also dicts)
Keys must be strings.
Values need only be strings (or lists of strings) if
``main.stringify`` is set.
``unrepr`` must be set when setting a value to a dictionary, without
creating a new sub-section.
Definition at line 582 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.defaults, lib.configobj.Section.depth, lib.configobj.Section.inline_comments, and lib.configobj.Section.main.
def lib.configobj.Section.__setstate__ (self, state) [inherited]
Definition at line 490 of file configobj.py.
def lib.configobj.ConfigObj._handle_comment (self, comment) [private]
Deal with a comment.
Definition at line 1994 of file configobj.py.
References lib.configobj.ConfigObj.indent_type.
def lib.configobj.ConfigObj._handle_configspec (self, configspec) [private]
Parse the configspec.
Definition at line 1922 of file configobj.py.
def lib.configobj.ConfigObj._handle_value (self, value) [private]
Given a value string, unquote, remove comment,
handle lists. (including empty and single member lists)
Definition at line 1838 of file configobj.py.
def lib.configobj.ConfigObj._multiline (self, value, infile, cur_index, maxline) [private]
Extract the value, where we are in a multiline situation.
Definition at line 1887 of file configobj.py.
def lib.configobj.ConfigObj._set_configspec (self, section, copy) [private]
Called by validate. Handles setting the configspec on subsections
including sections to be validated by __many__
Definition at line 1943 of file configobj.py.
def lib.configobj.ConfigObj._write_line (self, indent_string, entry, this_entry, comment) [private]
Write an individual line, for the write method
Definition at line 1971 of file configobj.py.
def lib.configobj.ConfigObj._write_marker (self, indent_string, depth, entry, comment) [private]
Write a section marker line
Definition at line 1985 of file configobj.py.
def lib.configobj.Section.as_bool (self, key) [inherited]
Accepts a key as input. The corresponding value must be a string or
the objects (``True`` or 1) or (``False`` or 0). We allow 0 and 1 to
retain compatibility with Python 2.2.
If the string is one of ``True``, ``On``, ``Yes``, or ``1`` it returns
``True``.
If the string is one of ``False``, ``Off``, ``No``, or ``0`` it returns
``False``.
``as_bool`` is not case sensitive.
Any other input will raise a ``ValueError``.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_bool('a')
Traceback (most recent call last):
ValueError: Value "fish" is neither True nor False
>>> a['b'] = 'True'
>>> a.as_bool('b')
>>> a['b'] = 'off'
>>> a.as_bool('b')
Definition at line 940 of file configobj.py.
def lib.configobj.Section.as_float (self, key) [inherited]
A convenience method which coerces the specified value to a float.
If the value is an invalid literal for ``float``, a ``ValueError`` will
be raised.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_float('a')
Traceback (most recent call last):
ValueError: invalid literal for float(): fish
>>> a['b'] = '1'
>>> a.as_float('b')
1.0
>>> a['b'] = '3.2'
>>> a.as_float('b')
3.2000000000000002
Definition at line 1007 of file configobj.py.
def lib.configobj.Section.as_int (self, key) [inherited]
A convenience method which coerces the specified value to an integer.
If the value is an invalid literal for ``int``, a ``ValueError`` will
be raised.
>>> a = ConfigObj()
>>> a['a'] = 'fish'
>>> a.as_int('a')
Traceback (most recent call last):
ValueError: invalid literal for int() with base 10: 'fish'
>>> a['b'] = '1'
>>> a.as_int('b')
>>> a['b'] = '3.2'
>>> a.as_int('b')
Traceback (most recent call last):
ValueError: invalid literal for int() with base 10: '3.2'
Definition at line 984 of file configobj.py.
def lib.configobj.Section.as_list (self, key) [inherited]
A convenience method which fetches the specified value, guaranteeing
that it is a list.
>>> a = ConfigObj()
>>> a['a'] = 1
>>> a.as_list('a')
[1]
>>> a['a'] = (1,)
>>> a.as_list('a')
[1]
>>> a['a'] = [1]
>>> a.as_list('a')
[1]
Definition at line 1029 of file configobj.py.
def lib.configobj.Section.clear (self) [inherited]
A version of clear that also affects scalars/sections
Also clears comments and configspec.
Leaves other attributes alone :
    depth/main/parent are not affected
Definition at line 695 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.configspec, lib.configobj.Section.defaults, lib.configobj.Section.extra_values, lib.configobj.Section.inline_comments, lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.ConfigObj.reload(), and lib.configobj.ConfigObj.reset().
def lib.configobj.Section.dict (self) [inherited]
Return a deepcopy of self as a dictionary.
All members that are ``Section`` instances are recursively turned to
ordinary dictionaries - by calling their ``dict`` method.
>>> n = a.dict()
>>> n == a
>>> n is a
Definition at line 770 of file configobj.py.
Referenced by lib.configobj.Section.__reduce__().
def lib.configobj.Section.get (self, key, default = None) [inherited]
A version of ``get`` that doesn't bypass string interpolation.
Definition at line 652 of file configobj.py.
def lib.configobj.Section.items (self) [inherited]
D.items() -> list of D's (key, value) pairs, as 2-tuples
Definition at line 722 of file configobj.py.
References lib.configobj.Section.scalars, lib.configobj.Section.sections, and lib.configobj.Section.values().
Referenced by lib.ordered.OrderedDict.__eq__(), lib.ordered.OrderedDict.__repr__(), and lib.configobj.Section.iteritems().
def lib.configobj.Section.iteritems (self) [inherited]
D.iteritems() -> an iterator over the (key, value) items of D
Definition at line 737 of file configobj.py.
References lib.configobj.Section.items().
def lib.configobj.Section.iterkeys (self) [inherited]
D.iterkeys() -> an iterator over the keys of D
Definition at line 742 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.itervalues (self) [inherited]
D.itervalues() -> an iterator over the values of D
Definition at line 749 of file configobj.py.
References lib.configobj.Section.values().
def lib.configobj.Section.keys (self) [inherited]
D.keys() -> list of D's keys
Definition at line 727 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.Section.merge (self, indict) [inherited]
A recursive update - useful for merging config files.
>>> a = '''[section1]
... option1 = True
... [[subsection]]
... more_options = False
... # end of file'''.splitlines()
>>> b = '''# File is user.ini
... [section1]
... option1 = False
... # end of file'''.splitlines()
>>> c1 = ConfigObj(b)
>>> c2 = ConfigObj(a)
>>> c2.merge(c1)
>>> c2
ConfigObj({'section1': {'option1': 'False', 'subsection': {'more_options': 'False'}}})
Definition at line 798 of file configobj.py.
def lib.configobj.Section.pop (self, key, default = MISSING) [inherited]
'D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
If key is not found, d is returned if given, otherwise KeyError is raised'
Definition at line 668 of file configobj.py.
def lib.configobj.Section.popitem (self) [inherited]
Pops the first (key,val)
Definition at line 684 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
def lib.configobj.ConfigObj.reload (self)
Reload a ConfigObj from file.
This method raises a ``ReloadError`` if the ConfigObj doesn't have
a filename attribute pointing to a file.
Definition at line 2334 of file configobj.py.
References lib.configobj.Section._initialise(), lib.configobj.ConfigObj._original_configspec, and lib.configobj.Section.clear().
def lib.configobj.Section.rename (self, oldkey, newkey) [inherited]
Change a keyname to another, without changing position in sequence.
Implemented so that transformations can be made on keys,
as well as on values. (used by encode and decode)
Also renames comments.
Definition at line 825 of file configobj.py.
References lib.configobj.Section.comments, lib.configobj.Section.inline_comments, lib.configobj.Section.scalars, lib.configobj.Section.sections, and lib.configobj.Section.walk().
def lib.configobj.ConfigObj.reset (self)
Clear ConfigObj instance and restore to 'freshly created' state.
Definition at line 2323 of file configobj.py.
References lib.configobj.Section._initialise(), lib.configobj.Section.clear(), and lib.configobj.Section.configspec.
def lib.configobj.Section.restore_default (self, key) [inherited]
Restore (and return) default value for the specified key.
This method will only work for a ConfigObj that was created
with a configspec and has been validated.
If there is no default value for this key, ``KeyError`` is raised.
Definition at line 1051 of file configobj.py.
References lib.configobj.Section.default_values, and lib.configobj.Section.defaults.
Referenced by lib.configobj.Section.restore_defaults().
def lib.configobj.Section.restore_defaults (self) [inherited]
Recursively restore default values to all members
that have them.
This method will only work for a ConfigObj that was created
with a configspec and has been validated.
It doesn't delete or modify entries without default values.
Definition at line 1067 of file configobj.py.
References lib.configobj.Section.default_values, lib.configobj.Section.restore_default(), and lib.configobj.Section.sections.
def lib.configobj.Section.setdefault (self, key, default = None) [inherited]
A version of setdefault that sets sequence if appropriate.
Definition at line 713 of file configobj.py.
def lib.configobj.Section.update (self, indict) [inherited]
A version of update that uses our ``__setitem__``.
Definition at line 660 of file configobj.py.
def lib.configobj.ConfigObj.validate (self, validator, preserve_errors = False, copy = False, section = None)
Test the ConfigObj against a configspec.
It uses the ``validator`` object from *validate.py*.
To run ``validate`` on the current ConfigObj, call: ::
    test = config.validate(validator)
(Normally having previously passed in the configspec when the ConfigObj
was created - you can dynamically assign a dictionary of checks to the
``configspec`` attribute of a section though).
It returns ``True`` if everything passes, or a dictionary of
pass/fails (True/False). If every member of a subsection passes, it
will just have the value ``True``. (It also returns ``False`` if all
members fail).
In addition, it converts the values from strings to their native
types if their checks pass (and ``stringify`` is set).
If ``preserve_errors`` is ``True`` (``False`` is default) then instead
of a marking a fail with a ``False``, it will preserve the actual
exception object. This can contain info about the reason for failure.
For example the ``VdtValueTooSmallError`` indicates that the value
supplied was too small. If a value (or section) is missing it will
still be marked as ``False``.
You must have the validate module to use ``preserve_errors=True``.
You can then use the ``flatten_errors`` function to turn your nested
results dictionary into a flattened list of failures - useful for
displaying meaningful error messages.
Definition at line 2117 of file configobj.py.
References lib.configobj.Section.configspec.
def lib.configobj.Section.values (self) [inherited]
D.values() -> list of D's values
Definition at line 732 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.Section.items(), and lib.configobj.Section.itervalues().
def lib.configobj.Section.walk (self, function, raise_errors = True, call_on_sections = False, keywargs) [inherited]
Walk every member and call a function on the keyword and value.
Return a dictionary of the return values
If the function raises an exception, raise the errror
unless ``raise_errors=False``, in which case set the return value to
``False``.
Any unrecognised keyword arguments you pass to walk, will be pased on
to the function you pass in.
Note: if ``call_on_sections`` is ``True`` then - on encountering a
subsection, *first* the function is called for the *whole* subsection,
and then recurses into it's members. This means your function must be
able to handle strings, dictionaries and lists. This allows you
to change the key of subsections as well as for ordinary members. The
return value when called on the whole subsection has to be discarded.
See the encode and decode methods for examples, including functions.
.. admonition:: caution
    You can use ``walk`` to transform the names of members of a section
    but you mustn't add or delete members.
>>> config = '''[XXXXsection]
... XXXXkey = XXXXvalue'''.splitlines()
>>> cfg = ConfigObj(config)
>>> cfg
ConfigObj({'XXXXsection': {'XXXXkey': 'XXXXvalue'}})
>>> def transform(section, key):
... val = section[key]
... newkey = key.replace('XXXX', 'CLIENT1')
... section.rename(key, newkey)
... if isinstance(val, (tuple, list, dict)):
... pass
... else:
... val = val.replace('XXXX', 'CLIENT1')
... section[newkey] = val
>>> cfg.walk(transform, call_on_sections=True)
{'CLIENT1section': {'CLIENT1key': None}}
>>> cfg
ConfigObj({'CLIENT1section': {'CLIENT1key': 'CLIENT1value'}})
Definition at line 856 of file configobj.py.
References lib.configobj.Section.scalars, and lib.configobj.Section.sections.
Referenced by lib.configobj.Section.rename().
def lib.configobj.ConfigObj.write (self, outfile = None, section = None)
Write the current ConfigObj as a file
tekNico: FIXME: use StringIO instead of real files
>>> filename = a.filename
>>> a.filename = 'test.ini'
>>> a.write()
>>> a.filename = filename
>>> a == ConfigObj('test.ini', raise_errors=True)
>>> import os
>>> os.remove('test.ini')
Definition at line 2006 of file configobj.py.
References lib.configobj.ConfigObj.indent_type.
Member Data Documentation
tuple lib.configobj.ConfigObj._keyword [static], [private]
Initial value:
= re.compile(r'''^ # line start
    (\s*) # indentation
    ( # keyword
        (?:".*?")| # double quotes
        (?:'.*?')| # single quotes
        (?:[^'"=].*?) # no quotes ) \s*=\s* # divider (.*) # value (including list values and comments) $ # line end ''', re.VERBOSE) _sectionmarker = re.compile(r'''^ (\s*) # 1: indentation ((?:\[\s*)+) # 2: section marker open ( # 3: section name open (?:"\s*\S.*?\s*")| # at least one non-space with double quotes (?:'\s*\S.*?\s*')| # at least one non-space with single quotes (?:[^'"\s].*?) # at least one non-space unquoted
    ) # section name close
    ((?:\s*\])+) # 4: section marker close
    \s*(\#.*)? # 5: optional comment
    $''',
        re.VERBOSE)
Definition at line 1087 of file configobj.py.
lib.configobj.ConfigObj._original_configspec [private]
Definition at line 2331 of file configobj.py.
Referenced by lib.configobj.ConfigObj.reload().
tuple lib.configobj.ConfigObj._valueexp [static], [private]
Definition at line 1117 of file configobj.py.
lib.configobj.ConfigObj._vdtMissingValue [private]
Definition at line 2159 of file configobj.py.
lib.configobj.Section.comments [inherited]
Definition at line 531 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.rename().
lib.configobj.ConfigObj.configspec
Definition at line 1939 of file configobj.py.
lib.configobj.Section.default_values [inherited]
Definition at line 537 of file configobj.py.
Referenced by lib.configobj.Section.restore_default(), and lib.configobj.Section.restore_defaults().
lib.configobj.Section.defaults [inherited]
Definition at line 536 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.restore_default().
lib.configobj.Section.depth [inherited]
Definition at line 514 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__().
lib.configobj.Section.extra_values [inherited]
Definition at line 538 of file configobj.py.
Referenced by lib.configobj.Section.clear().
lib.configobj.ConfigObj.indent_type
Definition at line 2023 of file configobj.py.
Referenced by lib.configobj.ConfigObj._handle_comment(), and lib.configobj.ConfigObj.write().
lib.configobj.Section.inline_comments [inherited]
Definition at line 532 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__setitem__(), lib.configobj.Section.clear(), and lib.configobj.Section.rename().
lib.configobj.ConfigObj.interpolation
Definition at line 2030 of file configobj.py.
lib.configobj.Section.main [inherited]
Definition at line 512 of file configobj.py.
Referenced by lib.configobj.Section.__setitem__().
lib.configobj.Section.name [inherited]
Definition at line 516 of file configobj.py.
lib.configobj.Section.parent [inherited]
Definition at line 510 of file configobj.py.
lib.configobj.ConfigObj.quot = tdquot [static]
Definition at line 1832 of file configobj.py.
lib.configobj.Section.scalars [inherited]
Definition at line 527 of file configobj.py.
Referenced by lib.configobj.Section.__delitem__(), lib.configobj.Section.__repr__(), lib.configobj.Section.clear(), lib.configobj.Section.items(), lib.configobj.Section.iterkeys(), lib.configobj.Section.keys(), lib.configobj.Section.popitem(), lib.configobj.Section.rename(), lib.configobj.Section.values(), and lib.configobj.Section.walk().
lib.configobj.Section.sections [inherited]
Definition at line 529 of file configobj.py.
Referenced by lib.configobj.Section.__repr__(), lib.configobj.Section.clear(), lib.configobj.Section.items(), lib.configobj.Section.iterkeys(), lib.configobj.Section.keys(), lib.configobj.Section.popitem(), lib.configobj.Section.rename(), lib.configobj.Section.restore_defaults(), lib.configobj.Section.values(), and lib.configobj.Section.walk().
Author
Generated automatically by Doxygen for PlotLib from the source code.