.TH "lib/plotlib.py" 3 "Wed Feb 11 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/plotlib.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlib\&.plotlib\&.NoDictMessagesFilter\fP"
.br
.ti -1c
.RI "class \fBlib\&.plotlib\&.HistStorageContainer\fP"
.br
.ti -1c
.RI "class \fBlib\&.plotlib\&.HistStorage\fP"
.br
.RI "\fIClass to handle histograms functions\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.plotlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlib\&.plotlib\&.xfrange\fP"
.br
.RI "\fIhelper methods \fP"
.ti -1c
.RI "def \fBlib\&.plotlib\&.getColorList\fP"
.br
.ti -1c
.RI "def \fBlib\&.plotlib\&.getDictValue\fP"
.br
.ti -1c
.RI "def \fBlib\&.plotlib\&.duke_errorbar\fP"
.br
.ti -1c
.RI "def \fBlib\&.plotlib\&._duke__errorbar\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
