.TH "py_test" 3 "Thu Apr 30 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py_test \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhist_example\fP"
.br
.ti -1c
.RI "def \fBmpl_example\fP"
.br
.ti -1c
.RI "def \fBr2m_example\fP"
.br
.ti -1c
.RI "def \fBtest\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def py_test\&.hist_example ()"

.PP
Definition at line 21 of file py_test\&.py\&.
.PP
Referenced by main()\&.
.SS "def py_test\&.main ()"

.PP
Definition at line 346 of file py_test\&.py\&.
.PP
References hist_example(), mpl_example(), r2m_example(), and test()\&.
.SS "def py_test\&.mpl_example ()"

.PP
Definition at line 85 of file py_test\&.py\&.
.PP
Referenced by main()\&.
.SS "def py_test\&.r2m_example ()"

.PP
Definition at line 158 of file py_test\&.py\&.
.PP
Referenced by main()\&.
.SS "def py_test\&.test ()"

.PP
Definition at line 249 of file py_test\&.py\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
