.TH "lib/style_class.py" 3 "Tue Aug 4 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/style_class.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlib\&.style_class\&.style_container\fP"
.br
.ti -1c
.RI "class \fBlib\&.style_class\&.position\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlib\&.style_class\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
