.TH "testplot.py" 3 "Wed Mar 18 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testplot.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBtestplot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtestplot\&.main\fP"
.br
.ti -1c
.RI "def \fBtestplot\&.readFiles\fP"
.br
.ti -1c
.RI "def \fBtestplot\&.getHists\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBtestplot\&.baseDir\fP = '/home/lo/rwth/user/out/output2014_10_8_19_12/merged/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
