.TH "rootplotlib" 3 "Wed Apr 29 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rootplotlib \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmsDecoration\fP"
.br
.ti -1c
.RI "class \fBLegend\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzvaluetopvalue\fP"
.br
.ti -1c
.RI "def \fBpvaluetozvalue\fP"
.br
.ti -1c
.RI "def \fBLatex\fP"
.br
.ti -1c
.RI "def \fBinit\fP"
.br
.ti -1c
.RI "def \fBtdrStyle\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def rootplotlib\&.init ()"

.PP
Definition at line 236 of file rootplotlib\&.py\&.
.PP
References tdrStyle()\&.
.SS "def rootplotlib\&.Latex (pad = \fCNone\fP)"

.PP
Definition at line 21 of file rootplotlib\&.py\&.
.SS "def rootplotlib\&.pvaluetozvalue (p, sided = \fC2\fP)"

.PP
Definition at line 13 of file rootplotlib\&.py\&.
.SS "def rootplotlib\&.tdrStyle ()"

.PP
Definition at line 241 of file rootplotlib\&.py\&.
.PP
Referenced by init()\&.
.SS "def rootplotlib\&.zvaluetopvalue (z, sided = \fC2\fP)"

.PP
Definition at line 5 of file rootplotlib\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
