.TH "lib.configobj.ReloadError" 3 "Fri Jul 31 2015" "PlotLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib.configobj.ReloadError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IOError\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A 'reload' operation failed.
This exception is a subclass of ``IOError``.

.fi
.PP
 
.PP
Definition at line 246 of file configobj\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lib\&.configobj\&.ReloadError\&.__init__ (self)"

.PP
Definition at line 251 of file configobj\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PlotLib from the source code\&.
