var annotated =
[
    [ "aix3a2Finder", "namespaceaix3a2Finder.html", null ],
    [ "aix3a2music", "namespaceaix3a2music.html", null ],
    [ "aix3adb2music", "namespaceaix3adb2music.html", null ],
    [ "aix3adbSampleFinder", "namespaceaix3adbSampleFinder.html", null ],
    [ "cleanProcessNames", "namespacecleanProcessNames.html", null ],
    [ "datasets", "namespacedatasets.html", null ],
    [ "fakeCondor", "namespacefakeCondor.html", null ],
    [ "githookcontroller", "namespacegithookcontroller.html", "namespacegithookcontroller" ],
    [ "helper", "namespacehelper.html", "namespacehelper" ],
    [ "HistClass", "namespaceHistClass.html", null ],
    [ "letHerFly", "namespaceletHerFly.html", null ],
    [ "lumi", "namespacelumi.html", null ],
    [ "mergeFolders", "namespacemergeFolders.html", null ],
    [ "music_crab", "namespacemusic__crab.html", null ],
    [ "music_crab3", "namespacemusic__crab3.html", null ],
    [ "parseSampleList", "namespaceparseSampleList.html", null ],
    [ "pdf_plotter", "namespacepdf__plotter.html", null ],
    [ "post-commit", "namespacepost-commit.html", null ],
    [ "pre-commit", "namespacepre-commit.html", null ],
    [ "pre-push", "namespacepre-push.html", null ],
    [ "RATA_PDF", "namespaceRATA__PDF.html", null ],
    [ "remoteAnalysis", "namespaceremoteAnalysis.html", "namespaceremoteAnalysis" ],
    [ "run", "namespacerun.html", null ],
    [ "signal_mover", "namespacesignal__mover.html", null ],
    [ "television", "namespacetelevision.html", "namespacetelevision" ],
    [ "watchdog", "namespacewatchdog.html", null ],
    [ "watchfrog", "namespacewatchfrog.html", "namespacewatchfrog" ],
    [ "wurlitzer", "namespacewurlitzer.html", null ]
];