var namespaces =
[
    [ "cleanProcessNames", "namespacecleanProcessNames.html", null ],
    [ "CrabConfigParser", "namespaceCrabConfigParser.html", null ],
    [ "crabConfigParser", "namespacecrabConfigParser.html", null ],
    [ "crabConfigParserTester", "namespacecrabConfigParserTester.html", null ],
    [ "datasets", "namespacedatasets.html", null ],
    [ "fakeCondor", "namespacefakeCondor.html", null ],
    [ "githookcontroller", "namespacegithookcontroller.html", null ],
    [ "helper", "namespacehelper.html", null ],
    [ "HistClass", "namespaceHistClass.html", null ],
    [ "letHerFly", "namespaceletHerFly.html", null ],
    [ "lumi", "namespacelumi.html", null ],
    [ "music_crab", "namespacemusic__crab.html", null ],
    [ "music_crab3", "namespacemusic__crab3.html", null ],
    [ "parseSampleList", "namespaceparseSampleList.html", null ],
    [ "pdf_plotter", "namespacepdf__plotter.html", null ],
    [ "post-commit", "namespacepost-commit.html", null ],
    [ "pre-commit", "namespacepre-commit.html", null ],
    [ "pre-push", "namespacepre-push.html", null ],
    [ "RATA_PDF", "namespaceRATA__PDF.html", null ],
    [ "signal_mover", "namespacesignal__mover.html", null ],
    [ "television", "namespacetelevision.html", null ],
    [ "watchfrog", "namespacewatchfrog.html", null ]
];