.TH "RATA_PDF Directory Reference" 3 "Fri Feb 6 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinput\fP"
.br
.ti -1c
.RI "directory \fBpython\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
