helper
NAME
helper -
helper for RATA_PDF pdf calculator
SYNOPSIS
Classes
class bcolors
Class for the different bash text colors.
Functions
def getTerminalSize
Function to get the size of the terminal.
def update_progress
Function to create and update a progress bar.
def welcome_output
Welcome output function.
def farewell_output
Farewell output function.
def Usage
Usage function, prints the usage information.
def option_parsing
Function to do the options input parsing.
def config_parsing
Function to do the config file parsing.
def control_output
Function that does a control output.
def get_event_number_list
Function to get list of event numbers.
def get_event_number
Function to get the number of events in one file.
def check_file
Function to check if there is anythin in a file.
def final_file_check
Function to check all output files.
def make_c_parameters
Function to convert the parameters for the C++ library.
Variables
tuple info = r.ProcInfo_t()
Detailed Description
helper for RATA_PDF pdf calculator
Important helping functions for the actual PDF uncertainty calculation
written by Soeren Erdweg 2013-2014
Function Documentation
def helper.check_file (file_name)
Function to check if there is anythin in a file. This function checks if the list of keys for a given file is bigger than zero, to check if the file is usable
Parameters:
file_name Name of the file to be checked
bool Either true (good file) or False (bad file)
Definition at line 344 of file helper.py.
Referenced by final_file_check().
def helper.config_parsing (options)
Function to do the config file parsing. This functions reads in the necessary config files, for the samples that should be analyzed (mc_cfg), which cross section they have (xs_cfg) and which PDF sets should be used how (pdf_cfg). The config files are also checked for sanity.
Parameters:
mc_cfg Config for the samples that should be analyzed
xs_cfg Config for the cross section of the samples
pdf_cfg Config for the PDF sets that should be used
Definition at line 219 of file helper.py.
Referenced by RATA_PDF.main().
def helper.control_output (options, mc_cfg, pdf_cfg, xs_cfg)
Function that does a control output. To check if all program parameters are correct, the most important ones are printed in this function for a quick cross check.
Parameters:
options Options object with all user defined input options
mc_cfg Config for the samples that should be analyzed
pdf_cfg Config for the PDF sets that should be used
xs_cfg Config for the cross section of the samples
Definition at line 268 of file helper.py.
Referenced by RATA_PDF.main().
def helper.farewell_output (t0, t1)
Farewell output function. Function to print the farewell output, consisting out of the local time, the programs run time and memory usage
Parameters:
t0 Total wall time
t1 Total CPU time
Todo
fix the crash at the end of the program
Definition at line 137 of file helper.py.
References raw_input().
Referenced by RATA_PDF.main().
def helper.final_file_check (options, run_samples, pdf_cfg)
Function to check all output files. This function calls check_file on every outputfile that should be produced. If the PDF calculation is done on background samples the output is also merged.
Parameters:
options Options object with all user defined input options
run_samples List of samples that were analyzed
pdf_cfg Config for the PDF sets that should be used
run_samples List of samples that were analyzed and pass the check
Definition at line 364 of file helper.py.
References check_file().
Referenced by RATA_PDF.main().
def helper.get_event_number (file_name, tree_name, cut_string)
Function to get the number of events in one file. This function reads the number of events from a given file
Parameters:
file_name Name of the file that should be analyzed
tree_name Name of the tree in the file
cut_string Cuts that should be apllied on the tree
nentries Number of events in the file
Definition at line 322 of file helper.py.
Referenced by get_event_number_list().
def helper.get_event_number_list (mc_cfg, pdf_cfg, path)
Function to get list of event numbers. This functions calculates the number of total events that should be analyzed and returns a list of the files that should be anlyzed and a list of events in each file.
Parameters:
mc_cfg Config for the samples that should be analyzed
pdf_cfg Config for the PDF sets that should be used
path Path to the files that should be analyzed
filelist List of files to be analyzed
total_events Total number of events
eventlist List of number of events for each file
Definition at line 300 of file helper.py.
References get_event_number().
Referenced by RATA_PDF.main().
def helper.getTerminalSize ()
Function to get the size of the terminal. Reads the width and height of the current terminal and returns this two values.
Parameters:
int(cr[1]) Width of the terminal
int(cr[0]) Height of the terminal
Definition at line 57 of file helper.py.
Referenced by update_progress().
def helper.make_c_parameters (mc_cfg, pdf_cfg)
Function to convert the parameters for the C++ library. To have all parameters readable by the C++ library functions, they need to be converted, this is done by this function.
Parameters:
mc_cfg Config for the samples that should be analyzed
pdf_cfg Config for the PDF sets that should be used
paras Dictionary of the converted parameters
Definition at line 396 of file helper.py.
Referenced by RATA_PDF.main().
def helper.option_parsing ()
Function to do the options input parsing. In this function the different possible comand line arguments are defined and read from the user input, they are also checked for sanity.
Parameters:
options Options object with all user defined input options
numeric_level Numeric value for the logging level
Definition at line 166 of file helper.py.
References Usage().
Referenced by RATA_PDF.main().
def helper.update_progress (progress)
Function to create and update a progress bar. This function displays or updates a console progress bar It accepts a float between 0 and 1. Any int will be converted to a float. A value under 0 represents a 'halt'. A value at 1 or bigger represents 100%
Parameters:
progress Relative progress that should be displayed
Definition at line 86 of file helper.py.
References lumi.format, and getTerminalSize().
Referenced by RATA_PDF.init_pdfs(), and RATA_PDF.pdf_file_loop().
def helper.Usage ()
Usage function, prints the usage information.
Definition at line 157 of file helper.py.
Referenced by option_parsing().
def helper.welcome_output ()
Welcome output function. Function to print the welcome output, consisting out of the ASCII art, the programs name and the local time
Definition at line 110 of file helper.py.
Referenced by RATA_PDF.main().
Variable Documentation
tuple helper.info = r.ProcInfo_t()
Definition at line 24 of file helper.py.
Author
Generated automatically by Doxygen for tools3a from the source code.