RATA_PDF/input/hist_maker.h
NAME
RATA_PDF/input/hist_maker.h -
Functions to calculate the PDF uncertainties. The functions will be called by tha RATA_PDF package.
SYNOPSIS
#include <TROOT.h>
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <iostream>
#include <fstream>
#include 'TSystem.h'
#include <TChain.h>
#include <TFile.h>
#include <TH1.h>
#include <TEfficiency.h>
#include <THnSparse.h>
#include <TKey.h>
#include <vector>
#include <map>
#include <TStopwatch.h>
#include <string>
#include 'LHAPDF/LHAPDF.h'
Namespaces
HistClass
Functions to have easy histogram handling.
Macros
#define LOG(level, message)
#define ERROR(message) LOG(1, message);
#define WARNING(message) LOG(2, message);
#define INFO(message) LOG(3, message);
#define DEBUG(message) LOG(10000, message);
#define THROW(errmsg) throw (std::string( __PRETTY_FUNCTION__ )+std::string(' (file: ')+std::string( __FILE__ )+std::string(', line: ')+std::string( Form('%d', __LINE__) )+std::string(') ')+std::string(errmsg));
Functions
void raw_input (TString question)
Function to simulate raw_input from python.
double get_scalefactor (char *f_name, double lumi, double data_mc_scf, double xs)
Function to read the MC scale factor from the number of events.
void init_bg (char *PDFpath, int n_pdfs, char **PDFsets, int loglevel)
Function to initialze the necessary PDF sets.
TTree * read_tree (char *filename, char *tree_name, char *tree_cuts)
Function to read and cut a tree from a .root file.
bool analyser (TTree *tree, char **branches, char *histname, int n_pdfs, char **PDFsets, double scalefactor)
Function to create for a given TTree the reweighted histograms.
bool writer (char *histname, int n_pdfs, char **PDFsets)
Function to write the histograms in an output file.
void make_hists (char *input_file, char *tree_name, char *tree_cuts, char **branches, double lumi, double cross_section, int n_pdfs, char **PDFsets, char *PDFnorm, char *histname, char *output_file, int n_binning, double *binning)
Function to coordinate the creation of the reweighted histograms.
vector< vector< Float_t > > hessian_pdf_asErr (vector< vector< TH1D * > > hist_scaled, double pdf_correction, double as_plus_correction, double as_minus_correction, int *as_plus_number, int *as_minus_number)
Function to calculate the overall uncertainty for a hessian PDF set.
void pdf_calcer_hessian (int n_pdfSet, char **pdf_sets, char *outfile, char *out_par, char *infile, char *main_hist, char *shortname, double pdf_correction, double as_plus_correction, double as_minus_correction, int *as_plus_number, int *as_minus_number)
Function to get the final uncertainty histograms for a hessian PDF set.
vector< vector< Float_t > > NNPDF_weighted_mean (vector< vector< TH1D * > > hist_scaled)
Function to calculate the overall uncertainty for a MC PDF set.
void pdf_calcer_MC (int n_pdfSet, char **pdf_sets, char *outfile, char *out_par, char *infile, char *main_hist, char *shortname)
Function to get the final uncertainty histograms for a MC PDF set.
static void HistClass::CreateHisto (Int_t n_histos, const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create histograms in the histo map.
static void HistClass::ClearHisto (Int_t n_histos, const char *name)
Function to clear histograms in the histo map.
static void HistClass::RebinHisto (Int_t n_histos, const char *name, Int_t n_rebin, Double_t *bins)
Function to rebin histograms in the histo map.
static void HistClass::Fill (Int_t n_histo, const char *name, double value, double weight)
Function to fille events in a histogram in the histo map.
static void HistClass::Write (Int_t n_histo, const char *name)
Function to write a histogram from the histo map.
static void HistClass::SetToZero (Int_t n_histo, const char *name)
Function to set every negative bin content to zero.
static TH1D * HistClass::ReturnHist (Int_t n_histo, const char *name)
Function to get a histogram from the histo map.
static void HistClass::DeleteHisto (Int_t n_histos, const char *name)
Function to delete a histogram from the histo map.
Variables
int gLogLevel = 4
ProcInfo_t info
LHAPDF::PDF * Mainpdf
vector< vector< LHAPDF::PDF * > > allPdfsets
static map< TString, TH1D * > histo
Detailed Description
Functions to calculate the PDF uncertainties. The functions will be called by tha RATA_PDF package.
Definition in file hist_maker.h.
Macro Definition Documentation
#define DEBUG(message) LOG(10000, message);
Definition at line 47 of file hist_maker.h.
Referenced by analyser(), get_scalefactor(), make_hists(), and read_tree().
#define ERROR(message) LOG(1, message);
Definition at line 44 of file hist_maker.h.
Referenced by analyser(), init_bg(), and writer().
#define INFO(message) LOG(3, message);
Definition at line 46 of file hist_maker.h.
Referenced by analyser(), init_bg(), and make_hists().
#define LOG(level, message)
Value:
{ if (gLogLevel >= level) { switch (level) { \
case 1: std::cerr << "ERROR: " << message << std::endl; break; \
case 2: std::cerr << "WARNING: " << message << std::endl; break; \
case 3: std::cout << "INFO: " << message << std::endl; break; \
default: std::cout << "DEBUG: " << message << std::endl; } } }
Definition at line 35 of file hist_maker.h.
#define THROW(errmsg) throw (std::string( __PRETTY_FUNCTION__ )+std::string(' (file: ')+std::string( __FILE__ )+std::string(', line: ')+std::string( Form('%d', __LINE__) )+std::string(') ')+std::string(errmsg));
Definition at line 50 of file hist_maker.h.
#define WARNING(message) LOG(2, message);
Definition at line 45 of file hist_maker.h.
Function Documentation
bool analyser (TTree *tree, char **branches, char *histname, intn_pdfs, char **PDFsets, doublescalefactor)
Function to create for a given TTree the reweighted histograms. This function reads the necessary information from a given TTree and reweights all event according to the specified PDF sets. This events are then filled in histograms fro further processing.
Parameters:
tree TTree that should be analyzed
branches Array with the name of the branches in the tree
histname Name that all filled histograms should get
n_pdfs Number of PDF sets to be analyzed
PDFsets Array with the name of the PDF sets to be analyzed
scalefactor Scalefactor that should be applied to the histograms
bool Either true(successfull loop) or false(something failed)
Definition at line 77 of file hist_maker.cpp.
References allPdfsets, DEBUG, ERROR, HistClass::Fill(), INFO, info, and Mainpdf.
Referenced by make_hists().
double get_scalefactor (char *f_name, doublelumi, doubledata_mc_scf, doublexs)
Function to read the MC scale factor from the number of events. This function takes the luminosity, data/MC scale factor and the cross section for the process, reads the number of events from a given files and returns the scale factor for this sample.
Parameters:
f_name Name of the file from which the number of events should be read
lumi Luminosity
data_mc_scf Optional scale factor between MC and data
xs Cross section of the process
scf Scale factor for the given sample
Definition at line 40 of file hist_maker.cpp.
References DEBUG, datasets::file, and signal_mover::scf.
Referenced by make_hists().
vector< vector<Float_t> > hessian_pdf_asErr (vector< vector< TH1D * > >hist_scaled, doublepdf_correction, doubleas_plus_correction, doubleas_minus_correction, int *as_plus_number, int *as_minus_number)
Function to calculate the overall uncertainty for a hessian PDF set. This function calculates the overall uncertainty for a hessian PDF set. It also calculates the uncertainties due to the alpha_S and adds this two uncertainties in quadrature. The whole procedure follows the PDF4LHC recommendation.
Parameters:
hist_scaled Vector of Vector of all histograms necessary
pdf_correction Global correction factor for this PDF set
as_plus_correction Correction factor for the alpha_S plus uncertainties
as_minus_correction Correction factor for the alpha_S minus uncertainties
as_plus_number Number of the alpha_S plus member, defined by the PDF config
as_minus_number Number of the alpha_S minus member, defined by the PDF config
v_as_errors Vector of Vector with the resulting uncertainties for each bin
Definition at line 294 of file hist_maker.cpp.
Referenced by pdf_calcer_hessian().
void init_bg (char *PDFpath, intn_pdfs, char **PDFsets, intloglevel)
Function to initialze the necessary PDF sets. This function is called by RATA_PDF to initiate the PDF sets, used later for the calculation of the PDF uncertainties.
Parameters:
PDFpath Path to where the PDF sets are installed
n_pdfs Number of PDF sets that should be initialized
PDFsets Array of the PDF set names that should be initialized
loglevel Coded logging level
reference PDF set which is used to produce the Monte Carlos
Definition at line 51 of file hist_maker.cpp.
References allPdfsets, ERROR, gLogLevel, and INFO.
void make_hists (char *input_file, char *tree_name, char *tree_cuts, char **branches, doublelumi, doublecross_section, intn_pdfs, char **PDFsets, char *PDFnorm, char *histname, char *output_file, intn_binning, double *binning)
Function to coordinate the creation of the reweighted histograms. This function prints if necessary the most important information on the reweighting process. It creates the output file an initialzes the necessary histograms with the user defined binning. It calls the analyser and the writer and cleans all histograms and files in the end. This function is also called by RATA_PDF.
Parameters:
input_file Name of the file from which the tree should be read
tree_name Name of the TTree that should be read
tree_cuts String of cuts that should be applied to the tree
branches Array with the name of the branches in the tree
lumi Luminosity
cross_section Cross section of the process
n_pdfs Number of PDF sets to be analyzed
PDFsets Array with the name of the PDF sets to be analyzed
PDFnorm Name of the PDF set which should be used for the normalization
histname Name that all filled histograms should have
output_file Name that the output file should get
n_binning Number of bins that each histogram should have
binning Array with the bin edges for the histograms
Definition at line 159 of file hist_maker.cpp.
References allPdfsets, analyser(), HistClass::CreateHisto(), DEBUG, HistClass::DeleteHisto(), get_scalefactor(), gLogLevel, INFO, info, Mainpdf, read_tree(), HistClass::RebinHisto(), and writer().
vector< vector<Float_t> > NNPDF_weighted_mean (vector< vector< TH1D * > >hist_scaled)
Function to calculate the overall uncertainty for a MC PDF set. This function calculates the overall uncertainty for a MC PDF set directly combined with the uncertainties due to alpha_S. The whole procedure follows the PDF4LHC recommendation.
Parameters:
hist_scaled Vector of Vector of all histograms necessary
v_as_errors Vector of Vector with the resulting uncertainties for each bin
Validate the number of replicas used from each set The number of replicas that are to be used from each set, (0,4,25,71,100,71,25,4,0) as mentioned in the PDF4LHC Interim Report, are assumed to be gaussianly distributed around a central value of alpha_s = 0.119. The following part of code varrifies the choosen number of replicas.
Combined PDF & alpha_s weighted mean value & standard deviation = PDF uncertainty Instead of randomly selecting which of the 100 replicas from each of the 7 sets to use, the following code uses all replicas from all sets (=100*7=700 replicas) and estimates a weighted mean. The weights are set to suit the gaussian assumption made above.
alpha_s = 0.116 -> file [5]
alpha_s = 0.117 -> file [6]
alpha_s = 0.118 -> file [7]
alpha_s = 0.119 -> file [8]
alpha_s = 0.120 -> file [9]
alpha_s = 0.121 -> file [10]
alpha_s = 0.122 -> file [11]
[replicas][bins]
sum over all 7 sets
sum over all 100 replicas in one set (1 to 100)
should be 300*100=30000 in this case
--> weighted mean
--> standard deviation
Definition at line 435 of file hist_maker.cpp.
Referenced by pdf_calcer_MC().
void pdf_calcer_hessian (intn_pdfSet, char **pdf_sets, char *outfile, char *out_par, char *infile, char *main_hist, char *shortname, doublepdf_correction, doubleas_plus_correction, doubleas_minus_correction, int *as_plus_number, int *as_minus_number)
Function to get the final uncertainty histograms for a hessian PDF set. This function reads in the necessary reweighted histograms, calls hessian_pdf_asErr and structures the output in a nice histogram format. This function is called by RATA_PDF.
Parameters:
n_pdfSet Number of PDF sets to be analyzed
pdf_sets Array with the name of the PDF sets to be analyzed
outfile Name that the output file should get
out_par How to handle the output file (RECREATE, UPDATE, ...)
infile Name of the input file
main_hist Base name of all histograms
shortname Short name that the output histograms should get
pdf_correction Global correction factor for this PDF set
as_plus_correction Correction factor for the alpha_S plus uncertainties
as_minus_correction Correction factor for the alpha_S minus uncertainties
as_plus_number Number of the alpha_S plus member, defined by the PDF config
as_minus_number Number of the alpha_S minus member, defined by the PDF config
Calculate uncertainty envelopes for CTEQ & MSTW, both with the scaling factors (C_90, C_59, C_79) and without
for upper & lower uncertainty histograms
Definition at line 350 of file hist_maker.cpp.
References hessian_pdf_asErr(), and HistClass::Write().
void pdf_calcer_MC (intn_pdfSet, char **pdf_sets, char *outfile, char *out_par, char *infile, char *main_hist, char *shortname)
Function to get the final uncertainty histograms for a MC PDF set. This function reads in the necessary reweighted histograms, calls NNPDF_weighted_mean and structures the output in a nice histogram format. This function is called by RATA_PDF.
Parameters:
n_pdfSet Number of PDF sets to be analyzed
pdf_sets Array with the name of the PDF sets to be analyzed
outfile Name that the output file should get
out_par How to handle the output file (RECREATE, UPDATE, ...)
infile Name of the input file
main_hist Base name of all histograms
shortname Short name that the output histograms should get
for upper & lower uncertainty histograms
Definition at line 506 of file hist_maker.cpp.
References NNPDF_weighted_mean(), and HistClass::Write().
void raw_input (TStringquestion)
Function to simulate raw_input from python. This function prints a message and waits for user input.
Parameters:
question TString of the message that should be printed
Definition at line 21 of file hist_maker.cpp.
Referenced by helper::farewell_output(), and pdf_plotter::main().
TTree* read_tree (char *filename, char *tree_name, char *tree_cuts)
Function to read and cut a tree from a .root file. This function reads in a TTree from a given .root files, applies given cuts and stores the cutted tree in the memory
Parameters:
filename Name of the file from which the tree should be read
tree_name Name of the TTree that should be read
tree_cuts String of cuts that should be applied
smallerTree Final read in and cutted tree
Definition at line 28 of file hist_maker.cpp.
References DEBUG, and datasets::file.
Referenced by make_hists().
bool writer (char *histname, intn_pdfs, char **PDFsets)
Function to write the histograms in an output file. This function writes the histograms in an output files, and checks the bin content of each histogram, negative bin contents are set to zero.
Parameters:
histname Name that all filled histograms have
n_pdfs Number of PDF sets to be analyzed
PDFsets Array with the name of the PDF sets to be analyzed
bool Either true(successfull writing) or false(something failed)
Definition at line 139 of file hist_maker.cpp.
References allPdfsets, ERROR, HistClass::SetToZero(), and HistClass::Write().
Referenced by make_hists().
Variable Documentation
vector<vector< LHAPDF::PDF* > > allPdfsets
Vector of Vector of all necessary PDF sets.
Definition at line 210 of file hist_maker.h.
Referenced by analyser(), init_bg(), make_hists(), and writer().
int gLogLevel = 4
Logging level, coded as an integer (errors=1, warnings=2, info=3, debug=4,5,...)
Definition at line 32 of file hist_maker.h.
Referenced by init_bg(), and make_hists().
map<TString, TH1D * > histo [static]
Map of a string and histogram, for easy histogram handling.
Definition at line 212 of file hist_maker.h.
Referenced by HistClass::ClearHisto(), HistClass::CreateHisto(), HistClass::DeleteHisto(), HistClass::Fill(), HistClass::RebinHisto(), HistClass::ReturnHist(), HistClass::SetToZero(), and HistClass::Write().
ProcInfo_t info
Process info, to get present memory usage etc.
Definition at line 53 of file hist_maker.h.
Referenced by analyser(), and make_hists().
LHAPDF::PDF* Mainpdf
PDF set that will be used for normalization.
Definition at line 208 of file hist_maker.h.
Referenced by analyser(), and make_hists().
Author
Generated automatically by Doxygen for tools3a from the source code.