.TH "letHerFly" 3 "Fri Feb 6 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
letHerFly \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBaddtime\fP"
.br
.ti -1c
.RI "def \fBletHerFly\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def letHerFly\&.addtime (tfor, tsince, tto)"

.PP
Definition at line 13 of file letHerFly\&.py\&.
.PP
Referenced by letHerFly()\&.
.SS "def letHerFly\&.letHerFly (filename)"

.PP
Definition at line 23 of file letHerFly\&.py\&.
.PP
References addtime()\&.
.SS "def letHerFly\&.main (stdscr)"

.PP
Definition at line 125 of file letHerFly\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
