music_crab3
NAME
music_crab3 -
MUSiC wrapper for crab3.
SYNOPSIS
Functions
def main
def createCrabConfig
def preloadProcess
def writeCrabConfig
def getRunRange
def readSampleFile
def getExistingProcesses
def getGlobalTag
def createDBlink
def submitSample2db_dump_csv
def submitSample2db
def submitSample2dbOld
def createTag
def setupLogging
def commandline_parsing
Variables
string COMMENT_CHAR = '#'
list log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
string date = '%F %H:%M:%S'
tuple skimmer_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject' )
tuple lumi_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/lumi' )
tuple config_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/configs' )
tuple log = logging.getLogger( 'music_crab' )
runOnMC = False
runOnData = False
runOnGen = False
Detailed Description
MUSiC wrapper for crab3.
music_crab is a wrapper script that has been developed to submit the large number of tasks (more or less) automatically, needed to get all data and MC. The script automatically creates CRAB config files according to the dataset file provided. crab3 rebuilds the previous crab2 functionality and relies on the work in the previous version
Author:
Tobias Pook
Function Documentation
def music_crab3.commandline_parsing (parsingController)
Definition at line 695 of file music_crab3.py.
References main().
Referenced by main().
def music_crab3.createCrabConfig (SampleFileInfoDict, sampleinfo, options)
Definition at line 125 of file music_crab3.py.
Referenced by main().
def music_crab3.createDBlink (options)
Definition at line 446 of file music_crab3.py.
Referenced by main().
def music_crab3.createTag (options, skimmer_dir)
Definition at line 589 of file music_crab3.py.
References music_crab.gitTag.
Referenced by main().
def music_crab3.getExistingProcesses ()
Definition at line 397 of file music_crab3.py.
def music_crab3.getGlobalTag (options)
Definition at line 430 of file music_crab3.py.
Referenced by main().
def music_crab3.getRunRange ()
Definition at line 289 of file music_crab3.py.
def music_crab3.main ()
Definition at line 52 of file music_crab3.py.
References commandline_parsing(), createCrabConfig(), createDBlink(), createTag(), getGlobalTag(), readSampleFile(), setupLogging(), submitSample2db(), submitSample2db_dump_csv(), and writeCrabConfig().
Referenced by commandline_parsing().
def music_crab3.preloadProcess (name, sample, SampleFileInfoDict)
Definition at line 253 of file music_crab3.py.
def music_crab3.readSampleFile (filename, options)
Definition at line 292 of file music_crab3.py.
Referenced by main().
def music_crab3.setupLogging (options)
Definition at line 685 of file music_crab3.py.
Referenced by main().
def music_crab3.submitSample2db (samplename, datasetpath, SampleFileInfoDict, options, dblink)
Definition at line 478 of file music_crab3.py.
Referenced by main().
def music_crab3.submitSample2db_dump_csv (samplename, datasetpath, SampleFileInfoDict, options)
Definition at line 458 of file music_crab3.py.
Referenced by main().
def music_crab3.submitSample2dbOld (name, sample, SampleFileInfoDict, dblink)
Definition at line 531 of file music_crab3.py.
def music_crab3.writeCrabConfig (name, config, options)
Definition at line 272 of file music_crab3.py.
Referenced by main().
Variable Documentation
string music_crab3.COMMENT_CHAR = '#'
Definition at line 34 of file music_crab3.py.
tuple music_crab3.config_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/configs' )
Definition at line 40 of file music_crab3.py.
string music_crab3.date = '%F %H:%M:%S'
Definition at line 36 of file music_crab3.py.
tuple music_crab3.log = logging.getLogger( 'music_crab' )
Definition at line 43 of file music_crab3.py.
list music_crab3.log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
Definition at line 35 of file music_crab3.py.
tuple music_crab3.lumi_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject/Skimming/test/lumi' )
Definition at line 39 of file music_crab3.py.
music_crab3.runOnData = False
Definition at line 47 of file music_crab3.py.
music_crab3.runOnGen = False
Definition at line 48 of file music_crab3.py.
music_crab3.runOnMC = False
Definition at line 46 of file music_crab3.py.
tuple music_crab3.skimmer_dir = os.path.join( os.environ[ 'CMSSW_BASE' ], 'src/MUSiCProject' )
Definition at line 38 of file music_crab3.py.
Author
Generated automatically by Doxygen for tools3a from the source code.