pdf_plotter
NAME
pdf_plotter -
Small script to plot the uncertainty bands calculated with RATA_PDF.
SYNOPSIS
Functions
def setTDRStyle
def set_palette
def reader
Function to read a histogram from a given file in the memory.
def main
Main function.
Variables
string path = '/home/home1/institut_3a/erdweg/Desktop/Software/SirPlotAlot/'
tuple tdrStyle = r.TStyle('tdrStyle','Style for P-TDR')
tuple tdrStyle2 = r.TStyle('tdrStyle2','Style for P-TDR')
list colors = [1, 2, 3, 4, 6, 7, 8, 9, 11]
list markers = [20, 21, 22, 23, 24, 25, 26, 27, 28]
list styles = [1, 2, 3, 4, 5, 6, 7, 8, 9]
Detailed Description
Small script to plot the uncertainty bands calculated with RATA_PDF.
This script can be used to plot the uncertainty bands of different PDF sets which were calculated with the RATA_PDF framework.
Function Documentation
def pdf_plotter.main ()
Main function. In this function the different histograms are read added and plotted together.
Definition at line 217 of file pdf_plotter.py.
References raw_input(), reader(), and setTDRStyle().
def pdf_plotter.reader (file, hist)
Function to read a histogram from a given file in the memory. In this function the .root file is opened and the histogram is read in the memory. At the moment also a rebinning with the factor 20 is done.
Parameters:
file String of the file name from which the histogram should be read
hist String of the histogram name to be read
ohist TH1F histogram that was read
Definition at line 203 of file pdf_plotter.py.
Referenced by main().
def pdf_plotter.set_palette (name, ncontours = 999)
Set a color palette from a given RGB list
stops, red, green and blue should all be lists of the same length
see set_decent_colors for an example
Definition at line 167 of file pdf_plotter.py.
def pdf_plotter.setTDRStyle (logy)
Definition at line 18 of file pdf_plotter.py.
Referenced by main().
Variable Documentation
list pdf_plotter.colors = [1, 2, 3, 4, 6, 7, 8, 9, 11]
Definition at line 162 of file pdf_plotter.py.
list pdf_plotter.markers = [20, 21, 22, 23, 24, 25, 26, 27, 28]
Definition at line 163 of file pdf_plotter.py.
string pdf_plotter.path = '/home/home1/institut_3a/erdweg/Desktop/Software/SirPlotAlot/'
Definition at line 13 of file pdf_plotter.py.
list pdf_plotter.styles = [1, 2, 3, 4, 5, 6, 7, 8, 9]
Definition at line 164 of file pdf_plotter.py.
tuple pdf_plotter.tdrStyle = r.TStyle('tdrStyle','Style for P-TDR')
Definition at line 15 of file pdf_plotter.py.
tuple pdf_plotter.tdrStyle2 = r.TStyle('tdrStyle2','Style for P-TDR')
Definition at line 16 of file pdf_plotter.py.
Author
Generated automatically by Doxygen for tools3a from the source code.