.TH "RATA_PDF/python/RATA_PDF.py" 3 "Fri Feb 6 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RATA_PDF/python/RATA_PDF.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRATA_PDF\fP"
.br
.RI "\fIRWTH Aachen Three A Parton Distribution Functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBRATA_PDF\&.init_pdfs\fP"
.br
.RI "\fIFunction to init the PDF sets\&. \fP"
.ti -1c
.RI "def \fBRATA_PDF\&.pdf_file_loop\fP"
.br
.RI "\fIFunction to loop over all files and caluclate the pdf reweighted histograms\&. \fP"
.ti -1c
.RI "def \fBRATA_PDF\&.calc_pdf_uncer\fP"
.br
.RI "\fIFunction to calculate the PDF uncertainties\&. \fP"
.ti -1c
.RI "def \fBRATA_PDF\&.main\fP"
.br
.RI "\fIMain function to run the whole PDF uncertainty calculation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
