RATA_PDF
NAME
RATA_PDF -
RWTH Aachen Three A Parton Distribution Functions.
SYNOPSIS
Functions
def init_pdfs
Function to init the PDF sets.
def pdf_file_loop
Function to loop over all files and caluclate the pdf reweighted histograms.
def calc_pdf_uncer
Function to calculate the PDF uncertainties.
def main
Main function to run the whole PDF uncertainty calculation.
Detailed Description
RWTH Aachen Three A Parton Distribution Functions.
calculate systematic uncertainties due to PDFs and alpha_S on background and signal Monte Carlo
written by Soeren Erdweg 2013-2014
Function Documentation
def RATA_PDF.calc_pdf_uncer (run_samples, options, c_par, pdf_cfg, mc_cfg, lib)
Function to calculate the PDF uncertainties. In this function the uncertainty due to a PDF set is calculated from the different shifted histograms produced previously. This is done for each PDF set as defined by the pdf config file.
Parameters:
run_samples List of samples that should be analyzed
options Options that given to the program
c_par List of parameter for the C++ library functions
pdf_cfg Config file for the different PDF sets
mc_cfg Config file for the MC samples that should be studied
lib C++ library from which th init function is used here
Todo
outfile parameters
include copier 'signal_mover.py'
Definition at line 110 of file RATA_PDF.py.
Referenced by main().
def RATA_PDF.init_pdfs (c_par, log_level, lib)
Function to init the PDF sets. In this function the different PDF sets as specified by the config file are initialized.
Parameters:
c_par Dictionary of the different parameters from the config file
log_level Integer to indicate the logging level
lib C++ library from which th init function is used here
Definition at line 22 of file RATA_PDF.py.
References helper.update_progress().
Referenced by main().
def RATA_PDF.main ()
Main function to run the whole PDF uncertainty calculation. In this function all necessary PDF sets are initialized, all samples are read and weighted. The histograms of the reweighted events are produced and the resulting uncertainty bands for each PDF set are calculated
Definition at line 188 of file RATA_PDF.py.
References calc_pdf_uncer(), helper.config_parsing(), helper.control_output(), helper.farewell_output(), helper.final_file_check(), helper.get_event_number_list(), init_pdfs(), helper.make_c_parameters(), helper.option_parsing(), pdf_file_loop(), and helper.welcome_output().
def RATA_PDF.pdf_file_loop (eventlist, total_events, filelist, c_par, xs_cfg, mc_cfg, pdf_cfg, lib)
Function to loop over all files and caluclate the pdf reweighted histograms. In this function the events will be reweighted according to the different PDF sets as specified by the config file and filled in histograms. This is done for every file as specified by the config files.
Parameters:
eventlist
total_events Number of total events to be processed, to update the status bar
filelist List of files for which the pdf histograms should be created
c_par List of parameter for the C++ library functions
xs_cfg Cross section config file
mc_cfg Config file for the MC samples that should be studied
pdf_cfg Config file for the different PDF sets
lib C++ library from which th init function is used here
run_samples List of samples that were processed
Todo
change to multiprocessing
calculate expected run time
Definition at line 63 of file RATA_PDF.py.
References helper.update_progress().
Referenced by main().
Author
Generated automatically by Doxygen for tools3a from the source code.