.TH "scripts/test_manager.py" 3 "Fri Feb 6 2015" "tools3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/test_manager.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBtest_manager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest_manager\&.mp_crab_worker\fP"
.br
.ti -1c
.RI "def \fBtest_manager\&.crab_worker\fP"
.br
.ti -1c
.RI "def \fBtest_manager\&.commandline_parsing\fP"
.br
.ti -1c
.RI "def \fBtest_manager\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtest_manager\&.serverLock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "tuple \fBtest_manager\&.optionsLock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "tuple \fBtest_manager\&.mylogger\fP = logging\&.getLogger('watchfrog')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tools3a from the source code\&.
